### ISSUE TITLE
Execute axios post response

### ISSUE THREAD

**Issue by Cancellara** [axios/axios#2684] opened 2020-01-21 16:46 UTC
Hi,

I´m working in a laravel app and i´m trying to make a post request from a Vue JS component like laravel method, so when i make the post request i would like the app go to the url received from the laravel controller on the http post response. I have the next code in my vue JS component methods:

```
submit: function() {

                const data = {
                    name: this.name,
                 
                };

                console.log('submit!')
                this.$v.$touch()
                if (this.$v.$invalid) {
                    this.submitStatus = 'ERROR'
                } else {

                    let currentObj = this;
                    axios.post('/group', data).then(function (response) {
                        currentObj.output = response.data;
                    }).catch(function (error) {
                        currentObj.output = error;
                    });

                }
            },
```
When i execute the code, the post request is done, i have the data sent on my database tables, however, the application is not redirected as i expect.

How the app can be redirected to the URL returned on laravel controller method?

**Comment by textbook** [comment] 2020-01-21 18:14
Likely duplicate of #932

**Comment by Cancellara** [comment] 2020-01-22 11:01
Well, question is similar but not exactly the same. This post has given me some clues, but i cannot resolve it completely.

With an axios interceptor i take the response, and i access to the request URL:

```
axios.interceptors.response.use(function (response) {
                      
                        let url = response.request.responseURL;
                        console.log(url);
                      
                    }
```

But i´m not able to redirect the app to this URL, i try with axios.get:

`axios.get(url);`

But  i get the next error message:

_

> app.js:2014 Uncaught (in promise) TypeError: Cannot read property 'request' of undefined

_
The error, theoretically, is on let url = response.request.responseURL; line code, but however it works, because in my log i can see the URL. 

How can i redirect the app to the Response requestURL? 

Also, i have another doubt. I return some paramenters in the Laravel Controller, is it possible to access them from the axios response? 

`return redirect(route('group.index'))->with('notification', trans('warehouse.group-created'));`

**Comment by textbook** [comment] 2020-01-22 12:31
`axios.get(url);` would start another XHR request, as far as I can tell you want to actually _change the page the app is on_ - as shown in the linked issue, that would be something like `window.location = ...`.

**Comment by Cancellara** [comment] 2020-01-22 14:55
Ok, thank you very much textbook, it works!

I will continue investigate if its possible to take the response parameters.

**Closed** 2020-01-23 15:02 UTC
