### ISSUE TITLE
Delete请求时data没有正确发送

### ISSUE THREAD

**Issue by qmhc** [axios/axios#3292] opened 2020-09-17 09:17 UTC
#### Describe the bug

在发送 delete 请求时，传入 data

在 0.19.2 版本的时候，该 data 是能正确发送，并被后端 `@RequestBody` 正确解析的，在 0.20.0 版本后该 data 没有被正确发送，进而会导致数据接收不到或者发生 400 错误

#### To Reproduce

```js
import Axios from 'axios'

Axios.delete('/api', {
  headers: {
      'Content-Type': 'application/json'
  },
  data: jsonData
})
```

#### Expected behavior

`options.data` 的数据能被正确发送至后端

#### Environment
 - Axios Version [0.20.0]
 - Browser [Chrome]

#### Additional context/Screenshots

![image](https://user-images.githubusercontent.com/40221744/93451067-47a15a00-f909-11ea-855a-cfdeb6613f90.png)

**Comment by kasper** [comment] 2020-09-17 11:48
I’m seeing the same issue. The data is not attached to DELETE requests.

**Comment by Nicholaiii** [comment] 2020-09-17 13:24
The delete instance method does not take data. Use request instead:

`axios.request({
  method: 'delete',
  url,
  data
})`

**Comment by tobias-grasse** [comment] 2020-09-17 14:16
Also hitting this after updating to 0.20.0.

@Nicholaiii Please note that @qmhc 's code example does not use the positional `data` argument (which would indeed not be in the `delete` [signature](https://github.com/axios/axios#instance-methods)), but the `data` config option – which should work for `DELETE` requests as well, per [the docs](https://github.com/axios/axios#request-config). #2887 explicitly added this to the docs, so its misleading at least.

**Comment by Nicholaiii** [comment] 2020-09-17 17:48
> Also hitting this after updating to 0.20.0.
> 
> @Nicholaiii Please note that @qmhc 's code example does not use the positional `data` argument (which would indeed not be in the `delete` [signature](https://github.com/axios/axios#instance-methods)), but the `data` config option – which should work for `DELETE` requests as well, per [the docs](https://github.com/axios/axios#request-config). #2887 explicitly added this to the docs, so its misleading at least.
> 
> EDIT: Well, like others in this thread I completely overlooked the pinned issue which confirms it's a regression in 0.20.0, and #3282 fixes the issue. Duplicate of #3220

I see. Either way, the request option fixes the issue untill the PR is merged.

**Comment by chinesedfan** [comment] 2020-09-19 02:37
Duplicate of #3220. Sorry for the breaking, and hope #3282 can be merged and released soon.

**Closed by chinesedfan** 2020-09-19 02:37 UTC
Labels: status:possible bug

**Comment by jasonsaayman** [comment] 2020-10-23 16:42
Hi,

Axios version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks

**Comment by qmhc** [comment] 2020-10-24 01:26
@jasonsaayman 
Now is working well.
Thanks.
