### ISSUE TITLE
Make AxiosRequestConfig type extensible

### ISSUE THREAD

**Issue by Stekmo** [axios/axios#3672] opened 2021-03-09 15:53 UTC
#### Is your feature request related to a problem? Please describe.
My problem is that I get type errors if I try to add custom properties to the AxiosRequestConfig parameter. I have a project built in TypeScript where I'm using interceptors to log information about requests being made. For certain request I'd like to include parts of the payload in the log itself.

For example, let's say I have a function
```
function updateProduct(product: Product) {
  return axios.put(`/products/${product.id}/`, product)
}
```
This function may be called multiple times, in multiple places in my app. Every time a product is updated, I want to include the product name and quantity in the request log. The request log is being made in my interceptor:
```
axios.interceptors.request.use((config) => {
  console.log('API Request', {
    url: config.url,
  })
  return config
})
```

The issue I'm facing is with the type AxiosRequestConfig. If I simply ignore the type, I can pass the data that I want to log through this parameter, like this.
```
function updateProduct(product: Product) {
  return axios.put(`/products/${product.id}/`, product, {
    metadata: {
      product_name: product.name,
      product_quantity: product.quantity,
    }
  })
}

axios.interceptors.request.use((config) => {
  console.log('API Request', {
    url: config.url,
    metadata: config.metadata,
  })
  return config
})
```

#### Describe the solution you'd like
Make AxiosRequestConfig type extensible.

#### Describe alternatives you've considered
Ignoring the type. // @ts-ignore

#### Additional context
![Screenshot 2021-03-09 at 16 38 41](https://user-images.githubusercontent.com/22430302/110496622-f45cd700-80f5-11eb-9a87-73d1acc64e74.png)

**Comment by EliRobinson** [comment] 2022-03-03 00:38
Is this a dupe of this? https://github.com/axios/axios/pull/1964

**Comment by jasonsaayman** [comment] 2022-06-12 17:56
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Closed by jasonsaayman** 2022-06-12 17:56 UTC
Labels: feature
