### ISSUE TITLE
upgrading from 0.19.0 to 0.19.1 breaks test suite because of cors

### ISSUE THREAD

**Issue by mlarcher** [axios/axios#2768] opened 2020-02-19 14:08 UTC
**Describe the bug**
When upgrading from 0.19.0 to 0.19.1, our test suite breaks because `nock` receives the cors OPTIONS call, which it did not receive before and did not expect. This is a breaking change, and I wouldn't expect the OPTIONS call to be made during tests.

Here's the error stack :
```sh
Error: Error: Nock: No match for request {
        "method": "OPTIONS",
        "url": "http://some_url.org/",
        "headers": {
          "origin": "http://localhost",
          "access-control-request-method": "PUT",
          "user-agent": "Mozilla/5.0 (darwin) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.12.0",
          "host": "some_url.org",
          "content-length": 0
        }
      }
          at Object.dispatchError (/Users/somatt/www/hm/_hm/app/client/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
          at EventEmitter.<anonymous> (/Users/somatt/www/hm/_hm/app/client/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:676:20)
          at EventEmitter.emit (events.js:215:7)
          at Request.<anonymous> (/Users/somatt/www/hm/_hm/app/client/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:412:47)
          at Request.emit (events.js:210:5)
          at Request.onRequestError (/Users/somatt/www/hm/_hm/app/client/node_modules/request/request.js:881:8)
          at OverriddenClientRequest.emit (events.js:210:5)
          at /Users/somatt/www/hm/_hm/app/client/node_modules/nock/lib/intercepted_request_router.js:101:11
          at processTicksAndRejections (internal/process/task_queues.js:75:11)
          at runNextTicks (internal/process/task_queues.js:62:3) undefined
```

**Expected behavior**
Mostly, a patch version should not break anything and breaking changes should be documented.

**Environment:**
 - Axios Version 0.19.1
 - OS: OSX 10.15.3 (19D76)
 - nock: 11.7.0

**Comment by chinesedfan** [comment] 2020-02-22 08:40
Duplicate of #2654.

**Closed by chinesedfan** 2020-02-22 08:40 UTC
