### ISSUE TITLE
Error response data nodejs

### ISSUE THREAD

**Issue by macductan** [axios/axios#5298] opened 2022-11-23 10:48 UTC
### Describe the bug

`
var axios = require('axios');
var data = JSON.stringify({
  "production_status": "",
  "package_status": [],
  "extra_status_reason": [],
  "page": 1,
  "limit": 1
});

var config = {
  method: 'post',
  url: 'https://example.com/',
  headers: { 
    'Authorization': 'Bearer token', 
  },
  data: {
    "production_status": "",
    "package_status": [],
    "extra_status_reason": [],
    "page": 1,
    "limit": 1
  }
};

axios(config)
.then(function (response) {
  console.log(response.data);
})
.catch(function (error) {
  console.log(error);
});
`

When i send API this response
![image](https://user-images.githubusercontent.com/73536823/203527806-e7f74bca-c6aa-45b0-b9b5-73138981228b.png)
I want respose must be json like that
![image](https://user-images.githubusercontent.com/73536823/203528048-a5555c94-ce21-4f7a-922b-53337e49aca6.png)

### Axios Version

1.2.0

### Node.js Version

14.20.1

**Comment by dgurinovych** [comment] 2022-11-23 11:01
I'm getting the same error :(

**Comment by ddugovic** [comment] 2022-11-23 11:07
Ditto with https://lichess.org/api/user/Toadofsky 

Routing through proxy server BeeCeptor I can observe that Lichess response data are valid, however axios 1.2.0 does not handle the gzip encoding:
```
    _header: 'GET /api/user/Toadofsky?trophies=true HTTP/1.1\r\n' +
      'Accept: application/json\r\n' +
      'User-Agent: axios/1.2.0\r\n' +
      'Accept-Encoding: gzip, deflate, br\r\n' +
      'Host: lichess.free.beeceptor.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
```

**Comment by cetteup** [comment] 2022-11-23 11:09
I'm also seeing this, plain old GET requests in my case.

**Comment by davidfilat** [comment] 2022-11-23 11:10
I have the same problem since upgrading to 1.2.0
<img width="1628" alt="CleanShot 2022-11-23 at 13 10 47@2x" src="https://user-images.githubusercontent.com/1475163/203532451-2e154a2d-20fc-4f62-a641-08e61c53b1f7.png">

**Comment by dgurinovych** [comment] 2022-11-23 11:24
The temporary workaround is to set `Accept-Encoding` header to something other than `gzip, deflate, be` to `application/json` for instance. By loosing compressed data exchange of course.

**Comment by ddugovic** [comment] 2022-11-23 11:35
Indeed, that workaround works in my case... based upon https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding I select `identity`:

```
    return axios.get(url, { headers: { Accept: 'application/json', 'Accept-Encoding': 'identity' }, params: { trophies: true } })
```

**Comment by davidfilat** [comment] 2022-11-23 11:43
> Indeed, that workaround works in my case... based upon https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding I select `identity`:
> 
> ```
>     return axios.get(url, { headers: { Accept: 'application/json', 'Accept-Encoding': 'identity' }, params: { trophies: true } })
> ```

Thank you! Worked for me!

**Comment by ddugovic** [comment] 2022-11-23 11:53
Can a maintainer confirm that manually adding `Accept-Encoding: identity` to every GET request is not the intended way to use axios (i.e., this issue is a regression)?

**Comment by SSANSH** [comment] 2022-11-23 14:11
+1

**Comment by jweingarten** [comment] 2022-11-23 14:21
+1

**Comment by jsfelix** [comment] 2022-11-23 15:19
Some problem here with gzip response and axios 1.2.0

**Comment by ddugovic** [comment] 2022-11-23 16:16
I've started migrating all my applications to `fetch` https://blog.logrocket.com/fetch-api-node-js/

**Comment by valbofs** [comment] 2022-11-23 16:49
> Indeed, that workaround works in my case... based upon https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding I select `identity`:
> 
> ```
>     return axios.get(url, { headers: { Accept: 'application/json', 'Accept-Encoding': 'identity' }, params: { trophies: true } })
> ```

Thank you!! This fixed it!

**Comment by semsturgut** [comment] 2022-11-23 16:58
I spent my whole day because of this problem...😩

**Comment by andreyanez** [comment] 2022-11-23 18:49
> Indeed, that workaround works in my case... based upon https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding I select `identity`:
> 
> ```
>     return axios.get(url, { headers: { Accept: 'application/json', 'Accept-Encoding': 'identity' }, params: { trophies: true } })
> ```

Thank you! I was wrestiling with this problem yesterday

**Comment by alisson-acioli** [comment] 2022-11-23 19:42
This is serious. Here at the company it stopped working when **npm install** was given in my package and there was a lot of support, luckily we decided to see if there was any update on axios. Here we solved leaving the **version 1.1.13** that was running.

**Comment by jsfelix** [comment] 2022-11-23 23:15
> This is serious. Here at the company it stopped working when **npm install** was given in my package and there was a lot of support, luckily we decided to see if there was any update on axios. Here we solved leaving the **version 1.1.13** that was running.

use ```npm ci``` or ```yarn install --frozen-lockfile``` and avoid problems about package updates.

**Comment by nnfans** [comment] 2022-11-24 04:14
spent hours to find this page 🤣 
change `package.json` version for `axios` to lower `"axios": "~1.1.0"` and wait for the fix to be released

**Comment by deKadir** [comment] 2022-11-24 06:20
i downgraded axios to ^0.19.2 it works now

**Comment by Myasir92** [comment] 2022-11-24 07:42
I spent my entire day because of this same problem and fixed it by downgrading **Axios** to 1.1.3 🤣

.

**Comment by djaffer** [comment] 2022-11-24 08:29
same I was scratching my head all day what is broken. reverting back to previous version.

**Comment by dnohr** [comment] 2022-11-24 08:36
Can confirm the issue as well. Unfortunately it's stopped working everywhere, just as with the v1 release. Looking forward to a fix, as I normally update all libraries to the latest via the npm-check-updates updater.

**Comment by ishaiavrahami** [comment] 2022-11-24 09:10
same here getting issue

**Comment by ishaiavrahami** [comment] 2022-11-24 09:12
this is ridiculous, other dependencies are reliant and system is down since yesterday

**Comment by SSANSH** [comment] 2022-11-24 10:50
I saw that update of axios also cause an issue into ajv validation....

**Comment by lukehillonline** [comment] 2022-11-24 12:45
We too are experiencing this issue.

Am I right in thinking that `Accept-Encoding: identity` is not a good fix as this would disable all encoding in HTTP responses, dramatically impacting performance?

We need a proper fix for this.

**Comment by alisson-acioli** [comment] 2022-11-24 13:06
The best solution is to go back to previous version 1.1.3 and wait for 1.2 to fix. There's already a commit awaiting approval it seems to me.

**Comment by PythonCoderAS** [comment] 2022-11-24 17:38
For me I just put in the heading `"Content-Type": "application/json"`. Prior I was not putting it in but now that I am it's working again.

**Comment by Carsten-Leue** [comment] 2022-11-24 19:59
The problem is caused by 
https://github.com/axios/axios/pull/5250
cc @DigitalBrainJS @jasonsaayman 

at this line:
```ts
const responseLength = +res.headers['content-length'];
```

If `res.headers` does **not** contain a `content-length` entry, then responeLength will be `NaN`

In that case this line:

```ts
if ((!responseLength || res.statusCode === 204) && res.headers['content-encoding']) {
```

Will cause a `content-encoding` header to be deleted and as a consequence axios will no longer unzip the response.

**Comment by alainkaiser** [comment] 2022-11-28 09:33
Same here. Locally it works, but not in a production env. I am getting the following response:

![image](https://user-images.githubusercontent.com/18368657/204243110-bb785361-6802-413d-a6d3-f89e520be0ad.png)

Setting "'Accept-Encoding': 'identity'" in the headers resolves the problem (as a workaround).

**Comment by macductan** [comment] 2022-11-28 09:53
> Indeed, that workaround works in my case... based upon https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding I select `identity`:
> 
> ```
>     return axios.get(url, { headers: { Accept: 'application/json', 'Accept-Encoding': 'identity' }, params: { trophies: true } })
> ```

It works to me. Thank you.
I will close this issue

**Comment by cupidchan** [comment] 2022-11-28 17:59
+1
@macductan, I saw you closed this issue. When do you think the fix be released? Thanks!

**Comment by cetteup** [comment] 2022-11-28 19:16
@macductan Closing the issue without a fix is a bit misleading. And the workaround is far from ideal.

Maybe you'd consider reopening the issue until this is actually fixed?

**Comment by cupidchan** [comment] 2022-11-28 19:22
Thanks @cetteup, I thought @macductan has already fixed that issue and closed it. If not, then it will be better to keep it opened since the workaround is not ideal because this issue regresses axios unzip feature for the returned result.

**Comment by n0rt0nthec4t** [comment] 2022-11-28 23:26
Have this issue too which caught me out wonder why json responses we're coming back all garbled.. Definitely shouldn't be closed

**Comment by itsnoteasytonameaccount** [comment] 2022-11-29 11:46
> The problem is caused by #5250 cc @DigitalBrainJS @jasonsaayman
> 
> at this line:
> 
> ```ts
> const responseLength = +res.headers['content-length'];
> ```
> 
> If `res.headers` does **not** contain a `content-length` entry, then `responeLength` will be `NaN`
> 
> In that case this line:
> 
> ```ts
> if ((!responseLength || res.statusCode === 204) && res.headers['content-encoding']) {
> ```
> 
> Will cause a `content-encoding` header to be deleted and as a consequence axios will no longer unzip the response.

I agree with. I try to modify `!responseLength` to `responseLength === 0` and it works;

**Comment by cenfun** [comment] 2022-11-30 07:01
same error when using v1.2.0
`
data: '\x1F�\b\x00\x00\x00\x00\x00\x04\x03d�An�0\x10E��u�<cl�\\��\x02\x05���\x04\x04�U\
`
![axios-bug](https://user-images.githubusercontent.com/334577/204729166-6b7d19ca-3ed4-4a00-bc10-b79713c232a0.png)

**Comment by jinsley8** [comment] 2022-11-30 07:33
> same error when using v1.2.0 `data: '\x1F�\b\x00\x00\x00\x00\x00\x04\x03d�An�0\x10E��u�<cl�\\��\x02\x05���\x04\x04�U\` ![axios-bug](https://user-images.githubusercontent.com/334577/204729166-6b7d19ca-3ed4-4a00-bc10-b79713c232a0.png)

Downgrade to `"axios": "1.1.3"` for now.

**Comment by sadjous** [comment] 2022-11-30 14:33
> > Indeed, that workaround works in my case... based upon https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding I select `identity`:
> > ```
> >     return axios.get(url, { headers: { Accept: 'application/json', 'Accept-Encoding': 'identity' }, params: { trophies: true } })
> > ```
> 
> Thank you!! This fixed it!

**Comment by ja-ka** [comment] 2022-11-30 15:25
Why has this been closed as completed? The issue still persists in `axios@1.3.0`. I don't think that setting the `Accept-Encoding: identify` explicitly should be the favored solution.

**Comment by nitroo88** [comment] 2022-11-30 22:08
same here :( currently `'Accept-Encoding': 'identity'` works...

**Comment by ghazanfarali345** [comment] 2022-12-01 14:18
> { headers: { Accept: 'application/json', 'Accept-Encoding': 'identity' },

It also worked for me in my case thanks bro

**Closed** 2022-12-01 14:22 UTC

**Comment by cupidchan** [comment] 2022-12-01 14:25
@jasonsaayman is this issue closed because it's really fixed in 1.3.1? Setting `Accept-Encoding': 'identity` is just a workaround but not the fix.

**Comment by jasonsaayman** [comment] 2022-12-02 13:16
No its close cause the PR that has the fix has been merged, this is how GitHub works. I will release this weekend

**Comment by maximedupre** [comment] 2022-12-03 00:34
For those that want to upgrade right now, use `1.2.0-alpha.1` (`npm i axios@next`)

**Comment by ricsantos** [comment] 2022-12-05 20:49
For those fixing this by downgrading to `1.1.3`, if you are using typescript you may want to downgrade further to `1.1.0` to avoid https://github.com/axios/axios/issues/5011

**Comment by jasonsaayman** [comment] 2022-12-06 06:36
Try the latest release v1.2.1 please

**Comment by salierykuba** [comment] 2022-12-07 06:16
> Indeed, that workaround works in my case... based upon https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding I select `identity`:
> 
> ```
>     return axios.get(url, { headers: { Accept: 'application/json', 'Accept-Encoding': 'identity' }, params: { trophies: true } })
> ```

thank you!, he has been fighting to solve this problem for three days;
 I'm using :axios:1.2.0
but please fix that properly, because I don't think it's good to inject it into every get.
but thank you very much!

**Comment by PythonCoderAS** [comment] 2022-12-08 00:24
You can always downgrade axios with no problems.

**Comment by frankiefab100** [comment] 2022-12-08 15:53
> Indeed, that workaround works in my case... based upon https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding I select `identity`:
> 
> ```
>     return axios.get(url, { headers: { Accept: 'application/json', 'Accept-Encoding': 'identity' }, params: { trophies: true } })
> ```

Thank you, you saved me a lot of time. It worked!

**Comment by razzeee** [comment] 2022-12-08 16:45
A fix for this has already been released, why would you still want to use the workaround?

**Comment by salierykuba** [comment] 2022-12-08 19:53
> A fix for this has already been released, why would you still want to use the workaroundi

I Will update yep 👍

**Comment by samharvey44** [comment] 2023-01-04 12:57
1.2.1 fixed issue, thanks. Drove me insane for 5 hours...

**Comment by samharvey44** [comment] 2023-01-04 12:58
1.2.1 fixed issue, thanks. Drove me insane for hours..

**Comment by NunoSempere** [comment] 2023-01-20 21:16
Hey, so I've been using axios for several years now, and I was really surprised that the problem I was having was coming from axios after all. Any ideas on why this happened, and what could be done to prevent similar issues in the future? 

If the cause is e.g., a lack of manpower I would be e.g., happy to donate some amount so that axios can continue to be maintained (though i don't see a quick link to do this in the repo).

**Comment by djaffer** [comment] 2023-01-23 02:03
The version 1.2.3 should fix it I think.
