### ISSUE TITLE
Headers malformed - identical Postman/Fetch request succeeds

### ISSUE THREAD

**Issue by Rob117** [axios/axios#809] opened 2017-04-01 07:42 UTC
When I try to make a delete request like so (user is auth info):
```
axios.delete(DOMAIN_NAME + '/auth/sign_out', {
      headers: user
    }).then(dispatch({ type: LOGOUT_USER }))
    .catch(dispatch({ type: LOGOUT_USER }));
  }
```
When I try to make the following request, I get a "authentication failed", which means no headers:
```
axios.post(DOMAIN_NAME + '/api/services/ocr', {
           headers: user
        }).then(response => console.log(response))
        .catch(error => console.log(error));
```

If I make an identical postman request, everything succeeds, so I don't think it's a CORS issue.

How can I troubleshoot this?

UPDATE:

Axios replaced with fetch code does the correct thing:
```
fetch(DOMAIN_NAME + '/api/services/ocr', {
          method: 'POST',
          headers: {
            'access-token': user['access-token'],
            uid: user.uid,
            client: user.client,
            'content-type': 'image/jpeg'
          }
        }).then(r => console.log(r)).catch(e => console.log(e));
```

Manually setting each header in Axios did nothing, but manually setting them in fetch ran well. I would strongly prefer to use Axios, however.

**Comment by takiarek** [comment] 2017-04-03 14:44
I have identical issue. In Chrome DevTools Network tab you can see that the headers map is put into the Request Payload instead of Request Headers.

**Comment by Rob117** [comment] 2017-04-22 05:29
@takiarek Thank you!

**Comment by davidyell** [comment] 2017-11-16 12:20
I have the same issue here. When I try and send my api authentication header, the header is not sent with the request, so I get a 403 Forbidden.

I've tried setting the header in my `axios.create()` and also in the instance with no luck.

**Comment by Rob117** [comment] 2018-01-18 09:28
It has been 8 months. No update on this? That's okay, but if it isn't something on the roadmap, maybe we should close it?

**Comment by michelarteta** [comment] 2018-02-15 23:26
having the same issue, the same GET request works on Postman but axios isn’t passing the headers. Any updates on this ? thanks a lot

**Comment by emilyemorehouse** [comment] 2018-02-18 17:15
I'm happy to look into this, but I'm having trouble reproducing the issue.

Here's my current test case with v0.17.1, where the specified `access-token` header is getting added to the request header:
<img width="696" alt="screen shot 2018-02-18 at 10 11 23 am" src="https://user-images.githubusercontent.com/4264897/36354614-5a80c7b6-1494-11e8-943c-e4b1661ca68a.png">

**Comment by davidyell** [comment] 2018-02-18 23:30
Use a non-standard header would be the thing to try. Something like `X-RandomToken`

**Comment by emilyemorehouse** [comment] 2018-02-18 23:46
`access-token` isn't a standard header, but here's with `X-RandomToken` in any case. 🤔 

<img width="685" alt="screen shot 2018-02-18 at 4 38 28 pm" src="https://user-images.githubusercontent.com/4264897/36358360-7aabe2ce-14ca-11e8-99af-ce6e127a4523.png">

**Comment by AllainPL** [comment] 2019-04-10 20:57
@emilyemorehouse I would assume that after 2 years, and one year since last message, it might be time to close this ;) especially that custom header is quite a regular use case, so probably if still happening it would be seen elsewhere.

**Comment by chinesedfan** [comment] 2019-12-07 08:49
> If I make an identical postman request, everything succeeds, so I don't think it's a CORS issue.

I want to correct something that CORS problems only occur in browser requests. And postman is much similar with Node.js requests. If someone still met this problem, feel free to open another issue with detailed descriptions. Thanks.

**Closed by chinesedfan** 2019-12-07 08:49 UTC
