### ISSUE TITLE
Axios send the same request twice and ignore the first response, only receives the second response.

### ISSUE THREAD

**Issue by newnewnet** [axios/axios#2825] opened 2020-03-17 05:51 UTC
**Describe the bug**
axios.post sends duplicate POST request and ignores the first response, only receives the second response.

**To Reproduce**
I don't know how to reproduce it since it's occurred.

```js
export const axiosAfterLoginRequest = (properties = {}, defaultConfig = {}) => (
  config = {}
) => {
  const {
    accessTokenKey = "",
    accessTokenValue,
    cookieName = STORAGE.USER_TOKEN
  } = properties
  const configMerge = merge(cloneDeep(defaultConfig), config)
  const headers = get(configMerge, "headers", {})
  const token = getLocalItem(cookieName)
  const accessToken = !isNil(accessTokenValue)
    ? accessTokenValue
    : get(token, accessTokenKey)
  if (!isNil(accessToken) && !isEmpty(accessToken)) {
    headers.Authorization = `Bearer ${accessToken}`
  }
  return { ...configMerge, headers, ...timestampConfig() }
}
const apiInstance = axios.create({
  baseURL: API_URL
})

const request = axiosAfterLoginRequest(
  { accessTokenKey: "access_token" },
  {
    headers: {
      post: {
        "Content-Type": "application/json"
      }
    }
  }
)

apiInstance.interceptors.request.use(request)

export const submitApi = (payload) =>
  apiInstance.post("url"), payload)

export function* submitSaga(action) {
   try {
      const response = yield call(submitApi, action.payload)
      yield put({type: "success"})
   } catch (e) {
      yield put({type: "error"})
   }
}
```
The submit function above is only called once, while the axios.post() is called twice. I have log for my system, in subject ***Additional context/Screenshots***

**Expected behavior**
The request is only sent once.

**Environment:**
 - Axios Version [e.g. 0.19.0]
 - OS: [e.g. Android 10; SM-G970U]
 - Browser [e.g. Chrome]
 - Browser Version [e.g. 80]
 - Additional Library Versions [e.g. React 16.8, redux 4.0.1 react-redux 7.1.0 redux-saga 1.0.3 ]

**Additional context/Screenshots**
<img width="1021" alt="Screen Shot 2563-03-17 at 12 26 08" src="https://user-images.githubusercontent.com/2849568/76825630-10b09580-684d-11ea-8b4e-2d28b5e5afd3.png">

You will see `request.query.t`  for first and second time. it same requested.

**Comment by BankNatthapon** [comment] 2020-03-17 11:50
+1

**Comment by chinesedfan** [comment] 2020-03-17 12:04
Can you provide the network panel request list in the browser, instead of the server logs?

**Comment by newnewnet** [comment] 2020-03-18 06:03
@chinesedfan 
```json
[{
  "_index": "log_2020-02",
  "_type": "request",
  "_id": "h0R0inABPJ1TmlIM0gHa",
  "_version": 1,
  "_score": null,
  "_source": {
    "env": "production",
    "request": {
      "body": {
        "paymentId": "id",
        "price": 30,
        "method": "braintree",
        "paymentObject": {
          "nonce": "token",
          "type": "CreditCard",
        }
      },
      "email": "test@gmail.com",
      "httpVersion": "1.1",
      "headers": {
        "host": "api.someurl.com",
        "x-request-id": "ccfd38ea73c14e26b7b6c4285e2f8a3a",
        "x-real-ip": "10.138.15.197",
        "x-forwarded-for": "10.138.15.197",
        "x-forwarded-host": "api.someurl.com",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
        "x-original-uri": "/api/v2/rental-submissions/id/credit-report/payment?t=1582870872332",
        "x-scheme": "https",
        "x-original-forwarded-for": "2601:681:8680:4ed0:91ed:9c39:9c62:47a1",
        "content-length": "459",
        "accept-encoding": "gzip",
        "cf-ipcountry": "US",
        "cf-ray": "56c04c1f3e6da02c-SLC",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "accept": "application/json, text/plain, */*",
        "sec-fetch-dest": "empty",
        "authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTU4YTkzYTU3MzExMjAwMWI4NTdiYWUiLCJlbWFpbCI6Ind5YXR0c21pdGg0MjdAZ21haWwuY29tIiwidHlwZSI6InJlbnRlciIsImlhdCI6MTU4Mjg2ODc5NCwiZXhwIjoxNTgyOTU1MTk0fQ.JFo4IvERk-K5Tszit0sqDF5BsqiX2x_OUzDdhIC3U6f08K6RMzePg_GQTdDI-2vCbHFDxfklzVe-XOnKTruzdiJiiPQXMIW1kuO-a3glvOiSMrg_ZfxRywHBP0tM9k7IzK1JVjMBum_vEtCNupVA4SWmp63e_-gCXucQqiC_F-KGDLKXUNK444oyrF3Pzjcs2kQsrJmhSHqhFeSww5DWFB04JaNYuinT8lDpqAP_gPp3XVEPf7uipdSVgi5M8DxHvmpZYQf069VxEgw4QBLwWDtnOASI1yjrqb3UQDkQGsKdMgVhAMOXeVP-SHKf7z9Br94Vtz70pCHxR51FZHoMkWG9dsuvAUcfWq8Qpv1Ml7tRpvE8tlvfG3GNL55eZvjreWKANu-QmXTEXXIJRech7RCWv-5cM1mrBy6MtF5XoIrPQ2LSVwujNwtSeqraksE-10IrAgWKcJ0y22hLSbKx7hgJ88FLatBIs_Fnni0MX-OTfBKrI8RBb8JCT0rTZo4IgCOFJ6GPniYSV6gjC48l0VfoMqLJygrwIgnZCMh4G8KLf4U5w84HuLKQCdSgvUM_Ts8bJfgcWRAFi7IDdkVgT1fq_9sZssCqJ87olXNbf76Kg3HGs_jIJ7Palrv5vXUYtHJnk7aGXF7Q8PAT9Hl97FUBYd2hyiLpnL-QLAH9ynI",
        "user-agent": "Mozilla/5.0 (Linux; Android 10; SM-G970U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.119 Mobile Safari/537.36",
        "content-type": "application/json;charset=UTF-8",
        "origin": "https://www.someurl.com",
        "sec-fetch-site": "same-site",
        "sec-fetch-mode": "cors",
        "referer": "https://www.someurl.com/apply/id/option/id/payment?utm_source=crmls&utm_medium=email",
        "accept-language": "en-US,en;q=0.9",
        "cf-connecting-ip": "2601:681:8680:4ed0:91ed:9c39:9c62:47a1",
        "cdn-loop": "cloudflare"
      },
      "method": "POST",
      "originalUrl": "/api/v2/rental-submissions/id/credit-report/payment?t=1582870872332",
      "path": "/api/v2/rental-submissions/id/credit-report/payment",
      "query": {
        "t": "1582870872332"
      },
      "route": {
        "path": "/rental-submissions/:rentalSubmissionId/credit-report/payment"
      }
    },
    "@timestamp": "2020-02-28T06:21:16.194Z",
    "response": {
      "statusCode": 409
    },
    "duration": 694,
    "error": {
      "stack": "PaymentGateWayError: Cannot use a payment_method_nonce more than once.\n    at Function._callee6$ (/app/src/services/rental-submission/credit-report.js:314:13)\n    at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)\n    at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:288:22)\n    at Generator.prototype.(anonymous function) [as throw] (/app/node_modules/regenerator-runtime/runtime.js:114:21)\n    at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _throw (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)\n    at <anonymous>",
      "message": "Cannot use a payment_method_nonce more than once.",
      "name": "PaymentGateWayError",
      "errors": {
        "validationErrors": {},
        "errorCollections": {
          "transaction": {
            "validationErrors": {
              "paymentMethodNonce": [
                {
                  "attribute": "payment_method_nonce",
                  "code": "91564",
                  "message": "Cannot use a payment_method_nonce more than once."
                }
              ]
            },
            "errorCollections": {}
          }
        }
      }
    },
    "os": {
      "totalmem": 7841001472,
      "freemem": 1229262848,
      "loadavg": [
        1.31884765625,
        0.8310546875,
        0.77392578125
      ]
    },
    "process": {
      "memory": {
        "rss": 104476672,
        "heapTotal": 52981760,
        "heapUsed": 44889168,
        "external": 52970
      }
    }
  },
  "fields": {
    "@timestamp": [
      "2020-02-28T06:21:16.194Z"
    ]
  },
  "highlight": {
    "request.email": [
      "@kibana-highlighted-field@wyattsmith427@/kibana-highlighted-field@@@kibana-highlighted-field@gmail.com@/kibana-highlighted-field@"
    ],
    "request.route.path": [
      "@kibana-highlighted-field@/rental-submissions/:rentalSubmissionId/credit-report/payment@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1582870876194
  ]
}, {
  "_index": "log_2020-02",
  "_type": "request",
  "_id": "7TV0inABhWHZpOgY0Kfv",
  "_version": 1,
  "_score": null,
  "_source": {
    "env": "production",
    "request": {
      "body": {
        "paymentId": "id",
        "price": 30,
        "method": "braintree",
        "paymentObject": {
          "nonce": "token",
          "type": "CreditCard",
        }
      },
      "email": "test@gmail.com",
      "httpVersion": "1.1",
      "headers": {
        "host": "api.someurl.com",
        "x-request-id": "84c15e8673370a65fbbf1a0b600f9465",
        "x-real-ip": "10.138.15.197",
        "x-forwarded-for": "10.138.15.197",
        "x-forwarded-host": "api.someurl.com",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https",
        "x-original-uri": "/api/v2/rental-submissions/id/credit-report/payment?t=1582870872332",
        "x-scheme": "https",
        "x-original-forwarded-for": "166.182.80.20",
        "content-length": "459",
        "accept-encoding": "gzip",
        "cf-ipcountry": "US",
        "cf-ray": "56c04c110be871d7-ORD",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "accept": "application/json, text/plain, */*",
        "sec-fetch-dest": "empty",
        "authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTU4YTkzYTU3MzExMjAwMWI4NTdiYWUiLCJlbWFpbCI6Ind5YXR0c21pdGg0MjdAZ21haWwuY29tIiwidHlwZSI6InJlbnRlciIsImlhdCI6MTU4Mjg2ODc5NCwiZXhwIjoxNTgyOTU1MTk0fQ.JFo4IvERk-K5Tszit0sqDF5BsqiX2x_OUzDdhIC3U6f08K6RMzePg_GQTdDI-2vCbHFDxfklzVe-XOnKTruzdiJiiPQXMIW1kuO-a3glvOiSMrg_ZfxRywHBP0tM9k7IzK1JVjMBum_vEtCNupVA4SWmp63e_-gCXucQqiC_F-KGDLKXUNK444oyrF3Pzjcs2kQsrJmhSHqhFeSww5DWFB04JaNYuinT8lDpqAP_gPp3XVEPf7uipdSVgi5M8DxHvmpZYQf069VxEgw4QBLwWDtnOASI1yjrqb3UQDkQGsKdMgVhAMOXeVP-SHKf7z9Br94Vtz70pCHxR51FZHoMkWG9dsuvAUcfWq8Qpv1Ml7tRpvE8tlvfG3GNL55eZvjreWKANu-QmXTEXXIJRech7RCWv-5cM1mrBy6MtF5XoIrPQ2LSVwujNwtSeqraksE-10IrAgWKcJ0y22hLSbKx7hgJ88FLatBIs_Fnni0MX-OTfBKrI8RBb8JCT0rTZo4IgCOFJ6GPniYSV6gjC48l0VfoMqLJygrwIgnZCMh4G8KLf4U5w84HuLKQCdSgvUM_Ts8bJfgcWRAFi7IDdkVgT1fq_9sZssCqJ87olXNbf76Kg3HGs_jIJ7Palrv5vXUYtHJnk7aGXF7Q8PAT9Hl97FUBYd2hyiLpnL-QLAH9ynI",
        "user-agent": "Mozilla/5.0 (Linux; Android 10; SM-G970U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.119 Mobile Safari/537.36",
        "content-type": "application/json;charset=UTF-8",
        "origin": "https://www.someurl.com",
        "sec-fetch-site": "same-site",
        "sec-fetch-mode": "cors",
        "referer": "https://www.someurl.com/apply/id/option/id/payment?utm_source=crmls&utm_medium=email",
        "accept-language": "en-US,en;q=0.9",
        "cf-connecting-ip": "166.182.80.20",
        "cdn-loop": "cloudflare"
      },
      "method": "POST",
      "originalUrl": "/api/v2/rental-submissions/id/credit-report/payment?t=1582870872332",
      "path": "/api/v2/rental-submissions/id/credit-report/payment",
      "query": {
        "t": "1582870872332"
      },
      "route": {
        "path": "/rental-submissions/:rentalSubmissionId/credit-report/payment"
      }
    },
    "@timestamp": "2020-02-28T06:21:13.996Z",
    "response": {
      "statusCode": 200
    },
    "duration": 2402,
    "os": {
      "totalmem": 13654306816,
      "freemem": 348090368,
      "loadavg": [
        0.22314453125,
        0.3466796875,
        0.46923828125
      ]
    },
    "process": {
      "memory": {
        "rss": 81301504,
        "heapTotal": 52981760,
        "heapUsed": 41745312,
        "external": 59616
      }
    }
  },
  "fields": {
    "@timestamp": [
      "2020-02-28T06:21:13.996Z"
    ]
  },
  "highlight": {
    "request.email": [
      "@kibana-highlighted-field@wyattsmith427@/kibana-highlighted-field@@@kibana-highlighted-field@gmail.com@/kibana-highlighted-field@"
    ],
    "request.route.path": [
      "@kibana-highlighted-field@/rental-submissions/:rentalSubmissionId/credit-report/payment@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1582870873996
  ]
}]
```

**Comment by chinesedfan** [comment] 2020-03-18 16:08
@newnewnet Sorry, I mean the screenshot like following if you are using Chrome. And I hope you can do some debugging to find out where triggers those two requests.

This issue will be kept open for weeks or months, but will be closed at last if no detailed evidences point to axios bugs. Thanks for understanding.

![image](https://user-images.githubusercontent.com/1736154/76981235-4486da80-6975-11ea-8fc6-6606b6affa38.png)

**Comment by newnewnet** [comment] 2020-03-20 04:37
@chinesedfan 
I can't make it had happened again but I have logging network panel for this case.

<img width="1060" alt="Screen Shot 2563-03-19 at 17 49 11" src="https://user-images.githubusercontent.com/2849568/77060491-3b484d00-6a0b-11ea-8ac1-702cafa52705.png">

I think it's the same issue with #2326

**Comment by yravid** [comment] 2020-04-22 12:38
Same thing happens for me, don't know how to reproduce exactly.
Environment:
"axios": "0.19.0"
Chromium 76.0.3809.146
Node.js | 12.4.0
macOS Mojave 10.14.6

**Comment by YitziG** [comment] 2020-05-25 11:12
This looks like a pre-flight request.

https://dev.to/p0oker/why-is-my-browser-sending-an-options-http-request-instead-of-post-5621

**Comment by KangZiRu** [comment] 2020-06-17 13:01
@YitziG in my case in #2326 , it is the exact same POST request. I confirmed it by checking the access log on the server.

**Comment by diazh** [comment] 2020-07-14 21:11
i am having the same issue. The same request is sent twice (or 4 because the preflight requests).
![Screen Shot 2020-07-14 at 2 07 44 PM](https://user-images.githubusercontent.com/12104685/87476732-be556a80-c5db-11ea-8512-9b7ab7dbd6fe.png)

**Comment by aliakseimaniuk** [comment] 2020-08-01 02:07
I have the same issue in NodeJs project. 

`"axios": "0.19.2",`

Noticed a connection between the occurrence of this error and the time of day. It appears that the issue disappears around 2 AM UTC time and appears again in 12 hours. :confused:

Maybe that helps. Looking forward to some help with this issue...

**Comment by denisbarriere** [comment] 2020-08-07 16:44
Same here. 
We have a React Native app calling our api to create some records with a POST request. 
From time to time, our api receives the exact same request twice (3 times once) in a row (a few ms time difference). 
We checked the app code and we made sure that it cannot make this POST, so when I saw this thread, I though that it could be a bug in axios.
It would be great to have some feedback on the progress of this ticket. And ideally, have some expectations on when we can get a fix live.
Thanks a lot!

**Comment by spawnrider** [comment] 2020-08-26 21:17
+1 
Same issue for me but I have three request (one prefilght OPTIONS followed by 2 GET calls) : 
![image](https://user-images.githubusercontent.com/107427/91357861-32e21280-e7f2-11ea-8c19-42902a62f82e.png)

Note that the third (the second GET) request does not contains the cookies

**Comment by chinesedfan** [comment] 2020-08-27 06:45
As mentioned in https://github.com/axios/axios/issues/2326#issuecomment-578407778, though lots of people were not satisfied with the comment, I am really glad to help. But can someone give a reproducible example?

Server logs are not trusted. A possible way is adding a breakpoint before axios sends the request(like in xhr adapter) and see who called it twice.

**Comment by spawnrider** [comment] 2020-08-27 08:56
A reproducible example online is the Directus demo site : https://demo.directus.io/
Use admin@example.com / password to connect to the admin panel. You will see 2 request to https://demo.directus.io/thumper/.
The first call stack : 
![image](https://user-images.githubusercontent.com/107427/91419418-ac5e1d00-e853-11ea-8ff8-4a1358c58589.png)

The second call stack : 
![image](https://user-images.githubusercontent.com/107427/91419518-c8fa5500-e853-11ea-81bc-67dbce360563.png)

Note that "const response = await axios.get(url);"  (line 180 in action.js) is called only once.

**Comment by chinesedfan** [comment] 2020-08-27 13:33
@spawnrider Thanks for your detailed information and screenshots. Note that call stacks(hover your mouse on the initiator column of the browser's network panel) only show the situation when just sending the request, which doesn't mean "actions.js:180" will never be called. 

- When the first request is send, "actions.js:180" has not been called yet, or at least not in the upper call stack.
- When the second request is send, it is there, which means the second request is send by inner function code of "actions.js:180".

If added a breakpoint at "actions.js:180", you will see it stops twice. One is when the page is loading. And the other is after I submitted the admin name and password. If you add a log statement after "actions.js:180", I bet it will be printed twice. In summary, nothing is wrong.

**Comment by liunan591** [comment] 2020-09-21 01:17
this issue troubled me a lot. I sent a post request but got two in server.  There art two minutes between the req received by server.

**Comment by jafar-jabr** [comment] 2020-09-26 10:52
the same issue here, it is to late now to change axios but I can promise I will never use it again in my life ^_*

**Comment by jafar-jabr** [comment] 2020-09-27 01:12
if anyone still stuck in this issue, I managed to remove axios from the project and to build fully functional module over "Fetch API"
can share it if anyone interested.

**Comment by VidurMalik** [comment] 2020-09-29 10:27
For everyone facing this problem and using Sagas / Actions, the problem might be in your sagas. Sagas might get yielded twice which will lead to the action being called once, but the web request executing twice. A potential solution is to use `takeLatest`/`takeLeading` rather than `takeEvery` in your sagas (https://redux-saga.js.org/docs/api/index.html#takeleadingpattern-saga-args)

If this doesn't work, maybe look at if your sagas are being mounted twice. @chinesedfan

**Comment by jafar-jabr** [comment] 2020-09-29 10:33
> For everyone facing this problem and using Sagas / Actions, the problem might be in your sagas. Sagas might get yielded twice which will lead to the action being called once, but the web request executing twice. A potential solution is to use `takeLatest`/`takeLeading` rather than `takeEvery` in your sagas (https://redux-saga.js.org/docs/api/index.html#takeleadingpattern-saga-args)
> 
> If this doesn't work, maybe look at if your sagas are being mounted twice. @chinesedfan

for me this was not the case, the redux debug tool shows the action dispatched only once but still the request goes twice
the only solution was to remove axios and to use fetch API.

**Comment by rafa798** [comment] 2020-11-10 20:03
same problem with version 0.20.0

**Comment by rafa798** [comment] 2020-11-11 18:03
After long hours of testing and debugging where requests were still duplicated in the SAP log, I was able to reproduce the problem locally. Everything indicates that Oh My Zsh and the nodemon left a hidden instance running with watch. Causing unwanted simultaneous firing. I can absolutely say that they were not provoked by Axios.

**Comment by christofferjjohansen** [comment] 2020-11-20 18:53
Not a solution, but adding an observation. I've been completely stumped by this issue, and only realized today that Axios was doing the double POST, which was causing a real headache in my app.

I'm using Vue, Nuxt specifically; had the POST happening in a pre-render lifecycle hook, `created`, ended up moving it to `mounted`, and the double POST disappeared, and it's working as intended now...

Like I said, not a solution, but perhaps it'll help with the troubleshooting.

**Comment by DanCanCodeIt** [comment] 2020-12-04 00:46
I'm also experiencing this issue, I've also tried logging right after to see if the function was being called twice but the log statement only appears twice while the api call is executed twice
![Screen Shot 2020-12-03 at 7 44 38 PM](https://user-images.githubusercontent.com/10767856/101107392-33800700-35a0-11eb-9f4e-f9e4ff00d042.png)

**Comment by tomellwood** [comment] 2020-12-11 16:15
I have the same issue - we are calling `axios.post` inside a Next JS API endpoint, it is only called once (it's not tied to any lifecycle hooks), yet the service it is requesting is getting duplicate requests, no more than 1 second apart.

We are only receiving the response from the second request, in our case, an error stating that the email used to register has already been used; the first request is technically successful as the user is generated in the database.

We are using axios version 0.21.0

**Comment by reflexator** [comment] 2020-12-16 10:49
I have same problem on my nginx i noticed this. I am using Nuxt (vuejs) + axios 0.21.0

```
172.20.0.8 - - [16/Dec/2020:10:40:31 +0000] "GET /api/auth/user HTTP/1.0" 200 63 "-" "axios/0.21.0"
172.20.0.7 - - [16/Dec/2020:10:40:31 +0000] "GET /api/auth/user HTTP/1.1" 200 74 "-" "axios/0.21.0"
```

So once it its as HTTP/1.0 and once as HTTP/1.1 and that was server side call

Same problem from client

```
172.20.0.1 - - [16/Dec/2020:10:46:55 +0000] "PUT /api/space/save HTTP/1.1" 500 1989 "http://localhost/prostor/pracovna-laskafe/velka-pracovna" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
172.20.0.8 - - [16/Dec/2020:10:46:55 +0000] "PUT /api/space/save HTTP/1.0" 500 1977 "http://localhost/prostor/pracovna-laskafe/velka-pracovna" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
```
Chrome on linux version 87.0.4280.88

**Comment by abhijoshi2k** [comment] 2021-02-23 11:39
I am having same issue. Multiple post requests are sent every time even if I call my function only once!

**Comment by DanCanCodeIt** [comment] 2021-02-23 15:02
@tomellwood @abhijoshi2k I ended up figuring out the problem. This isn't a problem with axios but in your react development environment the component is rendered twice if you're in StrictMode. The purpose of this to uncover unpredicted side-effects, it doesn't happen in production

**Comment by abhijoshi2k** [comment] 2021-02-23 17:04
@DanCanCodeIt Hey... that solved my issue. Thanks for quick help.

**Closed** 2021-03-23 14:51 UTC
Labels: status:more info needed

**Comment by melvin78** [comment] 2021-03-29 00:02
I managed to fix my issue. At first my axios instance was not sending duplicate requests. Then after i installed vee validate a vue plugin for handling form validations that's where the issue started. Vee validate also handles server side validation by passing the error objects to the form.  So i had to change my button to type 'submit' for the validation observer to pick up the errors object. This in turn somehow brought about the duplicating of axios requests . When i removed the validation it stopped making the duplicate requests.

**Comment by tpharaoh** [comment] 2021-06-21 18:58
> Same here.
> We have a React Native app calling our api to create some records with a POST request.
> From time to time, our api receives the exact same request twice (3 times once) in a row (a few ms time difference).
> We checked the app code and we made sure that it cannot make this POST, so when I saw this thread, I though that it could be a bug in axios.
> It would be great to have some feedback on the progress of this ticket. And ideally, have some expectations on when we can get a fix live.
> Thanks a lot!

Did you ever figure this out? I am having same issue with capacitorjs app, copy pasting identical code into HTML page works fine

**Comment by sziraqui** [comment] 2021-07-16 11:23
Same issue on axios 0.21.1. Happening on Nodejs lambda intermittently.
For example:

**Comment by AyazAI** [comment] 2021-07-20 19:22
The **problem** in my case was caused by **React development server**.
The strict mode in react caused the issue!
![image](https://user-images.githubusercontent.com/45338553/126382520-c84833ce-acf0-4861-a5e7-b7e4d56d3079.png)

I had to remove the strict mode
![image](https://user-images.githubusercontent.com/45338553/126382817-1cc7fece-e8ef-48bd-8b1c-1ae084627f83.png)

This solved the problem of sending double requests!

The strict mode checks are only run in **development mode**.
Doc: https://reactjs.org/docs/strict-mode.html

**Comment by sderrico** [comment] 2021-07-29 14:30
@AyazAI Thank you very much! Solved our issues.

**Comment by Xairoo** [comment] 2021-09-24 16:20
For me it was a missing `event.preventDefault()` on a `onClick()` handler.

The code above `axios()` didn't run twice, so I haven't checked `event.preventDefault()` directly. Give it a try! ;-)

**Comment by acf77** [comment] 2022-01-22 19:17
> The **problem** in my case was caused by **React development server**. The strict mode in react caused the issue! ![image](https://user-images.githubusercontent.com/45338553/126382520-c84833ce-acf0-4861-a5e7-b7e4d56d3079.png)
> 
> I had to remove the strict mode ![image](https://user-images.githubusercontent.com/45338553/126382817-1cc7fece-e8ef-48bd-8b1c-1ae084627f83.png)
> 
> This solved the problem of sending double requests!
> 
> The strict mode checks are only run in **development mode**. Doc: https://reactjs.org/docs/strict-mode.html

THAT WAS MY PROBLEM EXACTLY! Thank you so much!

**Comment by chitoxl777** [comment] 2022-04-30 19:33
> The **problem** in my case was caused by **React development server**. The strict mode in react caused the issue! ![image](https://user-images.githubusercontent.com/45338553/126382520-c84833ce-acf0-4861-a5e7-b7e4d56d3079.png)
> 
> I had to remove the strict mode ![image](https://user-images.githubusercontent.com/45338553/126382817-1cc7fece-e8ef-48bd-8b1c-1ae084627f83.png)
> 
> This solved the problem of sending double requests!
> 
> The strict mode checks are only run in **development mode**. Doc: https://reactjs.org/docs/strict-mode.html

THIS WAS MY PROBLEM AS WELL!!

**Comment by pedrosimarrosantamaria** [comment] 2022-05-18 10:51
> The **problem** in my case was caused by **React development server**. The strict mode in react caused the issue! ![image](https://user-images.githubusercontent.com/45338553/126382520-c84833ce-acf0-4861-a5e7-b7e4d56d3079.png)
> 
> I had to remove the strict mode ![image](https://user-images.githubusercontent.com/45338553/126382817-1cc7fece-e8ef-48bd-8b1c-1ae084627f83.png)
> 
> This solved the problem of sending double requests!
> 
> The strict mode checks are only run in **development mode**. Doc: https://reactjs.org/docs/strict-mode.html

THANKS <3

**Comment by jokerclay** [comment] 2022-09-22 15:31
I have a similar case, I am bonding a `a` tag  with a function that use `axios.delete` to sent a delete request to the server
and when I click the `a` tag, it won't delete the item until the second times, then I change the `a` tag to a `button` tag, and it worked, I guess there is some side effect when I click the `a` tag, this is a case, hope it can be helpful

**Comment by Naveenkms** [comment] 2022-10-26 08:44
> For me it was a missing `event.preventDefault()` on a `onClick()` handler.
> 
> The code above `axios()` didn't run twice, so I haven't checked `event.preventDefault()` directly. Give it a try! ;-)



> For me it was a missing `event.preventDefault()` on a `onClick()` handler.
> 
> The code above `axios()` didn't run twice, so I haven't checked `event.preventDefault()` directly. Give it a try! ;-)

**Comment by kcprabase** [comment] 2022-12-12 05:01
> @tomellwood @abhijoshi2k I ended up figuring out the problem. This isn't a problem with axios but in your react development environment the component is rendered twice if you're in StrictMode. The purpose of this to uncover unpredicted side-effects, it doesn't happen in production

I would have never thought of it. Thanks. It did the trick.

**Comment by SethCram** [comment] 2023-04-11 03:39
For me, this was caused by unintentionally re-registering an axios interceptor middleware on every re-render. So, the same interceptor would be called multiple times. 

The interceptor was held in a React Functional Component because it had to access the user context api. I solved this through scrapping the use of an interceptor entirely and reusing a function to retrieve the axios headers for individual api calls.

**Comment by Mike-J-W** [comment] 2024-02-19 06:56
> For me, this was caused by unintentionally re-registering an axios interceptor middleware on every re-render. So, the same interceptor would be called multiple times.
> 
> The interceptor was held in a React Functional Component because it had to access the user context api. I solved this through scrapping the use of an interceptor entirely and reusing a function to retrieve the axios headers for individual api calls.

This was my issue as well - and your solution worked for me too. Thank you!
