### ISSUE TITLE
Secret options in config

### ISSUE THREAD

**Issue by clar-cmp** [axios/axios#2719] opened 2020-02-06 21:14 UTC
**Describe the issue**
Right now, axios helpfully copies its config into all error messages. Unfortunately, if there is sensitive data in this config (e.g. API keys) this is also logged. There should be an easily accessible option to help prevent this, because most people won't bother to put in the effort for security. This use case is intended for node.js users, where consumers of the logs aren't necessarily as privileged as those running the library.

**Example Code**
Code snippet to illustrate your question

```js
// in externalapi.js
const instance = axios.create({
    baseUrl: 'https://something.com',
    headers: {
        'X-Api-Key': 'secretstring',
    }
});

// in useapi.js
instance.get('/somethnig'); // oops, typo; throws 404 error
```

**Expected behavior, if applicable**
Right now, the thrown error includes the API key in the logs, which is not ideal. Instead, there should be a way to include the API key in the config without including it in the errors. We might also want to to remove it from the response config as well in case downstream users want to copy-paste that in their own errors.

**Environment:**
 - Axios Version 0.19.2
 - OS: N/A
 - Additional Library Versions: Node 12

**Additional context/Screenshots**
It might be nice to be able to encode additional data and headers in the config which aren't included in the config returned by response. Perhaps this could be done via separate `secretData` or `secretHeaders` fields which are treated separately.

**Comment by chinesedfan** [comment] 2020-02-10 12:01
Duplicate of #2602. If possible, I'd like accept a PR to emphasize it in document.

**Closed** 2020-02-10 12:01 UTC
