### ISSUE TITLE
Question about isValidXss.js

### ISSUE THREAD

**Issue by JinTak** [axios/axios#2663] opened 2020-01-14 19:16 UTC
**Describe the issue**
I was curious as to why the regex looks for 'on' in the get parameters. I had a parameter called 'onSiteTestComplete=false' but I had to change it to 'isOnSiteTestComplete=false'. Thanks!

https://github.com/axios/axios/blob/master/lib/helpers/isValidXss.js

**Environment:**
 - Axios Version 0.19.0
 - OS: OSX 10.15.2 Catlina
 - Browser Chrome Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by felipecwb** [comment] 2020-01-14 21:06
I got this error too.  
My URL: `http://localhost:3001/api/management/users?onlyActive=true`

The query string part `onlyActive=` was caught by regex.  

**Environment:**
- Axios Version: 0.19.1
- Firefox Developer Edition 73.0b4 (64-bit)

**Comment by 315101** [comment] 2020-01-14 22:56
My 2 cents:
axios version: ^0.19.1
- xssRegex.test("https://some.url.com?only=false&foo=false") returns true
- xssRegex.test("https://some.url.com?only=true&foo=false") returns false

**Comment by CammyMurrie** [comment] 2020-01-15 15:10
see this bug guys https://github.com/axios/axios/issues/2646

**Comment by skflo60** [comment] 2020-01-20 09:11
Hello !
Same problem here with "?onlyActive"
![image](https://user-images.githubusercontent.com/10008577/72713353-2ebf8980-3b6d-11ea-9ef9-b36dd3956957.png)

**Comment by chinesedfan** [comment] 2020-01-20 13:18
Duplicate of #2646.

**Closed by chinesedfan** 2020-01-20 13:18 UTC
