### ISSUE TITLE
withCredentials in cross domain request dosn't work

### ISSUE THREAD

**Issue by PawelJ-PL** [axios/axios#1661] opened 2018-07-08 20:41 UTC
#### Context

- axios version: *v0.18.0, v.0.17.0*
- Environment: *e.g.: Firefox 52.9.0 Linux, Chrome 67.0.3396.99 Linux*

#### Problem
It looks, that Axios is unable to send cookie in request to another domain. I've two app: 

* frontend on local computer, port 8080
* backend on local computer, port 9000

In frontend I've defined backend as: `http://127.0.0.1:9000`. 

In my JavaScript code I have service:

```
import axios from 'axios';
axios.defaults.withCredentials = true;
axios.get('127.0.0.1:9000/api/v1/inventory/system', {withCredentials: true});
```

When I open my frontend as: `http://127.0.0.1:8080` (frontend and backend are in the same domain 127.0.0.1, only port is different), everything is ok, cookie is present in request headers.

But when I open my frontend as `http://localhost:8080` cookie is missing in request headers. It's GET request, and there no preflight request, so I would expect, that cookie will be added to request.

I've attached screenshoots

#### Correct request with cookie (the same domain):
![correct](https://user-images.githubusercontent.com/20472898/42423729-b14f8026-82ff-11e8-8c03-eb27cc1a1250.png)

#### Incorrect request without cookie (cross domain):
![incorrect](https://user-images.githubusercontent.com/20472898/42423747-da6d116c-82ff-11e8-88e0-ef976f5ac27c.png)

**Comment by kunvarsingh** [comment] 2018-07-13 12:39
I want to solve this issue,
But how can i run this projects, I have clone it and make new branch for issue, and install npm.

and i am trying to rum "npm start" then it is not running.
can anyone help me for run this project???

**Comment by kunvarsingh** [comment] 2018-07-13 12:54
By design, domain names must have at least two dots; otherwise the browser will consider them invalid. (See reference on http://curl.haxx.se/rfc/cookie_spec.html)

When working on localhost, the cookie domain must be omitted entirely. Just setting it to "" or NULL or FALSE instead of "localhost" is not enough.

For PHP, see comments on http://php.net/manual/en/function.setcookie.php#73107.

If working with the Java Servlet API, don't call the cookie.setDomain("...") method at all.
**OR check with**
https://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain

**Comment by PawelJ-PL** [comment] 2018-07-13 20:22
It isn't problem with loaclhost domain. For test purposes I've added entry `127.0.0.1       localhost myapp1.api myapp2.api` in my `/etc/hosts` and problem is the same:

### Working example:
* backend defined as myapp1.api:9000
* frontend as myapp1.api:8080 (in browser)

##### Result:
cookie sent in first request

### Not working example:
* backend definied as myapp1.api:9000
* frontend as myapp2.api:8080 (in browser)

##### Result:
cookie not sent


In spare time I will try to prepare and publish example project

**Comment by peter527** [comment] 2018-07-25 02:40
I met the same problem,

**Comment by liunian1004** [comment] 2018-08-18 23:44
i get same problems. i set all steps. but not send cookie

**Comment by SeanBurt** [comment] 2018-08-27 10:47
i also have this problem, who can help us?

**Comment by pthorsley** [comment] 2018-08-27 19:07
For now to get past this error, I am using a POST, such a waste of time to try to figure out why Axios does not support just simple HTTP methods, driving me nuts, might have to change libs.

**Comment by ijse** [comment] 2018-09-30 09:50
I have the same problems.

**Comment by sevaTechoPark** [comment] 2018-10-07 13:42
same issue

**Comment by nevermo2013** [comment] 2018-10-17 09:38
我遇到了同样的问题,跨域请求无论怎么设置axios.defaults.withCredentials = true 都无法发送cookie

**Comment by liyun-li** [comment] 2018-11-14 18:55
Little late to the party but I've been bashing my head against the wall on this.

I think the issue is not caused by `axios` but by your browser(s). _By default, your browser refuses to send cookies to a "remote" location._

I resolved my issue by using `127.0.0.1` as my host instead of `localhost`. For anyone who's experiencing this problem, I recommend making sure that your domain name isn't `localhost` but at least `127.0.0.1`.

Hope this helps.

**Comment by PawelJ-PL** [comment] 2018-12-02 21:31
I've found solution. The problem was GET request (there is no preflight for this method). The workaround is adding non standard header for request (for example X-Version), so preflight request will be performed.
During debugging I've found one more problem: Ghostery Firefox extension is adding some extra headers to each request (so CORS is failing), so I removed this extension.

**Comment by rhyspang** [comment] 2019-02-14 02:50
same issue

**Comment by pthorsley** [comment] 2019-02-14 02:56
@rhyspang  just use a post so much easier and gets you moving quickly, using .net core and works great.

however have not tried @PawelJ-PL  suggested, that might be worth some investigation.

**Comment by DillionApple** [comment] 2019-02-14 03:01
I solved the problem. It turns out to be the wrong configuration in my Django backend. Since Django 2.1+ has introduced some new security features, I need to add these two lines in my `settings.py`: 

```
SESSION_COOKIE_SAMESITE = None
CRSF_COOKIE_SAMESITE = None
```

**Comment by pthorsley** [comment] 2019-02-14 03:04
don't use django but might take a look after I am doing sucking up elixir. :)

**Comment by snowdream** [comment] 2019-03-31 03:37
any solution?

**Comment by sergeycw** [comment] 2019-04-18 13:57
same issue :(

**Comment by suguoyao** [comment] 2019-05-13 09:42
i have this issue too 😿

**Comment by Poyoman39** [comment] 2019-05-14 14:19
@liyun-li solved my problem with an express server.

Problem may come from "sameSite" cookie option. More details here :
https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-4.1.1

**Comment by Ddper** [comment] 2019-05-29 12:22
https://github.com/nuysoft/Mock/issues/300

mockjs aways set withCredentials false

**Comment by vonKingsley** [comment] 2019-06-21 22:48
Hopefully this helps someone else out there.  If the cookie has the secure flag set, the browser won't send it out again over http, I was using webpack devServer proxy, and I had to set the https: true option on for devServer in my config.  Once I had an https server, i was able to send back the cookie. It didn't matter that it was a self signed cert.
`devServer: {
    https: true,
    proxy: {
      '/api': {
        target: 'https://remoteserver.com'
       }
     }
}`

**Comment by obilearns2rock** [comment] 2019-10-18 15:03
If you're using express server, try the cors npm package with the following config

```
const corsConfig = {
  origin: true,
  credentials: true,
};

app.use(cors(corsConfig));
app.options('*', cors(corsConfig));
```

Then in your frontend code using axios set the following
`axios.defaults.withCredentials = true;`

**Comment by sun-kingcity** [comment] 2019-11-08 04:49
> I solved the problem. It turns out to be the wrong configuration in my Django backend. Since Django 2.1+ has introduced some new security features, I need to add these two lines in my `settings.py`:
> 
> ```
> SESSION_COOKIE_SAMESITE = None
> CRSF_COOKIE_SAMESITE = None
> ```

Problem fixed by 3 parts
On frontend
1) axios.defaults.withCredentials = true;

On Backend
1) settings.py
SESSION_COOKIE_SAMESITE = None
CRSF_COOKIE_SAMESITE = None

2) Set-Cookie on response (e.g. login):  response.set_cookie

**Comment by chinesedfan** [comment] 2019-12-07 08:25
> During debugging I've found one more problem: Ghostery Firefox extension is adding some extra headers to each request (so CORS is failing), so I removed this extension.

Closed due to it is solved. https://github.com/axios/axios/issues/1661#issuecomment-443544090

**Closed by chinesedfan** 2019-12-07 08:25 UTC

**Comment by BrookZhao** [comment] 2019-12-17 04:00
thank you




| |
赵山伟
邮箱：15900929407@163.com
|

签名由 网易邮箱大师 定制

On 12/07/2019 16:25, Xianming Zhong wrote:

During debugging I've found one more problem: Ghostery Firefox extension is adding some extra headers to each request (so CORS is failing), so I removed this extension.

Closed due to it is solved. #1661 (comment)

**Comment by contracamilo** [comment] 2020-01-13 15:20
> I have the same problems. Use `fetch()` that works.

fetch() was my solution.

**Comment by micookie** [comment] 2020-03-13 19:53
> [nuysoft/Mock#300](https://github.com/nuysoft/Mock/issues/300)
> 
> mockjs aways set withCredentials false

same resloved

**Comment by timmaloshtan** [comment] 2020-04-12 09:29
Guys, to whoever is still stuck on this in 2020.

Axios only ever looks at the `withCredentials` setting, if environment you are executing it in resembles a browser environment.
You can check their [source code](https://github.com/axios/axios/blob/5e0fb5fc998d7f9f5a897363977b42f4fa047238/lib/adapters/xhr.js#L105)

Say your are making your requests from Jest, then make sure that you have `testEnvironment: "jsdom"`  in `jest.config`

**Comment by muhalitas** [comment] 2020-04-20 18:27
> I solved the problem. It turns out to be the wrong configuration in my Django backend. Since Django 2.1+ has introduced some new security features, I need to add these two lines in my `settings.py`:
> 
> ```
> SESSION_COOKIE_SAMESITE = None
> CRSF_COOKIE_SAMESITE = None
> ```

Typo alarm!

CSRF_COOKIE_SAMESITE = None

**Comment by hypn0t1z** [comment] 2020-05-02 16:34
> If you're using express server, try the cors npm package with the following config
> 
> ```
> const corsConfig = {
>   origin: true,
>   credentials: true,
> };
> 
> app.use(cors(corsConfig));
> app.options('*', cors(corsConfig));
> ```
> 
> Then in your frontend code using axios set the following
> `axios.defaults.withCredentials = true;`

WOW, it's work for me <3. Thanks
