### ISSUE TITLE
HTTPS over HTTP Proxy Fails

### ISSUE THREAD

**Issue by sidharthv96** [axios/axios#3384] opened 2020-11-05 04:28 UTC
#### Describe the bug
HTTPS over HTTP Proxy Fails with 500 handshakefailed on mcafee proxy.
`mcafee initialize server context:handshakefailed:server state 1:state 9:Application response 500 handshakefailed`
With HTTP_PROXY and HTTPS_PROXY set, curl works but axios.get fails.

#### To Reproduce

```ts
import axios from 'axios';

(async () => {
  try {
    console.log(await axios.get('https://github.com/'));
  } catch (e) {
    console.log(e);
  }
})();

```

#### Expected behavior
Request should succeed.

#### Environment
 - Axios Version [0.21.0]
 - Node.js Version [v12.18.3]
 - OS: [OSX 10.15.7]

#### Additional context/Screenshots
N/A

#### Current workaround
Install `global-agent`, remove the HTTP_PROXY env vars and set GLOBAL_AGENT_HTTP_PROXY.

Add `import 'global-agent/bootstrap';` to index.

**Comment by gary-archer** [comment] 2020-11-09 17:38
If you are using a non browser (NodeJS) process you should find that the below approach is needed. Most non browser processes (including C# and Java HTTP Clients) do not work off the HTTP_PROXY / HTTPS_PROXY environment variables and require an equivalent setting.

```
const options = {
  proxy: {
    host: 'http://127.0.0.1',
    port: 8888,
  },
};
await axios.get('https://github.com/', options);
```

It is common to control whether a process uses a proxy via a configuration file, as in [this JSON file of mine](https://github.com/gary-archer/authguidance.websample1/blob/master/api/api.config.json).

**Comment by sidharthv96** [comment] 2020-11-12 04:23
What  I observed was that axios does recognise the environment variables, but the way it connects to the proxy causes issues.

I did try setting the proxy manually, but even that didn't work and had the same issue.

The problem seems to be connecting to an HTTPS endpoint via an HTTP proxy.

Global agent uses the right way to setup the proxy and works, but axios' default mechanism fails.

**Comment by MichaelKoch** [comment] 2020-12-08 17:54
Can confirm that issue using a http proxy for https connections 
-> export http_proxy=http://xyz:3330
-> export https_proxy=http://xyz:3330
-> curl https://www.google.com ->   ok 
-> axios failed

Environment docker ubuntu 18.04

**Comment by gary-archer** [comment] 2020-12-08 20:31
I noticed that my code above was a little out of date (I was using an old Axios version), so I've updated it - here is [some code of mine](https://github.com/gary-archer/authguidance.basicloadtest/blob/master/src/api/apiClient.ts) that calls a Web API via a proxy when required. It uses version 0.21 currently and if behaviour changes I will update it.

**Comment by sidharthv96** [comment] 2020-12-09 06:38
@gary-archer the code shared seems to be setting a proxy agent manually.

The bug is in the axios NodeJS implementation of reading the ENV vars automatically.
Ideally it should work without having to manually specify a proxyAgent. (And it does, for http -> http cases)

The issue, as @MichaelKoch has shown is in case of http -> https.

so a simple `axios.get('https://google.com')` will fail if the HTTPS_PROXY env var is set to an `http://`  endpoint.

**Comment by Niek** [comment] 2020-12-22 11:48
This seems to be an issue since a long time. There's even a "fixed" NPM package for this: https://www.npmjs.com/package/axios-https-proxy-fix
Commit: https://github.com/Sitronik/axios/commit/36c1f46cb3e39b620bf81b5ba4069f1ddd02d4ce

**Comment by saamalik** [comment] 2021-01-23 18:29
Hi @Niek - any ideas why the _axios-https-proxy-fix_ fix aren't merged into axios? I'm sure a lot of people are running into this.

**Comment by linchen1987** [comment] 2021-09-02 11:02
set proxy to false can fix:

`const axios = require('axios').create({ proxy: false })`

**Comment by jasonsaayman** [comment] 2022-06-12 17:34
Hi 👋 

Please could you retry with the latest version and open a new issue should this error still be relevant?

Thanks

**Closed by jasonsaayman** 2022-06-12 17:34 UTC

**Comment by ericrange** [comment] 2022-06-17 09:09
this still does not work!

**Comment by amiral-jion** [comment] 2022-06-30 18:42
I'm having the same issue

**Comment by pemontto** [comment] 2022-07-01 12:51
Relates to open issue `Proxy support does not work properly with CONNECT on https requests` #4531

**Comment by ericrange** [comment] 2022-07-01 13:58
because there is no real answer for that... what really works (for complex proxy scenarios)

```
const axios = require('axios');
const axiosHttpsProxy = require('helpers/axios.js');
axios.interceptors.request.use(axiosHttpsProxy);
```

and the content of the "helper"

```
var url = require('url')

var httpsProxyAgent = require('https-proxy-agent')

function proxy (config) {
  /* istanbul ignore if */
  if (config.socketPath != null) return config

  var parsed = url.parse(config.url)
  var protocol = parsed.protocol
  /* istanbul ignore if */
  if (protocol !== 'https:') return config

  var proxy = config.proxy
  /* istanbul ignore if */
  if (proxy === false) return config

  var proxyOptions
  if (proxy != null) {
    proxyOptions = {
      hostname: proxy.host,
      port: proxy.port
    }
    if (proxy.auth != null) {
      proxyOptions.auth = proxy.auth.username + ':' + proxy.auth.password
    }
  } else {
    var proxyUrl = process.env['HTTPS_PROXY'] || process.env['https_proxy']
    /* istanbul ignore if */
    if (!proxyUrl) return config

    parsed = url.parse(proxyUrl)
    proxyOptions = {
      hostname: parsed.hostname,
      port: parsed.port
    }
    if (parsed.auth) {
      proxyOptions.auth = parsed.auth
    }
  }

  // HTTPS request must use tunnel proxy protocol
  config.httpsAgent = httpsProxyAgent(proxyOptions)

  // Disable direct proxy protocol in axios http adapter
  config.proxy = false

  return config
}

module.exports = proxy
```

**Comment by ericrange** [comment] 2022-07-01 14:00
why cant axios just implement this? proxy shit is the most common shit out there... and proxy autodetect is NOT THAT HARD....

**Comment by meteorlxy** [comment] 2022-08-02 05:38
@jasonsaayman Still have this issue with 1.0.0-alpha.1

**Comment by pcandido** [comment] 2022-08-26 19:58
I combined two approaches, and it worked to me

`npm i npm i tunnel-agent`

```
axios
  .create({proxy:false})
  .get('https://xxxx', {
    headers:{authorization:'Bearer xxxx'}, 
    httpsAgent: TunnelAgent.httpsOverHttp({ proxy: url.parse("http://proxy:3128")})
  })
```

**Comment by ericrange** [comment] 2022-08-27 07:30
the problem is, that the proxy url is passed as variable into a docker container (99% of the cases)

axios itself wont look for "https_proxy" and another problem is case-sensity.

thats why you need
```
process.env['HTTPS_PROXY'] || process.env['https_proxy']
```
