### ISSUE TITLE
Arrays in a request's config are merged positionally with the default config

### ISSUE THREAD

**Issue by lagr** [axios/axios#2614] opened 2019-12-20 11:53 UTC
Hello everyone,

first things first – thanks to all of you for devoting your valuable time to this project! I have not found a corresponding issue for this case and I am not sure whether it is a bug or a feature. If it is a feature, please read this post as a suggestion for a more explicit documentation of the behavior.

**Describe the bug**
When I specify some request (or response) transformations in the default config and then use an empty array (or one with less transformation functions than the default has) in a request's transformation config, some of the default transformations are still being applied.

**To Reproduce**
```js
client = Axios.create({
  transformRequest: [
    deepKebabTransform,
    JSON.stringify
  ]
})

// ...

// a) 
client.put(url, data, { transformRequest: [] })

// b)
client.put(url, data, { transformRequest: [data => data] })
```

In both cases, `JSON.stringify` is still run. In case a), both functions from the default config are applied.

**Expected behavior**
I would expect the default config entries for `transformRequest` and `transformResponse` (if not all array entries) to be either replaced completely by or merged with their counterparts in a request's config.

**Environment:**
 - Axios Version 0.18.0
 - OS: OSX 10.15.2
 - Browser: tested in Chrome 79.0.3945.88, Safari 13.0.4

**Additional context**
Regarding the `merge` function in `utils` I came to the assumption, that the arrays would likely be treated as objects and thus their entries are effectively overridden positionally.

**Comment by chinesedfan** [comment] 2019-12-20 15:26
Duplicate of #2567. Sorry for the inconvenient.

**Closed by chinesedfan** 2019-12-20 15:26 UTC

**Comment by lagr** [comment] 2019-12-20 15:42
Thank you for the hint, I must have missed that there is a similar symptomatic there. 
I believe though, that `deepMerge` is not involved in the bug at hand as it is only applied to the config keys `'headers'`, `'auth'` and `'proxy'`.

**Comment by chinesedfan** [comment] 2019-12-20 15:56
@lagr Oops, I noticed that you are using 0.18. The old codes have similar bug.

Maybe you can try 0.19, but be careful with other new changes/bugs. 😪 

```js
function merge(/* obj1, obj2, obj3, ... */) {
  var result = {};
  function assignValue(val, key) {
    if (typeof result[key] === 'object' && typeof val === 'object') {
      result[key] = merge(result[key], val);
    } else {
      result[key] = val;
    }
  }

  for (var i = 0, l = arguments.length; i < l; i++) {
    forEach(arguments[i], assignValue);
  }
  return result;
}

//
merge([1,2],[3])
// {0: 3, 1: 2}
```

**Comment by lagr** [comment] 2019-12-20 16:05
I think the bug/behavior is consistent across versions 0.18.0-0.19.0 (and present in both `merge`/ `deepMerge`).

```js
(typeof result[key] === 'object' && typeof val === 'object')
```
yields `true` for arrays, so I think adding `&& !toString.call(result[key])` should enable the desired behavior.

If I find the time during the festive days, I could try to submit a pull request to address the issue.

**Comment by chinesedfan** [comment] 2019-12-20 16:09
@lagr Thanks for your attention. And you can check #2568 first.

Old maintainers have been inactive for a long time. We need time to cleaning issues and PRs.
