### ISSUE TITLE
Sending cookie with fetch is working but not with axios

### ISSUE THREAD

**Issue by suguoyao** [axios/axios#2149] opened 2019-05-14 01:55 UTC
First, here is my cookie in my chrome.
```
Name               Value      Domain          Path      Expires    HTTP    Secure
JSESSIONID          xx        x.sss.com         /          N/A      true     true
```

This is my axios code. I didn't see the cookie on my server log. 
```javascript
const request = axios.create({
  baseURL: 'https://x.sss.com',
  headers: {
    'Content-Type': 'application/json'
  },
  withCredentials: true,
  timeout: 300000,
  transformRequest: [function (data) {
    return JSON.stringify(data)
  }]
})

request({
  url: '/api/post',
  method: 'post',
  data: [1,2,3]
})
```

I can get my cookie with fetch
```javascript
fetch('https://x.sss.com/api/post', {
  'method': 'POST',
  'body': JSON.stringify([1,2,3]),
  'credentials': 'include',
  'mode': 'cors',
  'headers': {
    'accept': 'application/json, text/plain, */*', 'content-type': 'application/json'
  }
})
```

This is the http response headers.
```http
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: x-requested-with,content-type
Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE
Access-Control-Allow-Origin: http://127.0.0.1:1288
Access-Control-Max-Age: 3600
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Date: Tue, 14 May 2019 01:49:14 GMT
Server: nginx/1.12.2
Transfer-Encoding: chunked
```
I'm very confused.😢 Could you help me please ?

**Environment:**
 - Axios Version: 0.18.0
 - OS: OSX 10.14.3
 - Browser: Chrome
 - Browser Version: 74.0.3729.131
 - Additional Library Versions: Vue 2.6.10

**Comment by evle** [comment] 2019-05-18 02:06
Hello there, 
I tried the 2 cases you described and axios works well, 
It seems like the something wrong with your CORS header, please check it and close the issue thank you.

**Comment by suguoyao** [comment] 2019-05-20 01:12
@evle  
Hi, Are you sure you are using the https protocol?

**Comment by ninbert** [comment] 2019-05-20 21:15
I had the same issue, used proxy instead....

**Comment by alexcomo95** [comment] 2019-05-22 11:32
I'm having the same issue. Fetch works while axios doesn't. So i'm guessing the issue is on axios' side.
Setting withCredentials to true doesn't help.

**Comment by ninbert** [comment] 2019-05-22 11:51
Ter Deleting the endpoint from the axios request. f.e --- axios.post("https://endpoint.com/getInfoFromDB" ,{bodyObject}).then etc...... 
to ---- axios.post("/getInfoFromDB. {bodyObject}).then etc.....

go to package.json and add the following line in the object no matter where:

"proxy":"https://endpoint.com",

Hope this will help.

**Comment by alexcomo95** [comment] 2019-05-22 12:18
Still not working so far..

**Comment by suguoyao** [comment] 2020-07-21 07:09
Is this the same situation as mine? 😖
https://github.com/axios/axios/issues/2149

**Comment by timbakkum** [comment] 2020-08-27 11:04
I have a similar issue. I'm adding a cookie by using the `withCredentials` option, but when adding a `transformRequest` option to set an additional header, the cookie will not show up on the request any more.

**Comment by Lucien-X** [comment] 2021-06-03 07:45
> I have a similar issue. I'm adding a cookie by using the `withCredentials` option, but when adding a `transformRequest` option to set an additional header, the cookie will not show up on the request any more.

same issue here.
axios seems to drop all the credentials , 
while I modify the request header with the 'headers' option

```javascript
const axiosInstance = axios.create({
    withCredentials: true,/
    headers: {
      'x-xsrf-token':  someCsrfToken,
    }
  });
```
without headers option:

![image](https://user-images.githubusercontent.com/20273998/120607038-612c0700-c482-11eb-9687-387e7205c238.png)

with headers option:

![image](https://user-images.githubusercontent.com/20273998/120607300-a2bcb200-c482-11eb-8f6b-a6b46187afa5.png)

**Comment by js-writer** [comment] 2022-08-20 22:38
I can confirm, still not working. With withCredentials flag it is adding Cookie: jwt= but the value is empty...

**Comment by js-writer** [comment] 2022-08-21 08:15
Try to add withCredentials: true to the request which create cookie in your server.
For example when cookie is created when user is try to login, than add flag withCredentials to login request.

**Comment by jpodpro** [comment] 2022-10-17 21:06
i'm having this problem also. `axios` fails to send the cookie to a slightly different domain even though it is the same cookie domain.

source url: xyz.com:3000
requested url: xyz.com:777
cookie domain: .xyz.com

**Comment by jbcuningham** [comment] 2023-10-12 17:42
> i'm having this problem also. `axios` fails to send the cookie to a slightly different domain even though it is the same cookie domain.
> 
> source domain: `xyz.com:3000` requested domain: `xyz.com:777` cookie domain: `.xyz.com`

I have just been gifted "ownership" of an app at my company and I'm having this exact problem when I try running the app on my local machine. It seems to run fine on the test and production servers, so I'm thinking there's just a setting that I need to get it running on my local. I've tried the withCredentials in all the places suggested and still no luck.

**Comment by yayapao** [comment] 2023-11-22 03:17
Caught same issues, when i make a same request, fetch cookies worked, axios cookies is not or sometimes no cookies. This happens in my development with webpack proxy and i've tried `withCredentials` in all the places or setting `cookieDomainRewrite` and still no luck.

**Comment by yayapao** [comment] 2023-11-22 06:51
> Caught same issues, when i make a same request, fetch cookies worked, axios cookies is not or sometimes no cookies. This happens in my development with webpack proxy and i've tried `withCredentials` in all the places or setting `cookieDomainRewrite` and still no luck.

i've solved the problem by changing axios baseURL from `https:something/api` to `api`

**Comment by iampapagray** [comment] 2023-11-23 07:40
> > Caught same issues, when i make a same request, fetch cookies worked, axios cookies is not or sometimes no cookies. This happens in my development with webpack proxy and i've tried `withCredentials` in all the places or setting `cookieDomainRewrite` and still no luck.
> 
> i've solved the problem by changing axios baseURL from `https:something/api` to `/api`

@yayapao Can you share your axios config? i'm having the same issue.

**Comment by yayapao** [comment] 2023-11-24 08:41
> > > Caught same issues, when i make a same request, fetch cookies worked, axios cookies is not or sometimes no cookies. This happens in my development with webpack proxy and i've tried `withCredentials` in all the places or setting `cookieDomainRewrite` and still no luck.
> > 
> > 
> > i've solved the problem by changing axios baseURL from `https:something/api` to `/api`
> 
> @yayapao Can you share your axios config? i'm having the same issue.

Yes, webpack proxy config like below:

```ts
export default {
  dev: {
    '/api/': {
      target: 'https://xxx.xxx.com/',
      changeOrigin: true,
      pathRewrite: { '^': '' },
      withCredentials: true,
    },
  },
}
```

Here is the bad case:

```ts
const service = Axios.create({
  baseURL:https://xxx.xxx.com/api,
  timeout: 5 * 60000,
  headers: { 'X-Requested-With': 'XMLHttpRequest' },
  withCredentials: true,
})
```

After i change `https://xxx.xxx.com/api` to `/api`, everything works fine. By the way, change axios to fetch can also works out.

**Comment by jasonsaayman** [comment] 2024-09-26 17:39
closing if this is still a problem please open a new issue

**Closed by jasonsaayman** 2024-09-26 17:39 UTC
