### ISSUE TITLE
Reponse Interceptor : unable to handle an expired refresh_token (401)

### ISSUE THREAD

**Issue by ligne13** [axios/axios#1266] opened 2018-01-04 17:44 UTC
Hi,  

I have the following interceptor on my axios reponse :

```
window.axios.interceptors.response.use(
                response => {
                    return response;
                },
                error => {
                    let errorResponse = error.response;
                    if (errorResponse.status === 401 && errorResponse.config && !errorResponse.config.__isRetryRequest) {
                        return this._getAuthToken()
                            .then(response => {
                                this.setToken(response.data.access_token, response.data.refresh_token);
                                errorResponse.config.__isRetryRequest = true;
                                errorResponse.config.headers['Authorization'] = 'Bearer ' + response.data.access_token;
                                return window.axios(errorResponse.config);
                            }).catch(error => {
                                return Promise.reject(error);
                            });
                    }
                    return Promise.reject(error);
                }
            );
```

The _getAuthToken method is :
```
_getAuthToken() {
            if (!this.authTokenRequest) {
                this.authTokenRequest = window.axios.post('/api/refresh_token', {
                    'refresh_token': localStorage.getItem('refresh_token')
                });
                this.authTokenRequest.then(response => {
                    this.authTokenRequest = null;
                }).catch(error => {
                    this.authTokenRequest = null;
                });
            }

            return this.authTokenRequest;
        }
```

The code is heavily inspired by https://github.com/axios/axios/issues/266#issuecomment-335420598.

Summary : when the user makes a call to the API and if his access_token has expired (a 401 code is returned by the API) the app calls the /api/refresh_token endpoint to get a new access_token. If the refresh_token is still valid when making this call, everything works fine : I get a new access_token and a new refresh_token and the initial API call requested by the user is made again and returned correctly.

The problem occurs when the refresh_token has also expired.  
In that case, the call to /api/refresh_token returns a 401 and nothing happens. I tried several things but I'm unable to detect that in order to redirect the user to the login page of the app.  
I found that in that case the if (!this.authTokenRequest) statement inside the _getAuthToken method returns a pending Promise that is never resolved. I don't understand why this is a Promise. In my opinion it should be null...

I'm a newbie with Promises so I may be missing something !
Thanks for any help !

**Comment by ligne13** [comment] 2018-01-04 19:00
I may have found a way much simpler to handle this : use axios.interceptors.response.eject() to disable the interceptor when I call the /api/refresh_token endpoint, and re-enable it after.

The code :

```
createAxiosResponseInterceptor() {
            this.axiosResponseInterceptor = window.axios.interceptors.response.use(
                response => {
                    return response;
                },
                error => {
                    let errorResponse = error.response;
                    if (errorResponse.status === 401) {
                        window.axios.interceptors.response.eject(this.axiosResponseInterceptor);
                        return window.axios.post('/api/refresh_token', {
                            'refresh_token': this._getToken('refresh_token')
                        }).then(response => {
                            this.setToken(response.data.access_token, response.data.refresh_token);
                            errorResponse.config.headers['Authorization'] = 'Bearer ' + response.data.access_token;
                            this.createAxiosResponseInterceptor();
                            return window.axios(errorResponse.config);
                        }).catch(error => {
                            this.destroyToken();
                            this.createAxiosResponseInterceptor();
                            this.router.push('/login');
                            return Promise.reject(error);
                        });
                    }
                    return Promise.reject(error);
                }
            );
        },
```

Does it looks good or bad ? Any advice or comment appreciated.

**Comment by smingam** [comment] 2018-01-16 11:06
Hi guys!
Can you check your package-lock.json or verify by any other way if your axios is using follow-redirect 1.3.0 ?
```    "axios": {
      "version": "0.16.2",
      "resolved": "https://registry.npmjs.org/axios/-/axios-0.16.2.tgz",
      "integrity": "sha1-uk+S8XFn37q0CYN4VFS5rBScPG0=",
      "requires": {
        "follow-redirects": "1.2.6",
        "is-buffer": "1.1.6"
      }
```
I've got a very similar error. It has something to do with 401 handling on POST or PUT (still works with GET) that doesn't get a proper response encapsulation with axios.
My very simple code 
```js
HTTP.interceptors.response.use(function (response) {
    return response.data
}, function (error) { 
    // error.response is undefined in case of POST and 401 response
    // only get a Network Error 
    if (error.response.status === 401) { 
        store.dispatch('logout')
    }
    return Promise.reject(error.response)
})
```
Reverting to follow-redirect 1.2.6 works.

**Comment by NanoDev777** [comment] 2018-01-16 13:35
@smingam  What version of axios did you use when it did not work ?, I use the 0.16.2 axios and it does not work for me, what do you currently use?

**Comment by ligne13** [comment] 2018-01-16 14:02
Hi, 
I would recommend my solution given in https://github.com/axios/axios/issues/1266#issuecomment-355368279 with the interceptor eject method. 
It works !

**Comment by NanoDev777** [comment] 2018-01-16 14:10
@ligne13 Is it possible to adapt your solution to my reference code? I have something different, I would also like to know what version of axios you use

**Comment by NanoDev777** [comment] 2018-01-16 19:46
@ligne13  I'm sorry, I already format the code to make it more understandable

**Comment by ligne13** [comment] 2018-01-16 21:36
Hi @NanoDev777,
"my" solution is totally doable with your code. The idea is to disable the response interceptor (with the eject method) as soon as you get a 401 (access token expired). You momentarily disable the interceptor in order to be able to make a request to your refresh token endpoint. Once you get your new token, you re-enable the interceptor. So the process is like that :
- put all your code inside a method so you can re-call it later (createAxiosResponseInterceptor() { ... })
- you create the interceptor and store it into a property (this.axiosResponseInterceptor = ...) : now you have a reference to the interceptor.
- you disable it when you get a 401 by calling the eject method on the property you created (window.axios.interceptors.response.eject(this.axiosResponseInterceptor)
- you do your request to get a new token
- once done, you recreate the interceptor by calling the method which wraps the whole stuff : this.createAxiosResponseInterceptor()
It's hard to explain code by writing... Hope it will help.

**Comment by smingam** [comment] 2018-01-17 14:45
@NanoDev777 : with axios 0.16.2 and follow-redirect 1.2.6 it works, with axios  0.16.2 and follow-redirect 1.3.0 it doesn't.

@ligne13 : the problem with your solution, from what I understand, is that it won't works as well, because the bug is somewhere between axios and follow-redirect.
```js
let errorResponse = error.response;
if (errorResponse.status === 401)` 
```
That code will fail because error.response is undefined, in my case it's a Network Error with some text, 
kinda like here : https://github.com/axios/axios/issues/383

**Comment by ligne13** [comment] 2018-01-17 14:53
@smingam well, for me it worked.

**Comment by smingam** [comment] 2018-01-17 15:00
I can confirm that it works with axios 0.17.1 and follow-redirect 1.3.0
My problem was with axios 0.16.2 and follow-redirect 1.3.0, don't know how I ended up with that combination.

**Comment by NanoDev777** [comment] 2018-01-18 03:11
@smingam  How can I know the version of follow-redirect ?, I'm still trying code and nothing works for me.

**Comment by picbenoit** [comment] 2018-01-18 16:21
Hello everybody,

I have the same problem when my token expired, I have an error.response undifined whereas my status code is 401 (I can see it on firefox network window).
I use axios 0.17.1 that ask for dependencies :
"follow-redirects": "^1.2.5",

follow-redirects version is 1.2.6.

Is anyone know how can I have the couple axios 0.17.1 and follow-redirects 1.3 ? Is it will work with both versions ?

Ben

**Comment by picbenoit** [comment] 2018-01-18 16:33
I update my follow-redirects to 1.3 by adding it on my composer.json project file.
But still have error.response undifined when my token is expired although my api server return a 401 status error...
I don't really want to check it with error.message === "Network Error" because can also be something like my app can not access to Internet.

Ben.

**Comment by rajalive28** [comment] 2018-01-23 18:11
https://gist.github.com/rajalive28/0219df4f9fe34308b793eb2babf0bb4f

Tried the above but no success ... any help would be appreciated

**Comment by robaxelsen** [comment] 2018-01-23 18:39
Closing as @ligne13 reported this as solved.

**Closed by robaxelsen** 2018-01-23 18:39 UTC

**Comment by qiangzi7723** [comment] 2019-05-19 16:35
I have the same trouble. This is my solution:

```
       async login() {
            this.$api.post('/admin/login', {
                name: this.username,
                password: this.password
            }).then((data) => {
                this.$cache.save('jwt', data.token)
                this.$cache.save('role', data.role)
                this.token = data.token
                this.$message('登录成功')
                this.config()
            }).catch(() => {
                this.$message('登录失败')
            })
        },
        config() {
            // 配置jwt
            this.$api.axios.interceptors.request.use((config) => {
                const token = this.$cache.load('jwt')
                if (token) config.headers.Authorization = `Bearer ${token}`
                return config
            })
            this.$router.push('/home')
        }

```

**Comment by idrislab** [comment] 2019-10-31 00:26
I use something like this:

```javascript
http.interceptors.response.use(response => response, async (error) => {
  if (error.response.status !== 401) {
    return Promise.reject(error);
  }

  const auth = store.getters['user/auth'];

  if (!auth) {
    router.replace({ name: 'login' });
  }

  try {
    const { data } = await authService.refreshToken({
      refresh_token: auth.refresh_token,
    });

    store.commit(`user/${MUTATION_SET_AUTH}`, data);

    const requestConfig = error.config;

    requestConfig.headers.Authorization = `Bearer ${data.access_token}`;

    await axios.request(requestConfig);
  } catch (exception) {
    store.commit(`user/${MUTATION_SET_AUTH}`, null);
    router.replace({ name: 'login' });
  }
});
```
