### ISSUE TITLE
cdn unpkg TypeError: axios is not a function

### ISSUE THREAD

**Issue by angel-yi** [axios/axios#5049] opened 2022-10-07 03:38 UTC
#### Describe the bug
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

#### To Reproduce
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
```

#### Environment
 - Axios Version [e.g. 0.18.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by akiva10b** [comment] 2022-10-07 04:03
I also started experiencing this, had to downgrade to get axios back

**Comment by peterw** [comment] 2022-10-07 04:26
Use Axios 1.0

**Comment by jenyang2** [comment] 2022-10-07 05:24
why is cdn changed?

**Comment by philBrown** [comment] 2022-10-07 05:33
> Why is cdn changed?

Because without specifying a version, it uses the latest which at this time is v1.1.0

**Comment by jenyang2** [comment] 2022-10-07 05:38
> 


However, in version 1.1, the existing axios calling code gave an error.
-> TypeError: axios is not a function

**Comment by jenyang2** [comment] 2022-10-07 05:39
> > Why is cdn changed?
> 
> Because without specifying a version, it uses the latest which at this time is v1.1.0

However, in version 1.1, the existing axios calling code gave an error.
-> TypeError: axios is not a function

**Comment by philBrown** [comment] 2022-10-07 05:40
Yep and Axios v1.0.0 and later is broken at this time. This is a dupe of #5038

**Comment by jasonsaayman** [comment] 2022-10-07 09:12
Update to v1.1.1 this should slove the issue

**Closed by jasonsaayman** 2022-10-07 09:12 UTC
