### ISSUE TITLE
Long string error ..

### ISSUE THREAD

**Issue by Mhmetengineer** [axios/axios#4904] opened 2022-08-05 17:26 UTC
jBody["fcm"]='dyxzsyL7Q5i-enk-KgHErl:APA91bHHqr262tGyPNH5GZiXW4NwgAKsGLztzrw4CtIXgC-PgPnxXrRaJslmkva8H9A1R3kpKWOgCizVJV6_wH3i5hfkxmmjQNf8fAAhzBy-GTL8erhydwpHEqiEuqUCfka6ZKR66btn';
      const res = await axios.post(xxx, jBody, headers: {   'Content-Type': 'application/json'});
   

There is no problem when I try it in postman, but when I try it in react native, I get an error. ( return 500 )

**Comment by WillianAgostini** [comment] 2022-08-06 02:33
Hi @Mhmetengineer 
What's the error showing?
Is it showing all the string "fcm" on the server?

**Comment by Mhmetengineer** [comment] 2022-08-06 15:02
hi @WillianAgostini  , 
There is no problem when u shrink the string. I have problem with the length of the string. When I try from the phone, it returns 500 from the server. No problem with postman.

**Comment by WillianAgostini** [comment] 2022-08-06 15:48
> hi @WillianAgostini  , 
> There is no problem when u shrink the string. I have problem with the length of the string. When I try from the phone, it returns 500 from the server. No problem with postman.

What content type are you using? On mobile and on Postman?

**Comment by Mhmetengineer** [comment] 2022-08-07 09:45
same type.. @WillianAgostini  ,
application/json

**Comment by WillianAgostini** [comment] 2022-08-07 16:38
I can't reproduce the error.
Can you reproduce it on a minimal example?

**Comment by cyberGHostJs** [comment] 2022-08-09 06:04
hi please i'm interested in this task. and i'd like to be assigned to fixing it

**Closed** 2024-09-28 18:18 UTC
