### ISSUE TITLE
axios (used in react-native) does not automatically follow redirect

### ISSUE THREAD

**Issue by GermanMontejo** [axios/axios#1350] opened 2018-02-09 09:38 UTC
Hello, I need your help. As stated here:

https://github.com/axios/axios/issues/239

axios is supposed to automatically follow a redirection. But whenever I access my API through a post request, it gives me this response and axios is not able to do anything other than timeout.

> Redirecting...</title>\n<h1>Redirecting...</h1>\n<p>You should be redirected automatically to target URL:

Note: I've omitted part of the response and just posted here what's relevant. In my signin API it accepts a POST request and whenever it detects that the user_id entered is not yet found in the db, it will redirect the request to the registration API. Note this works on curl and postman. I've tested it there. But when we're using axios to do a post request, it always gives me the timeout error followed by the message above.

The status returned is 307 as what I've indicated in the API in my flask web app for redirection.

**Comment by GermanMontejo** [comment] 2018-02-09 10:02
These were the headers I used when making the request from the react-native app I'm working on:

headers: {
               'content-type': 'application/x-www-form-urlencoded',
               'X-Requested-With': 'XMLHttpRequest',
               "Access-Control-Allow-Origin": "*"
           }

**Comment by GermanMontejo** [comment] 2018-02-12 02:32
@mzabriskie @nickuraltsev please check this.

**Comment by GermanMontejo** [comment] 2018-02-12 06:24
@mzabriskie @nickuraltsev Hi! I've noticed that the redirection works if the status code on my render_template() function in my flask app is 302. If I change it to 307, redirection does not work. I needed 307 to make sure that the method is not updated to GET. 307 maintains the original request method, which in my case is POST. I've added a workaround in my web app but if you could fix this issue, then it would be great.

**Comment by emilyemorehouse** [comment] 2018-02-16 23:03
Hi @GermanMontejo! 

I believe this is a misunderstanding of the difference between 302 and 307 requests. 

[RFC7231 6.4.7](https://tools.ietf.org/html/rfc7231#section-6.4.7) states: 
>The 307 (Temporary Redirect) status code indicates that the target
   resource resides temporarily under a different URI and the user agent
   MUST NOT change the request method if it performs an automatic
   redirection to that URI.  Since the redirection can change over time,
   the client ought to continue using the original effective request URI
   for future requests.

Essentially what this means is that if you have a POST that redirects via a 302, the redirect is done with a GET.
If you have a POST that redirects via a 307, the redirect is done with a POST. You can actually see where this happens in one of Axios' dependencies `follow-redirects` [here](https://github.com/olalonde/follow-redirects/blob/master/index.js#L184). 

Perhaps this is messing up your redirect call?

Nonetheless, this doesn't seem to be an issue with Axios, so I'm closing this out. If you still need help, feel free to comment again and I'll see if I can help!

**Closed by emilyemorehouse** 2018-02-16 23:03 UTC

**Comment by GermanMontejo** [comment] 2018-02-17 00:30
Hi @emilyemorehouse,

I know 307 does not change the http method as I stated above:

"I needed 307 to make sure that the method is not updated to GET. 307 maintains the original request method, which in my case is POST."

What I don't understand is why the redirection works when the status code is 302. 307 is still a redirection, and when I use that status code on my flask web app for the response, my mobile app (with axios) timeout. It can successfully follow if tge status code is 302, though.

**Comment by GermanMontejo** [comment] 2018-02-17 00:31
But not with 307, which is supposed to work as it says axios can follow redirects with 307

**Comment by GermanMontejo** [comment] 2018-02-17 00:32
*What I don't understand is why the redirection works when the status code is 302 but not with 307, which is supposed to work.

**Comment by emilyemorehouse** [comment] 2018-02-17 01:34
Hm. Without being able to debug your API, I'm not sure I'll be of any help. I tested redirects with a 307 and it still follows them.

Here's an example, adapted from one of our tests (it creates a server that redirects `/one` to `/to`):
```
var axios = require('axios')
var http = require('http');
var url = require('url');

http.createServer(function (req, res) {
  var parsed = url.parse(req.url);
  
  req.on('data', function (data) {
    console.log(`DATA: ${data}`);
  });

  if (parsed.pathname === '/one') {
    console.log(`TYPE: ${req.method}, URL: ${req.url}`);
    res.setHeader('Location', '/two');
    res.statusCode = 307;
    res.end();
  } else {
    console.log(`REDIRECTED -- TYPE: ${req.method}, URL: ${req.url}`);
    res.end('test response');
  }
}).listen(4444, function () {
  axios.post('http://localhost:4444/one', {'foo': 'bar'});
});
```

Here's a [link to the running code ](https://runkit.com/embed/y7tt53ebuoou) as well, which outputs:

```
"TYPE: POST, URL: /one"
"DATA: {\"foo\":\"bar\"}"
"REDIRECTED -- TYPE: POST, URL: /two"
"DATA: {\"foo\":\"bar\"}"
```

**Comment by GermanMontejo** [comment] 2018-02-17 01:46
Hi,

Thanks for testing it. Can you try by sending a form (POST) request? My
flask API accepts the request in a form, not in a raw json body. I've
tested my flask API with Postman and Curl, and it redirects properly so I'm
sure I don't need to modify my flask API. Also, please set the header to
form-url-encoded or multipart/form-data in your axios object.

Warm regards,
German

**Comment by RezaBaiat** [comment] 2019-06-30 14:38
i can confirm that axios does not follow the 307 when method is POST , but it does when it is GET

**Comment by RezaBaiat** [comment] 2019-06-30 14:56
tested every thing and im sure of it now , for now im using a working around . this is the method which doesnt work :

axios.request({url:url,headers:headers,body:body,method:'POST'});

**Comment by GermanMontejo** [comment] 2019-07-01 06:13
@RezaBaiat  You might wanna ask @emilyemorehouse to re-open this issue. I've already forgotten my work-around for it so I won't be of much help here.

**Comment by RezaBaiat** [comment] 2019-07-01 12:06
yes thanks alot , work alot for this is pretty simple , just catch the 307
status and manually recall the api
