### ISSUE TITLE
Memory leak with responseType: 'text' and 'Content-Type': 'text/html'

### ISSUE THREAD

**Issue by mehdibeldji** [axios/axios#1997] opened 2019-02-12 09:42 UTC
**Describe the bug**
Hello,
I don't know if it's a V8 issue or Axios issue. When I send a get request to get HTML content on a page, a memory leak appear : the html is never stored in garbage collector...

**To Reproduce**
I create a simple server.js with express and axios client to test outside of my project:

```js
const express = require('express');
const axios = require('axios');

const server = express();
const axiosClient = axios.create();

server.get('/axios-test-html', async (req, res) => {
  try {
    const data = await axiosClient.get('https://github.com/winstonjs/winston-daily-rotate-file/pull/185', {
      responseType: 'text',
    });
    const htmlResponse = data.data;
    return res.send({
      sourceCode: htmlResponse,
    });
  } catch (error) {
    console.log(error);
    return res.status(500).send(error);
  }
})

server.listen('4242', () => {
  console.log('server listen at 4242');
});

process.on('SIGINT', () => {
  console.log('server signint');
  process.exit(0);
});
```
<img width="1439" alt="capture d ecran 2019-02-12 a 10 38 29" src="https://user-images.githubusercontent.com/5889926/52625933-654b4980-2eb2-11e9-9fb7-8ef1bbd0a3a6.png">

I've running my server.js with `node --inspect` and create heap snapshots at the beginning and after 3/4 calls.

**Expected behavior**
Normally a memory leak does not appear with json content, but with html yes.

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: 10.14
 - Browser: Chrome
 - Browser: Version 71.0.3578.98
 - Node.JS : 10.14.1

**Comment by mehdibeldji** [comment] 2019-02-12 13:37
I've tested the same code with (got)[https://github.com/sindresorhus/got] and no memory leak...

**Comment by Tarabyte** [comment] 2019-02-14 09:31
This seems to be V8 issue caused by `JSON.parse`. I've filed a [bugreport](https://bugs.chromium.org/p/v8/issues/detail?id=8841).

The simplest way to reproduce the issue w/o axios
```javascript
setInterval(() => {
  const hugeNonJSONString = '*'.repeat(10 ** 6)

  try {
    JSON.parse(hugeNonJSONString)
  } catch (ignored) {
    // swallow
  }
}, 1000)
```

**Comment by mehdibeldji** [comment] 2019-02-14 10:08
Thanks a lot for your PR 👍

**Comment by Tarabyte** [comment] 2019-02-14 10:14
@mehdibeldji  Before PR is merged (if it ever would be :rofl: ) you could pass a custom response transformer that does nothing. This should eliminate the leak.

```javascript
const axiosClient = axios.create({
  transformResponse: function(data, headers) {
    // use JSON.parse only if headers['content-type'].includes('application/json')
    // or always return data if you don't plan to use this client to fetch json
    return data 
  }
});
```

**Comment by jasonsaayman** [comment] 2020-06-25 17:58
Closing in favour of #2783

**Closed by jasonsaayman** 2020-06-25 17:58 UTC
Labels: status:possible bug
