### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'create')

### ISSUE THREAD

**Issue by sephentos** [axios/axios#5175] opened 2022-10-24 15:43 UTC
### Describe the bug

```
import axios, { AxiosInstance, AxiosResponse } from 'axios'

...

this.instance = axios.create( {
                        ^
```

`TypeError: Cannot read properties of undefined (reading 'create')`

### Axios Version

1.1.3

### Node.js Version

19

**Comment by rgripper** [comment] 2022-10-28 09:27
Duplicate of #5038

**Comment by RaresAil** [comment] 2022-11-04 10:26
The issue still persists in `1.1.3` and that ticket was closed

**Comment by jasonsaayman** [comment] 2022-11-10 19:19
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Closed by jasonsaayman** 2022-11-10 19:19 UTC
