### ISSUE TITLE
ERR_CONNECTION_REFUSED vs ERR_INTERNET_DISCONNECTED determination

### ISSUE THREAD

**Issue by MarcFletcher** [axios/axios#1296] opened 2018-01-17 12:26 UTC
#### Summary

Should Axios be differentiating between the following:

 - A request which fails because the client has no network connection at
   the point when the request was made - (ERR_CONNECTION_REFUSED).
 - A request which fails because network connectivity is lost *after* the 
   request was made but *before* the response was received - (ERR_INTERNET_DISCONNECTED).

It seems that in both cases, all we get back is a rather unhelpful "Network Error" message...

The documentation (https://github.com/axios/axios#handling-errors) suggests that in the latter case, `error.request` should be populated, but I have been unable to replicate *any* scenario where `error.request` exists. In both of the above scenarios, I get an error object looking like this:

    {
      config: { ... },
      response: undefined,
      message: "Network Error",
      stack: "Error: Network Error at createError (http://localhost:3000/static/js/bundle.js:1636:15) at XMLHttpRequest.handleError (http://localhost:3000/static/js/bundle.js:1170:14)"
    }

#### Context

- axios version: *v0.17.1*

**Comment by Axnyff** [comment] 2018-01-18 10:07
Are you using axios in node or in the browser?

If I do, with no internet,
    axios.get('https://404/foo').catch(error => console.log(error.request));
in the browser I dot get an XMLHttpRequest.

It looks like I also got the correct thing in node with the same code.

Do you have any code to reproduce the issue?

**Comment by AndyNeale** [comment] 2018-03-01 10:13
To try and simulate this problem, I wrote a basic Node API:

```
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  setTimeout(() => {
    res.send('Finished');
  }, 10000);
});

app.listen(8282, function () {
  console.log('Node API listening on port 8282...')
});
```

and a simple Node client:

```
var express = require('express');
var app = express();
var axios = require('axios');

app.get('/', function (req, res) {
  const config = {
    url: 'http://localhost:8282',
    method: 'GET',
    timeout: 30000,
  };
  axios(config)
  .then((response) => {
    res.status(200).send(response.data);
  })
  .catch((error) => {
    res.status(500).send({
      code: error.code,
      config: error.config,
      response: error.response,
    });
  });
});

app.listen(8181, function () {
  console.log('Node client listening on port 8181...')
});
```

Launch both applications from the command line, browse to http://localhost:8181, then terminate the API application to simulate the connection being dropped, and the client receives the following error details:

```
{
  "code": "ECONNRESET",
  "config": {
    "transformRequest": {},
    "transformResponse": {},
    "timeout": 30000,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "User-Agent": "axios/0.18.0"
    },
    "method": "get",
    "url":"http://localhost:8282"
  }
}
```

So perhaps the answer is to look at the error code - ECONNRESET in this case. (Note that if a request times out, you get an ECONNABORTED error code back.)

**Comment by lmanzurv** [comment] 2018-03-15 15:02
Is this issue fixed? I keep having an unusable app after this error happens. It's a react app that's hooked to a rails app with react-on-rails. After this happens, the only way of getting the app working again is to refresh.

**Comment by Kulak** [comment] 2018-09-04 18:57
I have a case when backend service is not running at all and I have observed that I got an error:

    Failed to load resource: net::ERR_CONNECTION_REFUSED

line 178 in axios/lib/adapters/xhr.js:

    // Send the request
    request.send(requestData);

The side effect is bad, because neither .then no .catch is executed.

My axios version is:

    axios@0.18.0

**Comment by ndegealbert** [comment] 2019-09-09 17:40
> Is this issue fixed? I keep having an unusable app after this error happens. It's a react app that's hooked to a rails app with react-on-rails. After this happens, the only way of getting the app working again is to refresh.

still having the same problem any solution please

**Comment by luatnd** [comment] 2020-01-22 06:53
+1.

I need to distingue those two cases:

POST https://xxx.com/sendMessage net::ERR_NAME_NOT_RESOLVED
POST https://xxx.com/sendMessage net::ERR_INTERNET_DISCONNECTED

As I checked. error return by the catch block is the same in both cases above.

**Comment by sayhicoelho** [comment] 2020-04-11 21:50
Any updates?

**Comment by spamshaker** [comment] 2020-11-15 09:22
> +1.
> 
> I need to distingue those two cases:
> 
> POST https://xxx.com/sendMessage net::ERR_NAME_NOT_RESOLVED
> POST https://xxx.com/sendMessage net::ERR_INTERNET_DISCONNECTED
> 
> As I checked. error return by the catch block is the same in both cases above.
> 
> Minimal Reproduction steps:
> Open browser console, run:
> 
> ```
> axios({
>     method: 'GET',
>     url: `https://api.URL_NOT_EXIST.org/sendMessage`,
>   }).then(console.log).catch(function(error) {
>   console.dir(error);
>   console.log('error.status: ', error.status)
>   if (!error.status) {
>     // network error
>     console.log('network error')
>   }
> });
> ```
> 
> Disconnect the Internet, run above request again


I am also looking for the resolution and according to this post https://bugs.chromium.org/p/chromium/issues/detail?id=118096#c5 it won't be so easy.
The only idea which is coming to my mind is to request external DNS service before the final fetch happen
this may resolve those two following two accordingly
when DNS responded then from response we may recognize if name is fine or not
```net::ERR_NAME_NOT_RESOLVED```
otherwise when DNS timeout then highly likely 
```net::ERR_INTERNET_DISCONNECTED```
though this will require to trust CORS for public dns or we may need to setup backend endpoint just to check that thing

**Comment by jasonsaayman** [comment] 2021-05-14 20:08
> I am also looking for the resolution and according to this post https://bugs.chromium.org/p/chromium/issues/detail?id=118096#c5 it won't be so easy.

Closing this as it does not seem it will be possible to fix it if you look at this link.

**Closed by jasonsaayman** 2021-05-14 20:08 UTC
Labels: type:question
