### ISSUE TITLE
Axios response memory leak

### ISSUE THREAD

**Issue by Dirk94** [axios/axios#3457] opened 2020-12-05 14:41 UTC
#### Describe the bug
I think that Axios has a serious memory leak. The Axios responses are never removed from memory.

#### To Reproduce
Create a new node project. 

```
npm i axios && touch index.js
```

```js
const axios = require('axios');

// Perform 1 request per second.
setInterval(async () => {
	const response = await axios.get("https://wikipedia.com");
	console.log("Done getting response!");
}, 1000)
```

#### Expected behavior
I would expect this program to not keep a reference to every response. But unfortunately, it does.

#### Environment
 - Axios Version 0.21.0
 - Node.js Version 14.12.0
 - OSX 10.15.6

#### Additional context/Screenshots
The Chrome memory profiler shows that the Wikipedia responses are stored in memory. 

<img width="1483" alt="Screen Shot 2020-12-05 at 3 38 31 PM" src="https://user-images.githubusercontent.com/2823049/101245837-f0dd3c80-370f-11eb-90c3-b2be1c7222a6.png">

**Comment by splitice** [comment] 2021-02-27 05:19
I have been investigating a similar issue. I'm currently testing using a more robust script of:

```
const axios = require('axios'),
      Q = require('q-lite')

let request = 0
async function doRequest(url){
	request++
	try {
		await axios.get(url);
	} catch(ex){
		console.log(`${url}: Failed to get response ${request}`)
		return
	}
	console.log(`${url}: Done getting response ${request}`);
}

async function main(url){
	// Perform requests with a 1 second delay
	while(true){
		await doRequest(url)
		await Q.delay(1000)
	}
}

main("https://wikipedia.com")
main("https://google.com")
main("https://microsoft.com")
main("https://gmail.com")
```

Ran with: `node --max_old_space_size=8 axios-leak.js`

**Comment by splitice** [comment] 2021-02-27 08:32
I have been investigating a similar issue. I'm currently testing using a more robust script of:

```
const axios = require('axios'),
      Q = require('q-lite')

let request = 0
async function doRequest(url){
	request++
	try {
		await axios.get(url);
	} catch(ex){
		console.log(`${url}: Failed to get response ${request}`)
		return
	}
	console.log(`${url}: Done getting response ${request}`);
}

async function main(url){
	// Perform requests with a 1 second delay
	while(true){
		await doRequest(url)
		await Q.delay(1000)
	}
}

main("https://wikipedia.com")
main("https://google.com")
main("https://microsoft.com")
main("https://gmail.com")
```

Ran with: `node --max_old_space_size=8 axios-leak.js`

Your script is prone to memory build-up due to it not waiting on the response before starting the next. The number of requests in flight can increase if the request time increases.

I wasnt able to replicate any issue with my script, I tested up to 22,422 requests.

**Comment by splitice** [comment] 2021-02-27 10:03
The following however does lead to an eventual crash.

```
const axios = require('axios'),
      Q = require('q-lite')

let request = 0
async function doRequest(url){
	request++
	try {
		await axios.get(url, {timeout: 500});
	} catch(ex){
		//console.log(`${url}: Failed to get response ${request}`)
		return
	}
	//console.log(`${url}: Done getting response ${request}`);
}

async function main(url){
	// Perform requests with a 1 second delay
	while(true){
		await doRequest(url)
		await Q.delay(100)
	}
}

main("https://httpstat.us/200?sleep=5000")
main("https://httpstat.us/200?sleep=6000")
main("https://httpstat.us/200?sleep=7000")
main("https://httpstat.us/200?sleep=8000")
main("https://httpstat.us/200?sleep=5000")
main("https://httpstat.us/200?sleep=6000")
main("https://httpstat.us/200?sleep=7000")
main("https://httpstat.us/200?sleep=8000")
main("https://httpstat.us/200?sleep=5000")
main("https://httpstat.us/200?sleep=6000")
main("https://httpstat.us/200?sleep=7000")
main("https://httpstat.us/200?sleep=8000")
main("https://httpstat.us/200?sleep=5000")
main("https://httpstat.us/200?sleep=6000")
main("https://httpstat.us/200?sleep=7000")
main("https://httpstat.us/200?sleep=8000")
main("https://httpstat.us/200?sleep=5000")
main("https://httpstat.us/200?sleep=6000")
main("https://httpstat.us/200?sleep=7000")
main("https://httpstat.us/200?sleep=8000")
main("https://httpstat.us/200?sleep=5000")
main("https://httpstat.us/200?sleep=6000")
main("https://httpstat.us/200?sleep=7000")
main("https://httpstat.us/200?sleep=8000")
main("https://httpstat.us/200?sleep=5000")
main("https://httpstat.us/200?sleep=6000")
main("https://httpstat.us/200?sleep=7000")
main("https://httpstat.us/200?sleep=8000")
main("https://httpstat.us/200?sleep=5000")
main("https://httpstat.us/200?sleep=6000")
main("https://httpstat.us/200?sleep=7000")
main("https://httpstat.us/200?sleep=8000")
main("https://httpstat.us/200?sleep=5000")
main("https://httpstat.us/200?sleep=6000")
main("https://httpstat.us/200?sleep=7000")
main("https://httpstat.us/200?sleep=8000")
```

Ran with: `node --max_old_space_size=5 --trace_gc --gc_interval=5000 axios-leak.js`

So it appears the leak is tied to timeouts or failed requests.

**Comment by splitice** [comment] 2021-02-27 11:18
Further troubleshooting narrows it down to `follow-redirects` as memory leak slower / non existant with `maxRedirects:0`.

**Comment by RubenVerborgh** [comment] 2021-02-27 14:41
follow-redirects v1.13.3 fixes this

**Comment by jasonsaayman** [comment] 2021-03-23 14:49
This has been fixed with #3694

**Closed by jasonsaayman** 2021-03-23 14:49 UTC
Labels: status:possible bug

**Comment by DjovDev** [comment] 2021-06-10 13:16
Hey you guys sure this is fixed?

I thought I'd give Axios a try instead of the actual HTTP client of Nodejs, yet I see my ram jump skyhigh when retrieving 5mb responses from a backend server using a post command:

This is the function I built.

`
const axios = require('axios').default;
const parseString = require('xml2js').parseString;

// post xml function
function xmlPost(body,host,port,callback) {   
    axios({
        method:'post',
        url: 'http://' + host + ':' + port,
        data: body,
        headers:  {
            'Content-Type': 'application/xml',
            'Content-Length': body.length
        }
    }).then(response => {
        parseString(response.data, function (err, result) {
            if (err) {
                callback('Tried to parse the following XML: ' + buffer + ' - ' + err)
            } else {
                callback(null,result)
                result = null
            }
        })
    })
}`

When doing something 'similar' in the http library, my ram stays levelled.

`
const http = require('http')
const parseString = require('xml2js').parseString;

// post xml function
function xmlPost(body,host,port,callback) {   

    let postRequest = {
        host: host,
        port: port,
        method: "POST",
        headers: {
            'Content-Type': 'application/xml;charset=UTF-8',
        }
    }

    let req = http.request( postRequest, function( res )    {
        let requestError
        let buffer = "";
        res.on( "data", function( data ) { buffer = buffer + data; } );
        res.on( "end", function( data ) { 
            if (requestError) {
                callback(requestError)
            } else {
                parseString(buffer, function (err, result) {
                    if (err) {
                        callback('Tried to parse the following XML: ' + buffer + ' - ' + err)
                    } else {
                        callback(null,result)
                    }
                })
            }

        } );
    
    });
    
    req.on('error', function(e) {
        requestError = 'Got error while posting XML: ' + e.message
        console.log('Got error while posting XML: ' + e.message)
    });
    
    req.write( body );
    req.end(); 
}`

**Comment by Samrat-Saha-Sammy** [comment] 2021-08-03 16:06
Seems like the bugFix [#3694](https://github.com/axios/axios/pull/3694) is merged to master on March 23, but still we got no version release after that.

**Comment by shaoxp** [comment] 2022-08-11 09:38
i used 0.27.2 version to test @Dirk94's original test, it still have memory leakage.

**Comment by shaoxp** [comment] 2022-08-12 04:18
I test all versions following ![image](https://user-images.githubusercontent.com/1912990/184284043-2ca3da55-957c-4e8e-8f6b-2f66e8496332.png).

 the results show that memory usage will always increase, so there seems still memory leakage. can someone reopen this issue? do we have any quick workaround?

and I used the chrome inspect to investigate the reason. and find the main leakage resource is a string. 
![image](https://user-images.githubusercontent.com/1912990/184284188-61156945-c543-45f8-a4eb-4fa1eda7249f.png)

**Comment by lptai** [comment] 2022-08-15 06:11
I just upgraded to `axios@0.27.2` still have memory leak. My use case is retrying on 429 status - rate limit exceeded error. The application is keeping restarted with memory leak error with axios retry

**Comment by vzkhrv** [comment] 2022-10-04 13:16
> I test all versions following ![image](https://user-images.githubusercontent.com/1912990/184284043-2ca3da55-957c-4e8e-8f6b-2f66e8496332.png).

Can't reproduce on my own. Do u still have this leakage?

**Comment by mongoose666** [comment] 2024-10-09 03:06
It still exists in Cancel.js as of 1.6.2 from the look of things.
