### ISSUE TITLE
Getting unreadable data in response from external API

### ISSUE THREAD

**Issue by PovedaAqui** [axios/axios#5315] opened 2022-11-27 12:57 UTC
### Describe the issue

I've deployed successfully my backend to a serverless cloud service, but, unlike the local version, in the hosted app I'm getting an unreadable response rather than JSON as you can see below.

`"�\b�T�r�8���r�i�.~����FH�!�\t�01C���\\��*Y�T��e�{�=��{��NgY?_�]��Aӝ�.yQw?k/?��۬=�|���<��#�dd3)��6���l2\nJ]X��������e��^�?\r|�H`

### Example Code

```js
app.get('/api/get-my-books', (req, res) => {

    const address = req.query.address;
    const chain = "polygon";

    const options = {
        method: 'GET',
        url: `https://api.nftport.xyz/v0/accounts/${address}`,
        params: {
          chain: chain,
          include: 'metadata',
          contract_address: process.env.REACT_APP_DROP_CONTRACT
        },
        headers: {
          'Content-Type': 'application/json',
          Authorization: process.env.REACT_APP_NFT_PORT
        }
      };
      
      axios.request(options)
      .then((response) => {
        res.json(response.data);
      })
      .catch((error) => {
        console.error(error);
      });
});
```

### Expected behavior

A readable JSON response is expected.

### Axios Version

1.2.0

### Browser

Chrome

### Node.js Version

14.19.1

### Additional Library Versions

```bash
"cors": "^2.8.5",
"dotenv": "^16.0.3",
"express": "^4.18.2"
```

**Comment by jankanty** [comment] 2022-11-28 09:50
Happens also on node v16 and v18

**Comment by jens-maus** [comment] 2022-11-28 12:00
The same happens for two of my node projects (node-unifi and node-ical) since dependabot suggests upgrade to 1.2.0. As soon as I upgrade, axios returns binary data. Pinning the axios version in package.json to 1.1.3 immediately restores this misbehaviour. Any suggestion on how to fix that or can the axios devs please investigate quickly because in case even `^1.1.3` is used in the `package.json` npm of course tries to install the latest 1.2.0 now and results into not working projects anymore...

**Comment by sayem314** [comment] 2022-11-28 12:45
Same here. No issue with v1.1.3

**Comment by Nykloon** [comment] 2022-11-28 12:54
Using v1.2.0-alpha.1 fixed this issue for me.

**Comment by kunkey** [comment] 2022-11-28 12:55
> Same here. No issue with v1.1.3

I just got scolded by my boss for all the api returning undefined, and luckily I found some cool solutions here!

**Comment by PovedaAqui** [comment] 2022-11-28 19:58
Thank you. Downgrading to 1.1.3 fixed the issue.

**Comment by rcbevans** [comment] 2022-11-28 20:47
Just bumped to 1.2 and seeing the same issue.  Guess I'm going to have to roll back.

**Comment by n1ckcodes** [comment] 2022-11-28 21:09
I was able to get this resolved by adding 

`    "Accept-Encoding": "application/json",` 

in my headers while using 1.2

**Comment by philBrown** [comment] 2022-11-29 02:51
Duplicate of #5298 / #5296. Does nobody check for existing issues before creating new ones?

**Closed** 2022-12-01 14:22 UTC

**Comment by Usama-Akbar** [comment] 2023-03-07 07:55
Its not an axios version error. It'll fix by adding :
      headers: {
        'Accept-Encoding': 'application/json',
}
works for me
