### ISSUE TITLE
415 Unsupported media type for DELETE

### ISSUE THREAD

**Issue by ZwapKillrath** [axios/axios#3248] opened 2020-09-01 19:50 UTC
#### Describe the bug

In version 0.19.1 my API worked for DELETE's against my .NET Core 3.1 API, but after upgrading to 0.20.0 this broke.

#### To Reproduce
My ts code:

```
  public static async postDelete(payload: IAssetDeletionData): Promise<IAssetDeletionResult> {
    const response = await (await getApi(this.apiBase)).delete('', {
      data: payload
    });
    return response.data as IAssetDeletionResult;
  }

```

Works with Axios 0.19.1 but not in 0.20.0.
I get a 
_{type: "https://tools.ietf.org/html/rfc7231#section-6.5.13", title: "Unsupported Media Type",…}
status: 415
title: "Unsupported Media Type"
traceId: "|3670a9cf-44c6c31efd70086d."
type: "https://tools.ietf.org/html/rfc7231#section-6.5.13"_

Downgrading to 0.19.1...it works again.

#### Expected behavior
Expect still to work in 0.20.0 and be backwards compatible (as version is non-breaking according to NPM semantic versioning)

#### Environment
 - Axios Version  0.20.0
 - Browser Chrome
 - Browser Version 84.0.4147.135
 - Node.js Version 12.8.0
 - OS: Windows 10 2004
 - Additional Library Versions [e.g. VueJS 2.6.12, Vuetify 2.3.9, Firebase 7.19.0 etc.

#### Additional context/Screenshots
N/A

**Comment by sk-** [comment] 2020-09-02 19:40
@ZwapKillrath technically the Semantic versioning spec does allow any kind of changes (including breaking) between versions when the major version is 0. See https://semver.org/#spec-item-4.

In fact, `npm` won't install version `0.20.0` if you specified `^0.19`. Check it out at https://semver.npmjs.com/

**Comment by chinesedfan** [comment] 2020-09-03 15:34
Duplicate of #3220. Sorry for the breaking, but it is satisfied with semantic versioning as @sk- mentiones.

**Closed by chinesedfan** 2020-09-03 15:34 UTC
Labels: status:possible bug

**Comment by ZwapKillrath** [comment] 2020-09-03 15:39
Ok, so its confirmed that there is a breaking change with the DELETE part...

**Comment by jasonsaayman** [comment] 2020-10-23 16:41
Hi,

Axios version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks
