### ISSUE TITLE
axios overwrites host header key

### ISSUE THREAD

**Issue by derSoerrn95** [axios/axios#4156] opened 2021-10-07 10:35 UTC
#### Describe the bug
Hi, I found following error: If I'm setting the host-header in the AxiosRequestConfig axios is going to overwrite the header key for host with its own 'host'. So if I'm setting 'Host' the request axios do contains 'host'. Below you can find two cases of setting the host header.

#### To Reproduce
```ts
// case 1 (setting host directly in header)
(async function() {
    const response: AxiosResponse = await axios('https://www.example.com/some/path', {
          {
              'Host' : 'www.example.com',
              // some more headers
          },
          method: 'GET',
      }
})();
```

```ts
// case 2 (setting host in common header)
(async function() {
    const response: AxiosResponse = await axios('https://www.example.com/some/path', {
          {
              common: {
                  'Host' : 'www.example.com'
              },
              // some more headers
          },
          method: 'GET',
      }
})();
```

#### Expected behavior
In both cases axios overwrites my host-header key with 'host' (instead of 'Host'). Is there any chance to archive that i can send host with an uppercase 'h'?

#### Environment
 - Axios Version [0.22.0]
 - Node.js Version [v16.10.0]
 - OS: [macOS BigSur 11.6]

#### Additional context/Screenshots

**Comment by derSoerrn95** [comment] 2021-10-12 20:34
Would be great 😍

**Comment by ivanchaz** [comment] 2022-09-30 16:47
Hi @jasonsaayman and @GregDevProjects, I'm not sure whether any of you guys are still working on this or not. But, would you guys mind letting me check on this? I am under impression the header is marked as forbidden because the user agent could change the value, but, in this case, axios is the user agent right. So, it should be able to change the value.

Regards

**Comment by GregDevProjects** [comment] 2022-10-01 00:10
@ivanchaz sounds good to me, I'm not working on it

**Comment by ivanchaz** [comment] 2022-10-02 16:31
Thanks for the reply @GregDevProjects. For the issue, I have looked into it. And, seems like I can't replicate it (in branch `v1.x` and tag `v0.22.0`). I have created some snippet to see the header as follows

```
axios.get('https://httpbin.org/get', { headers: { 'Host': 'httpbin.org' } }).then(function (response) {
  console.log(response.headers);
  console.log(response.data)
});
```

and the response is as follow

```
{
  date: 'Sun, 02 Oct 2022 16:22:24 GMT',
  'content-type': 'application/json',
  'content-length': '286',
  connection: 'close',
  server: 'gunicorn/19.9.0',
  'access-control-allow-origin': '*',
  'access-control-allow-credentials': 'true'
}
{
  headers: {
    Accept: 'application/json, text/plain, */*',
    Host: 'httpbin.org',
    'User-Agent': 'axios/0.22.0',
    'X-Amzn-Trace-Id': 'Root=1-6339bac0-65b37db87f5cfd873b0c6c85'
  },
}
```

So, I'm not sure, maybe @derSoerrn95 could help provide us with a reproducable? or maybe this issue has been fixed in another commit? cc @jasonsaayman

**Closed as completed** 2024-09-26 17:48 UTC
