### ISSUE TITLE
The response data object "goods.goodsId" undefined

### ISSUE THREAD

**Issue by limylico** [axios/axios#2113] opened 2019-04-26 01:11 UTC
**Describe the bug**

The response data object "goods.goodsId" undefined
when change the key "goods" to others,that is ok.

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
import axios from 'axios'
import qs from 'qs'
import SERVER_BASE_URL from './config'
import router from '@/router'
import sessionUtil from '@/libs/sessionUtil'

const instance = axios.create({
  baseURL: SERVER_BASE_URL,
  timeout: 120000,
  withCredentials: true, //是否是跨域请求,发送用户请求凭据
  headers: {},
  transformRequest: []
});

// http 请求拦截器
instance.interceptors.request.use(
  config => {
    return config
  },
  err => {
    return Promise.reject(err)
  }
);

// http 响应拦截器
instance.interceptors.response.use(
  res => {
    console.log("response is", res)
    //会话过期，清空前端用户信息，跳转登录页，提示重新登录
    if (res.data.status.statusCode === "CUE-10004") {
      sessionUtil.clearUser();
      router.push("/login");
    }
    return res.data;
  },
  err => {
    //Do something with response error
    return Promise.reject(err);
  }
);

//更专axios post实例方法
const fetch = function(option) {
  //axios实例方法 axios#post(url[,data[,config]])
  if (option.headers) {
    //设置headers属性
    return instance.post(option.url, option.data, {
      headers: option.headers
    });
  } else {
    return instance.post(option.url, qs.stringify(option.data));
  }
}

export default fetch;

```

**Expected behavior**

**Environment:**
 - Axios Version [0.16.2]
 - OS: [win7]
 - Browser [Chrome]
 - Browser Version [73]
 - Additional Library Versions [vue 2.3.3]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![QQ截图20190426090514](https://user-images.githubusercontent.com/22970441/56777260-0c2d5980-6803-11e9-9d8f-5fb7f00ff865.png)
![QQ截图20190426090550](https://user-images.githubusercontent.com/22970441/56777262-10f20d80-6803-11e9-9656-71aac11a2ace.png)

**Comment by limylico** [comment] 2019-04-26 01:52
It is my fault. when I push the data to other array, the bug appears, but I do not why.
![QQ截图20190426095029](https://user-images.githubusercontent.com/22970441/56778476-f4f16a80-6808-11e9-8154-37baad3e93b5.png)

**Comment by limylico** [comment] 2019-04-26 02:31
I am sorry to found that I write the array "find" function wrong, and the vue bidirectional bindings.  the bug appears.
like this:
![QQ截图20190426102759](https://user-images.githubusercontent.com/22970441/56779602-523bea80-680e-11e9-8cdb-2bc3f7a9014e.png)

**Comment by jonnypolite** [comment] 2019-05-08 18:30
I'm afraid I'm pretty confused as to what the issue is here or how/if it has anything to do with axios. In the last code you posted, you're iterating over your item array with `find`. In each iteration of `find` you're assigning `id` to 0 and also returning 0, which is falsy.

- So you're not finding anything because you always return false
- You're reassigning the value of id in each element of the array (Did you mean `item.id === 0`?)
- You aren't capturing the return from `find()` anyway

Maybe you already figured this out though? There wasn't really a question posed in the last comment. Can this bug be closed?

**Comment by limylico** [comment] 2019-05-09 00:37
yes, I known that it was wrong. so close it.

**Comment by jonnypolite** [comment] 2019-05-09 01:35
I don’t have the permissions to close it. 🙂 I’m just a random guy trying to help clean up the bug queue.

You should be able to close it though, yeah?

**Closed** 2019-05-09 02:10 UTC
Labels: bug
