### ISSUE TITLE
something about the AxiosRequestConfig interface

### ISSUE THREAD

**Issue by aweiu** [axios/axios#1256] opened 2017-12-28 12:59 UTC
#### Summary

I want the [AxiosRequestConfig interface](https://github.com/axios/axios/blob/master/index.d.ts#L23) to be this:
```
{
  url?: string;
  method?: string;
  baseURL?: string;
  transformRequest?: AxiosTransformer | AxiosTransformer[];
  transformResponse?: AxiosTransformer | AxiosTransformer[];
  headers?: any;
  params?: any;
  paramsSerializer?: (params: any) => string;
  data?: any;
  timeout?: number;
  withCredentials?: boolean;
  adapter?: AxiosAdapter;
  auth?: AxiosBasicCredentials;
  responseType?: string;
  xsrfCookieName?: string;
  xsrfHeaderName?: string;
  onUploadProgress?: (progressEvent: any) => void;
  onDownloadProgress?: (progressEvent: any) => void;
  maxContentLength?: number;
  validateStatus?: (status: number) => boolean;
  maxRedirects?: number;
  httpAgent?: any;
  httpsAgent?: any;
  proxy?: AxiosProxyConfig | false;
  cancelToken?: CancelToken;
  // custom config
  [someOtherConfig: string]: any;
}
```
So i can add some custom config without type matching error

#### Context
- axios version: *e.g.: v0.17.1*

**Comment by klummy** [comment] 2018-01-08 07:27
I will recommend a `customConfig: object | null` property to be added to the interface which allows users to add unlimited custom configuration without type errors.

I am open submitting a PR for this if the community deems it necessary.

**Comment by jongrim** [comment] 2018-01-14 05:40
@aweiu Where are you receiving an error? I am able to add arbitrary properties to the request config and not receive an error. My sample code is as follows:

```
this.axiosInstance = axios.create({
      baseUrl: "https://yahoo.com",
      custom: {data: 1}
    });
    this.axiosInstance.get('/').then(resp => console.log(resp));
    console.log(this.axiosInstance.defaults.custom) // {data: 1}

// Can also set custom config values through the main axios object
    axios.get({
      url: "https://yahoo.com",
      custom: {data: 1}
    }).then(resp => console.log(resp.data));
```

Furthermore, what use case are you trying to support by adding custom properties? What aren't you able to achieve currently?

**Comment by choi4450** [comment] 2018-03-27 07:20
I need it.. 😪

**Comment by service-paradis** [comment] 2018-11-21 01:07
This would be great!
I'm having Type Checking error using https://github.com/kuitos/axios-extensions since it used custom properties!

**Comment by Helaers** [comment] 2019-03-25 13:31
Any update on this?

**Comment by chinesedfan** [comment] 2020-03-29 10:09
Duplicate of #1963.

**Closed by chinesedfan** 2020-03-29 10:09 UTC
Labels: feature:typescript
