### ISSUE TITLE
Aborting request is not immediate

### ISSUE THREAD

**Issue by ipatalas** [axios/axios#5903] opened 2023-09-18 20:48 UTC
### Describe the issue

Hey! I'm trying to run a simple example with aborting a request but the process doesn't exit but still waits until the server responds (or timeout, whichever comes first).  
See example repro code. Server call is 5 seconds, I'm aborting after a second yet still the process waits another ~4 seconds before it exits. I was expecting abort to be immediate like some sources say. Is this by design?  
If I lower the timeout then it only waits until the timeout so for instance in this example if timeout was 2 seconds then the process would exit after ~2 seconds but it's not a solution because in real life abort can come at any time and I can no longer change the timeout once the request had been fired.  
We are using Axios 1.1 but I checked with most recent 1.5 and it's exactly the same.

### Example Code

```js
import axios from 'axios';

const url = 'https://httpstat.us/200?sleep=5000';

(async function main() {
    const ac = new AbortController();
    axios.defaults.signal = ac.signal;
    axios.defaults.timeout = 5000;

    setTimeout(() => {
        ac.abort();
    }, 1000);

    process.on('exit', () => {
        console.log('Exit', process.uptime());
    });

    try {
        const response = await axios.get(url);

        console.log(`Response: ${response}`);
    } catch (err) {
        console.log(`Error: ${err}`);
        if (axios.isCancel(err)) {
            console.log('Request was aborted', process.uptime());
        }
    }

    console.log('Done', process.uptime());
})();
```

### Expected behavior

I would expect the process to exit right after the request is aborted. It seems like the application itself exists because the `Done` message is shown after the abort but there is something causing the process to hang for few more seconds. Application output:

```
Error: CanceledError: canceled
Request was aborted 1.169009292
Done 1.169065792
Exit 5.624233875
```

As you can see process exists after ~5s (current timeout setting) instead of after request is aborted.

### Axios Version

1.5.0

### Node.js Version

16.19.1

### OS

OSX 13.5.2

**Comment by DigitalBrainJS** [comment] 2023-09-18 21:17
'''
[nodemon] starting `node index.js`
Error: CanceledError: canceled
Request was aborted 1.14789336
Done 1.148665853
[nodemon] clean exit - waiting for changes before restart
'''
It seems that everything is working fine, so it is not very clear what exactly is wrong. Do you expect the "Done" message not to appear?

**Comment by ipatalas** [comment] 2023-09-18 21:26
> ```
> [nodemon] starting `node index.js`
> Error: CanceledError: canceled
> Request was aborted 1.14789336
> Done 1.148665853
> [nodemon] clean exit - waiting for changes before restart
> ```
> 
> It seems that everything is working fine, so it is not very clear what exactly is wrong. Do you expect the "Done" message not to appear?

Does the process exits for you right after the request is aborted?

I've just extended the example to be more clear with:

```
process.on('exit', () => {
     console.log('Exit', process.uptime());
});
```

Can you run it again and show the results? For me it's:

```
Error: CanceledError: canceled
Request was aborted 1.169009292
Done 1.169065792
Exit 5.624233875
```

So request is cancelled after ~1s but process exits after ~5s.

**Comment by DigitalBrainJS** [comment] 2023-09-18 21:56
```
[00:55:24.651] INFO (1720): Started on v16.19.0
[00:55:25.381] INFO (1720): Error: AxiosError: Request failed with status code 503
[00:55:25.382] INFO (1720): Done 0.9607588
[00:55:25.683] INFO (1720): Child process exited with 0

Process finished with exit code 0
```

without calling abort()

```
[00:56:05.643] INFO (14624): Started on v16.19.0
[00:56:10.723] INFO (14624): Error: AxiosError: timeout of 5000ms exceeded
[00:56:10.725] INFO (14624): Done 5.2508587
[00:56:10.738] INFO (14624): Child process exited with 0

Process finished with exit code 0

```

**Comment by DigitalBrainJS** [comment] 2023-09-18 22:26
I got it.  The test sometimes gives different results. Apparently, something is wrong with a timer inside the `follow-redirects` dependency. So if you disable redirects by setting `maxRedirects` to 0 the test always passes.

**Comment by ipatalas** [comment] 2023-09-19 06:51
> I got it. The test sometimes gives different results. Apparently, something is wrong with a timer inside the `follow-redirects` dependency. So if you disable redirects by setting `maxRedirects` to 0 the test always passes.

Well.. it does help but it's not a solution. We need redirects because we don't own the services we are calling and there may be redirects there.

Is there any other workaround for that? Also somehow setting axios timeout to 2s stops the process after 2s so apparently axios know how to clean up the resources then.

**Comment by DigitalBrainJS** [comment] 2023-09-19 14:17
Axios doesn't handle timeouts itself but just passes the timeout value to the low-level request library. The problem is that `follow-redirects` is too outdated and doesn't support the destroy method to abort the request, like the native node request. (in practice it destroys the stream but not the underlying request and timers). As we know abort method was deprecated a long time ago, so Axios 1.x was moved to the current API spec. So that is the reason for the issue. 
I have created PR for `follow-redirects` but it can take some time to be reviewed & merged, plus it seems there are some issues with their CI. But I hope everything will be resolved soon.

**Comment by RubenVerborgh** [comment] 2023-09-19 15:32
@DigitalBrainJS Thanks for the PR, I'll get on it (will need some tests etc.). Could you just help me understand the connection with this issue? The PR is described as a fix for a resource leak, but the issue I see here is a delayed reaction. Understanding the link will help me write the right tests.

**Comment by DigitalBrainJS** [comment] 2023-09-19 16:06
@RubenVerborgh It temporary resource leak. Resources will be released on timeout, but not when we call `destroy` method.
In the current node http request API specification, aborting a request must be done using the `destroy` method (+`close` event), since `abort` and `abort` event have been deprecated since version 14 (https://nodejs.org/api/http.html#requestabort).
Follow-redirects does not have a `destroy` implementation, so it cannot release internal resources when the user calls the `destroy` method, as required by the specification and it just destroys the writable stream. 
Axios uses the destroy method to abort the request, so we have a temporary resource leak (timer and HTTP request) that keeps the node running. So it works with native HTTP request, but not with follow-redirects implementation.

**Comment by RubenVerborgh** [comment] 2023-09-19 18:52
Thanks! Updated fix published as `follow-redirects@1.15.3`.

**Comment by DigitalBrainJS** [comment] 2023-09-19 19:07
Thanks @RubenVerborgh! Axios now works as expected.

```
[21:57:21.350] INFO (13036): Started on v16.19.0 using axios 1.5.0
[21:57:22.365] INFO (13036): Error: CanceledError: canceled
[21:57:22.366] INFO (13036): Request was aborted 1.2750711
[21:57:22.367] INFO (13036): Done 1.2759156
[21:57:22.385] INFO (13036): Child process exited with 0  

Process finished with exit code 0
```

**Closed by DigitalBrainJS** 2023-09-19 19:07 UTC

**Comment by ipatalas** [comment] 2023-09-19 19:28
Wow, that was amazing guys! Thank you both! @DigitalBrainJS when do you plan to release a new Axios version with updated dependency?

**Comment by RubenVerborgh** [comment] 2023-09-19 19:31
@ipatalas Given that axios doesn't pin the version, you can just reinstall and your system will use the latest patch version.

**Comment by ipatalas** [comment] 2023-09-19 19:39
> @ipatalas Given that axios doesn't pin the version, you can just reinstall and your system will use the latest patch version.

Oh.. I haven't noticed that earlier, that's even better ;)
