### ISSUE TITLE
Error objects thrown by Axios contain the entire request including headers which can contain credentials such as API keys

### ISSUE THREAD

**Issue by Vitaefinis** [axios/axios#2648] opened 2020-01-09 14:38 UTC
This is more of a FYI kind of issue.

**Is your feature request related to a problem? Please describe.**
When making a request via Axios, if an error is caught and logged as-is, it will contain the entire request object which contains headers which can include credentials such as API keys.
If someone isn't aware of this and just logs the entire error object or error.toJSON() without sanitising it, they can leak sensitive data and credentials.

**Describe the solution you'd like**
A config option to not append the request object to thrown errors and keep only the standard error properties from the spec https://nodejs.org/api/errors.html#errors_class_error

**Describe alternatives you've considered**
I've worked around this by creating a new error object and only copying the standard error properties and the response status to the new error and throwing that instead.

**Comment by chinesedfan** [comment] 2020-01-10 12:09
Duplicate of #2602. And your workaround is the recommended way in fact.

**Closed by chinesedfan** 2020-01-10 12:09 UTC
