### ISSUE TITLE
Axios 0.27.1 has a pretty serious problem

### ISSUE THREAD

**Issue by gh81997167** [axios/axios#4638] opened 2022-04-26 13:52 UTC
#### Describe the bug
There are some people whose production environment is using the CDN introduction。
Using jsDelivr CDN:<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
Using unpkg CDN:<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

#### To Reproduce
Many people will use the image upload function.Just today, Axios has been upgraded to version 0.27.1. As a result, pictures in our production environment cannot be uploaded and used. I think this will affect more people, which should be a big problem!

```
uploadSpecsValueImgChange() {
  let inputDOM = this.$refs.inputer;
  let file = inputDOM.files[0]; 
  let size = Math.floor(file.size / 1024);
  let formData = new FormData();
  formData.append("file", file); 
  var that = this;
  var index0 = this.specsValueImgIndex0;
  var index1 = this.specsValueImgIndex1;
  axios.post('/api/Upload/one', formData)
	  .then(function(res) {
		  console.log(res.data);
		  if (res.data.code != 0) {
			  layer.msg(res.data.msg);
			  return false;
		  }
  
		  if (index1 >= 0) {
			  that.specsList[index0]['values'][index1]['image'] = res.data.data.file
		  } else {
			  that.specsList[index0]['new_image'] = res.data.data.file
		  }
	  })
	  .catch(function(error) {
		  // console.log(error);
	  });
}
```

#### Expected behavior
Hope it can be repaired soon.

#### Environment
 - Axios Version [e.g. 0.27.1]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]

#### Additional context/Screenshots
Refer to the sample code and simulate submitting images to see this problem

**Comment by MrChriZ** [comment] 2022-04-26 14:13
I've just had to pull it out of a live site.  I was getting an exception about b.split being missing.  That was for a basic json get request.
I've now set the site to use 0.26.0 and it's working again.

**Comment by lorand-horvath** [comment] 2022-04-26 18:05
The CDN versions of the 0.27.0 and 0.27.1 builds (in /dist folder) are broken, see https://github.com/axios/axios/issues/4629

**Comment by Farrien** [comment] 2022-04-26 21:15
0.27.0 still works with FormData and `multipart/form-data` header

**Comment by Farrien** [comment] 2022-04-26 21:17
I noticed that 0.27.1 doesn't send Headers to server. (Maybe I'm wrong bcas not pro in JS)

**Comment by ajmeireles** [comment] 2022-04-26 21:31
I noticed that one of my apps using Axios broke. All requests that deal with files are sending the request data this way.

![image](https://user-images.githubusercontent.com/60591772/165395823-d372bd4e-324d-4720-85b2-cf4be7176e9c.png)

**Comment by Farrien** [comment] 2022-04-26 21:58
Looks like someone pushed test build

**Comment by symonxdd** [comment] 2022-04-27 02:02
For my college project I needed to upload a file. I found some article that explains how to do that in Vue and I had literally struggled for 5 hours straight with this piece of crap bug to just find out that the authors app used an old version of axios which didn't include this pathetic bug which should never had been introduced, ever...

I think I'm done with axios for a few years.

At the time of writing this is **axios 0.27.1 (latest)**

**Comment by gh81997167** [comment] 2022-04-27 03:30
If you encounter similar problems, please first use the CDN of the previous version to ensure normal production environment  
< script SRC = "https://unpkg.com/axios@0.27.0/dist/axios.min.js" > < / script >

**Comment by lorand-horvath** [comment] 2022-04-27 07:41
@gh81997167 0.27.0 has other problems. Use 0.26.1

**Comment by gh81997167** [comment] 2022-04-27 08:05
@lorand-horvath OK, thank you.

**Comment by jasonsaayman** [comment] 2022-04-27 09:23
Will be releasing 0.27.2 that should fix up all these problems

**Comment by dani-vrd** [comment] 2022-04-27 10:36
@jasonsaayman - I tried 0.27.2 and the issue is still not fixed in my case... 

post method works but not the patch method

**Comment by jasonsaayman** [comment] 2022-04-27 11:50
@dani-vrd please can you tell me what CDN link you are using and give me a example of the PATCH request

**Comment by dani-vrd** [comment] 2022-04-27 12:45
@jasonsaayman - I do not use CDN link. I have it over npm installed.

Example: (simplified)

This is over post:

```
await axios
            .post(props.url_submit, getFormData(), {
                headers: { 'body-type': 'multipart/form-data' },
            })....
```

And in case of an update I set the method to "PATCH":

```
function getFormData() {
        let form_data = new FormData();        
        form_data = a_function(form_data);       

        // AND HERE I SET THE PATCH METHOD TO UPDATE CONTENT
        if (isActionUpdate) {
            form_data.append('_method', 'PATCH');
        }

        return form_data;
    }
```

Works fine in 0.26.1 (not testet in 0.27.0)

**Comment by jasonsaayman** [comment] 2022-04-27 12:51
Check this out we handle form data automatically now [here](https://github.com/axios/axios#form-data)

**Comment by dani-vrd** [comment] 2022-04-27 13:13
@jasonsaayman - Hm... I have updated only the package to 0.27.2 and now it works... don't know why... sorry for the false alarm

**Closed** 2022-04-27 13:20 UTC
Labels: status:possible bug
