### ISSUE TITLE
Memory Leak when Handling 502 Errors

### ISSUE THREAD

**Issue by astormnewrelic** [axios/axios#3179] opened 2020-08-07 00:03 UTC
#### Describe the bug

We've discovered what appears to be a memory leak in axios when handling HTTP requests that result in a 502 error.  

#### To Reproduce
1. Run [this small program](https://github.com/raoulus/some-memory-leak/blob/master/index2.js) in a terminal window (sets up an endpoint to call)

2. Run the program whose source is provided below
    ````
    $ node main.js > /dev/null
    ````

3. Monitor memory usage of the node process from program #2

_Expected Behavior_: Memory usage stays constant

_Actual Behavior_: Memory use slowly grows over time

```
//File: main.js
const axios = require('axios')

// localhost:3001/bad
const client = axios.create({
  baseURL: 'http://localhost:3001'
})

const work = async () => {
  try {
    await client.get('/bad')
    console.log('did it')
  } catch (error) {
    console.log('an error')
  }
}

const main = () => {
  setInterval(work, 0)
}
main()
```

#### Expected behavior

We expect the memory use of the node process should stay consistent and not grow

#### Environment
 - Axios Version 0.19.2
 - Adapter: HTTP
 - Node.js Version: v12.18.2
 - OS: 10.14.6

#### Additional context/Screenshots

We maintain New Relic's NodeJS agent.  We had a custom come to us reporting a memory leak in the Node Agent, [with a reproduction here](https://github.com/raoulus/some-memory-leak). Like a lot of the leaks reported to us, this appears to be a case of a small leak in an upstream package (`axois`) being made much worse by the steps the New Relic's Node Agent needs to take in order to instrument it's thing.

**Comment by chinesedfan** [comment] 2020-08-15 07:36
Can you give full codes of `main.js`? Looks like it includes an express server. Then the memory leaking is hard to be determined by axios or express.

**Comment by astormnewrelic** [comment] 2020-08-15 14:47
@chinesedfan D'oh -- my apologies.  I appear to have copy and pasted the wrong program into my ticket description. I have pasted the actual program into the description, and I will include it below as well.  

```
const axios = require('axios')

// localhost:3001/bad -- 
const client = axios.create({
  baseURL: 'http://localhost:3001'
})

const work = async () => {
  try {
    await client.get('/bad')
    console.log('did it')
  } catch (error) {
    console.log('an error')
  }
}

const main = () => {
  setInterval(work, 0)
}
main()
```

**Comment by astormnewrelic** [comment] 2020-08-28 18:54
@chinesedfan were you able to reproduce with the above program, or are you not seeing the problem we're seeing?  Is there anything we can do to help move this along?

**Comment by chinesedfan** [comment] 2020-08-29 07:18
I have a question about the example first, why you need `setInterval` with timeout=0. If you commented the line with axios, will its memory still keeps growing?

**Comment by astormnewrelic** [comment] 2020-08-29 17:31
@chinesedfan If we comment out the axios line the memory will not keep growing, it stabilizes.  

We're using `setInterval` in the above example to call the `work` function over and over again in order to show that the call to `axios` appears to be leaking memory in the thrown exception case.

**Comment by sammccord** [comment] 2020-09-16 15:56
Seeing this as well, would love to see an update :)

**Comment by astorm** [comment] 2020-09-16 16:30
@chinesedfan any updates on this or anything @sammccord and I could do to help move this along?

**Comment by chinesedfan** [comment] 2020-09-17 03:07
Sorry, I don't have much experiences about memory leaking. There are some similar issues in our issue list. Hope the community can find out the reason with an easy understanding report.

**Comment by astorm** [comment] 2020-09-17 03:59
Thank you @chinesedfan -- so if I understand you correctly in addition to seeing the behavior reproduced, you'll need someone that can actually get into the axios internals and describe what's going on that leads to the leak.  @sammccord -- is that the sort of thing you might be up for?

**Comment by astorm** [comment] 2020-10-19 01:06
Still present, still reproducible with the steps listed above.

**Comment by pgcalixto** [comment] 2020-10-19 16:32
Hey, guys, I saw there has been recent updates on this issue (@astorm said it is still reproducible), I'd like to work on this. Is anyone else already tackling this problem?

**Comment by chinesedfan** [comment] 2020-10-20 03:34
@pgcalixto Sure. Feel free to take it, as well as any other issues of axios. This repository requires help from the community urgently.

**Comment by jasonsaayman** [comment] 2021-03-23 14:49
Please check if this error is now fixed with the latest version of master?

**Comment by astormnewrelic** [comment] 2021-03-23 23:05
Happy to check @jasonsaayman -- is that fix in a release yet? If not is there a canonical way to run `axios` from the `master` branch  (is it enough to point NPM at the master branch of this repo, or is a build step required, etc?)

**Comment by jasonsaayman** [comment] 2021-03-29 14:28
@astormnewrelic it seems that the error actually has to do with the follow-redirects package so the issue persists. To answer your question you can do the following `npm install --save ../path/to/mymodule`.

**Closed** 2021-04-29 16:08 UTC
Labels: status:possible bug
