### ISSUE TITLE
Feature request: fetch based adapter

### ISSUE THREAD

**Issue by ccnokes** [axios/axios#1219] opened 2017-12-04 17:09 UTC
I didn't see an issue for this (opened or closed), but if this is a duplicate just close it 😸 . 

Are there any plans for a `fetch` based adapter for axios? I thought I'd check and see if this has been discussed, and if not, if you all would be open to a feature request (or I'm happy to work on it and PR it). 

Reasons for adding a `fetch` adapter are basically for the same reasons you'd use fetch:
- Support for service workers
- Integration with Cache API 
- natively promise based, so axios can become a thinner library
- response streaming 
- probably more that I'm not even thinking of right now

Reasons you'd still want axios wrapping fetch for you (because some people feel like you don't need a lib over fetch): 
- fetch is low level. Using plain fetch in an app that is 99% GET/PUT/POST against a JSON API means lots of duplicate boilerplate code which axios can abstract
- request/response interceptors
- probably more that I'm not even thinking of right now :smile:

**Comment by mividtim** [comment] 2017-12-28 13:47
👍

**Comment by jc275** [comment] 2018-01-01 17:49
Possible duplicate of https://github.com/axios/axios/issues/484

This is a dealbreaker for using Axios in PWAs,  because the serviceworker can only intercept and cache http requests sent via the `fetch` api.

**Comment by jabacchetta** [comment] 2018-01-09 07:57
Just noticed this after diving into service workers this week. Is [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) a viable alternative for PWAs?

**Comment by ccnokes** [comment] 2018-01-09 16:33
@jabacchetta I have no experience with PWAs yet but I would think so. If you want something sort of axios like, https://github.com/jackfranklin/so-fetch, looks good (haven't tried it yet personally though).

**Comment by jabacchetta** [comment] 2018-01-09 21:58
Great, thanks! I'll take a look.

**Comment by NShahri** [comment] 2018-01-11 02:44
Is there any implementation for 'fetch adapter' in progress? otherwise I can work on it

**Comment by ccnokes** [comment] 2018-01-13 04:20
@NShahri I haven't started on anything yet, sadly ☹️

**Comment by NShahri** [comment] 2018-01-14 19:44
@ccnokes Ok, I will send pull request soon

**Comment by ccnokes** [comment] 2018-01-16 04:51
I actually just started working on this too (don't let this discourage you @NShahri, yours might be better or I might not finish it, etc). 

Still hoping for some positive signal from a maintainer. @nickuraltsev or @mzabriskie any thoughts on this? 

I haven't gotten too far into the implementation yet but I know one question that'll come up is do you explicitly opt into the fetch adapter or does it take precedence over the `XMLHttpRequest` one, if available? I'm sure more questions will come later 😄.

**Comment by NShahri** [comment] 2018-01-16 10:00
@ccnokes, at the moment I change the code to choose fetch adapter when fetch is available otherwise it will choose XHR adapter.

Also I am using [whatwg-fetch](https://github.com/github/fetch) polyfill in test environment as it lets me to run the all current tests against fetch adapter with minimum changes. This polyfill uses XHR to implement fetch, so I can use it on test environment for running current XHR tests for fetch adapter. But I am no sure about this approach.

In addition I have another question about 'withCredentials' as I think it can be mapped to ```request.credentials``` which can accept 'include', 'omit' and 'same-origin' as value. I am not sure 'include' or 'same-origin' is the right value when ```withCredianls=true``` or should I change axios interface to let user to choose value except true or false.

@nickuraltsev @mzabriskie

**Comment by NShahri** [comment] 2018-01-16 11:27
@ccnokes this is my first try to implement fetch adapter https://github.com/axios/axios/compare/master...NShahri:feature/fetch-adapter

Remaining tasks:
- Progress handlers (download and upload)
- Setting timeout
- Use new implemented utils/enums in http and xhr adapter
- Test bundle size
- Passing all tests using polyfill
- finalise tests for fetch
- run tests for all xhr, http and fetch adapters

**Comment by ccnokes** [comment] 2018-01-17 03:40
Nice @NShahri! Let me know if you need help with anything.

**Comment by NShahri** [comment] 2018-01-17 04:02
Thanks @ccnokes, Feel free to start implementing any of remaining tasks. let me know which one you started to avoid both of us working on the same task.

**Comment by ccnokes** [comment] 2018-01-24 03:58
Hey @NShahri sorry for the delay, I'll take a look this week at the Redirects task. 

Another thing I thought of while looking at your code (which looks great btw, really awesome progress) that I'd might look into is methods like `utils.forEach` that I don't think will currently work with a native `Headers` object (here, for example, https://github.com/NShahri/axios/blob/feature/fetch-adapter/lib/adapters/fetch.js#L124). It should probably use `Headers.forEach` in that case. Not a big deal. Some of the new ES6 data types that `fetch` and other APIs use might necessitate some changes like that.

**Comment by NShahri** [comment] 2018-01-31 21:53
@ccnokes sorry for delay. 
it is up to you fork/PR me or direct commiting

**Comment by eybarta** [comment] 2018-04-18 08:39
Hey guys, any progress on this? I would LOVE to keep using axios, but I need to implement
offline availability with SW's, can I do anything to help?

thx

**Comment by NShahri** [comment] 2018-04-18 20:10
@eybarta 
Unfortunately I am too busy and can not finalise this feature. 

The minimum requirements are implemented and tested, but I haven't use this in any app. It would be great if you have time and use it in your app. https://github.com/NShahri/axios/tree/feature/fetch-adapter

There is a list of remaining tasks in https://github.com/axios/axios/issues/1219#issuecomment-357931915.

**NOTE:** 
- there are some missing functionalities because it is not supported by fetch in some browsers like request `timeout` and `progress handler`
- because of the differences between `xhr` and `fetch`, there are some functionality in fetch which is not implemented by `axios`, like `credentials: 'same-origin'`

Next phase to finalise `fetch adapter` would be changing `axios` interface to accept options which user can use to configure fetch request

**Comment by rajatvijay** [comment] 2018-11-13 04:31
@NShahri 

are all the remaining task done and released? 
If not is it up for grabs?

**Comment by ccnokes** [comment] 2018-11-14 03:50
Personally, I'd be wary of working adding fetch support as a PR, especially as there's hasn't been any interest shown from maintainers. Also I noticed there's a 1.0.0 version in the plans: https://github.com/axios/axios/projects/2. Maybe a fetch adapter will be a part of that?

**Comment by Mechazawa** [comment] 2018-11-14 11:01
It'd be great if a fetch adapter can be part of 1.0.0. It'd solve a lot of issues I have with `xhrAdapter`.

**Comment by juanarbol** [comment] 2019-01-09 04:32
@ccnokes This issue is already solved, close please.

**Comment by Mechazawa** [comment] 2019-01-09 10:58
@juanarbol What PR was it fixed in?

**Comment by juanarbol** [comment] 2019-01-09 18:32
My bad, if anyone could explain me how to solve, I could help

**Comment by cristianoccazinsp** [comment] 2019-04-07 18:00
Any news on this? When using react native, fetch seems to be way faster than xhr to process json responses and it would be great to use a fetch adapter.

**Comment by pchaganti** [comment] 2019-04-07 18:12
👍

**Comment by ccnokes** [comment] 2019-04-07 20:26
@cristianoccazinsp not from my end. Feel free to pick it up and work a PR 😄.

**Comment by hdpinto** [comment] 2020-03-13 18:46
Any updates on this feature request?

**Comment by sgammon** [comment] 2020-04-12 22:49
this is embarrassing and sad

**Comment by MHA15** [comment] 2020-06-14 07:12
hey guys
any update? 

thank you all for your works

**Comment by Shayan-To** [comment] 2020-07-03 22:18
Any updates?

**Comment by bogdaniy** [comment] 2021-02-13 22:54
Any updates?

**Comment by efeminella** [comment] 2021-03-17 19:35
Any Updates?

**Comment by janat08** [comment] 2021-09-12 19:40
https://gist.github.com/mp035/ae833b68cb45f51dbac7a2520731d22a/forks

**Comment by janat08** [comment] 2021-09-12 19:42
I’d like to use this to convert npm package for cloud flare workers.

**Comment by drmercer** [comment] 2022-09-28 06:28
This is an awful limitation for axios, and saying "it's coming in a complete rewrite of axios" doesn't really solve the problem. The only reason this is an issue for me (and many others) is because I want to use a library that depends on axios, and I'm in an environment that only supports fetch, like Cloudflare Workers. Waiting for (1) axios to release v1 and then (2) the library I'm using to update to axios v1 (which might never happen) is not a good solution at all.

I was able to work around this by using [patch-package](https://www.npmjs.com/package/patch-package) to make axios use a custom fetch-based adapter by default. (I used [this adapter](https://www.npmjs.com/package/@vespaiach/axios-fetch-adapter) built by @vespaiach.)


```diff
diff --git a/node_modules/axios/lib/defaults/index.js b/node_modules/axios/lib/defaults/index.js
index 9199818..1cfccc6 100644
--- a/node_modules/axios/lib/defaults/index.js
+++ b/node_modules/axios/lib/defaults/index.js
@@ -17,15 +17,7 @@ function setContentTypeIfUnset(headers, value) {
 }
 
 function getDefaultAdapter() {
-  var adapter;
-  if (typeof XMLHttpRequest !== 'undefined') {
-    // For browsers use XHR adapter
-    adapter = require('../adapters/xhr');
-  } else if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
-    // For node use HTTP adapter
-    adapter = require('../adapters/http');
-  }
-  return adapter;
+  return require('@vespaiach/axios-fetch-adapter').default
 }
 
 function stringifySafely(rawValue, parser, encoder) {

```

**Comment by sgammon** [comment] 2022-10-16 07:56
sorry guys i really did try to solve this at one point, in #2891.

i would be happy to finish it up and write some tests if the axios team could opine about how to publish it as an external package, or how to land it as a PR. (@jasonsaayman ?)

**Comment by jasonsaayman** [comment] 2022-10-16 08:57
@sgammon please do, just assign me, I will have a look and see if we could get the PR in

**Comment by sgammon** [comment] 2022-10-17 20:14
@jasonsaayman i'm working through an implementation and i'm well on my way, but could you advise about tests?

it looks like the browser-side tests are in `test/specs/`, and node-side tests are in `test/unit/`, right? seeing as `fetch` can be used on both platforms, i may write a testsuite for Node as well as the browser because Node is easier to test with locally. do you object?

followup, is there a way to run the full suite of adapter tests against a new adapter, or should i create tests for this adapter anew?

**Comment by mh-alahdadian** [comment] 2022-10-18 04:52
As far as I know we can not have a upload progress percentage with fetch base technology , Are you going to implement a adapter without supporting upload progress feature ?

**Comment by sgammon** [comment] 2022-10-18 05:16
@mh-alahdadian i haven't gotten that far yet. streams aren't yet standardized on the web platform but perhaps there is a high-quality polyfill or workaround.

in any case, i don't see why this would be a practical limitation. if you're in a browser environment, you can still use the XHR adapter, which supports the `progress` event (axios supports download and upload progress on top of XHR).

if you're in a node environment, you can use the `http` adapter, which also supports upload and download progress.

in more exotic environments like CloudFlare Workers, where you _only_ have access to fetch, this may be an unsupported feature until the spec lands, only because the runtime may not emit the requisite events.

**Comment by KaKi87** [comment] 2022-10-26 16:54
One more reason in favor of a `fetch` adapter is [Deno](https://deno.land/) support.

Thanks

**Comment by TaxBusby** [comment] 2024-02-09 18:22
Another new JS runtime, [`llrt`](https://github.com/awslabs/llrt) just came out, boasting low latency startups for serverless environments. It supports `fetch` but not `http.request`. So a fetch adapter would help support this runtime as well.

**Comment by KaKi87** [comment] 2024-02-09 18:31
For now I recommend [`@haverstack/axios-fetch-adapter`](https://github.com/haverstack/axios-fetch-adapter).

**Comment by sgammon** [comment] 2024-02-10 00:07
cc / @jasonsaayman I'd still love to join discord and attack this; let me know if that's welcome at all :)

**Comment by DigitalBrainJS** [comment] 2024-04-29 17:04
Fetch adapter was added in [v1.7.0-beta.0](https://github.com/axios/axios/releases/tag/v1.7.0-beta.0)
Use `npm i axios@next` to install the beta.

**Closed by DigitalBrainJS** 2024-04-29 17:04 UTC
Labels: fetch

**Comment by Tofandel** [comment] 2024-10-08 14:12
Could we get an option for a custom fetch implementation? Currently it uses the global fetch, but I would like to use `useRequestFetch()` from nuxt

**Comment by roman910dev** [comment] 2025-09-16 11:18
> Could we get an option for a custom fetch implementation? Currently it uses the global fetch, but I would like to use `useRequestFetch()` from nuxt

You can now do it in `v1.12.2`:

```typescript
const req = axios.create({
	adapter: 'fetch',
	baseURL: 'http://0.0.0.0',
	env: { fetch: app.request },
})
```
