### ISSUE TITLE
How can I get the Status Code of the options method?

### ISSUE THREAD

**Issue by Kunoky** [axios/axios#1506] opened 2018-04-27 05:32 UTC
Because of the privileges control of the server,
The Status Code that is sometimes returned is 401
When I tried to process Status Code, I triggered an exception directly.

![qq 20180427132351](https://user-images.githubusercontent.com/26639880/39346040-af7cf77a-4a1e-11e8-988a-bd654dc3218f.png)

![qq 20180427133031](https://user-images.githubusercontent.com/26639880/39346141-33446296-4a1f-11e8-9fcf-71f3e821530a.png)

**Comment by litt1e-p** [comment] 2018-05-10 08:47
same question

**Comment by kucix** [comment] 2018-05-10 11:46
Same here
How do i get status == 401?
In catch block is in argument only config and empty request (XMLHttpRequest)... response is undefined
In network panel i can see status and response body (json) from server, but axios discards it

**Comment by hutsi** [comment] 2018-05-17 17:46
same here

**Comment by xiaomingdexian** [comment] 2018-06-28 08:55
same here

**Comment by tebs1200** [comment] 2018-08-02 00:17
Is this a duplicate of #1427?

**Comment by chinesedfan** [comment] 2019-12-11 14:58
By default, only 2xx status codes are considered as valid. Maybe you can try to custom `config.validateStatus`.

**Closed by chinesedfan** 2019-12-11 14:58 UTC

**Comment by Kunoky** [comment] 2019-12-12 07:12
axios.interceptors.response.use(res => res.status)
