### ISSUE TITLE
error.response is not the same in web and mobile apps

### ISSUE THREAD

**Issue by eldano1995** [axios/axios#3300] opened 2020-09-24 21:02 UTC
#### Describe the bug
When performing an axios request to my API and getting a bad response (status = 4XX), the object **error.response** is not the same between web browsers and mobile devices.

#### To Reproduce
```js

import axios from "axios"

const customAxios = axios.create();

customAxios.interceptors.response.use(
    response => Promise.resolve(response),
    error => {
        console.log('THIS CASE', error.response);
        Promise.reject(error)
     }
)

// URL should be an API endpoint (whatever framework you want) that is protected 
// (requires that user is authenticated). I was using JWT for it. Perform the request with 
// no credentials, or use an expired token to get a response with status= 401 (Unauthorized).
customAxios.get(URL);
```
Execute the code above from a browser in a web app, developed  either in a React or Vue, or whatever you use.
And then execute the same code in mobile app, using the corresponding equivalent (React Native, NativeScript, or whatever you use)

#### Expected behavior
The **error.response** object should be the same in both cases.

#### Environment
 - Axios Version: 0.19.2
 - Adapter: XHR
 - Browser: Chrome
 - Browser Version84.0.4147
 - Node.js Version: 12.16.1
 - OS: Windows 10
 - Additional Library Versions: React: 16.13.1; React Native: 0.63.2

### ScreenShot of the console in my React app when printing error.response (runs on web browser):
![react-axios](https://user-images.githubusercontent.com/24553679/94197009-c9016b00-fe7a-11ea-84b8-4767d83e6bf8.jpg)

### ScreenShot of the console in my React Native app when printing error.response (runs on mobile device):
![react-native-axios](https://user-images.githubusercontent.com/24553679/94197012-ca329800-fe7a-11ea-92bf-88764d81c1fc.PNG)

**Comment by chinesedfan** [comment] 2020-10-07 04:50
Note `config.url` is different, which may be caused by relative path.

**Comment by eldano1995** [comment] 2020-10-07 13:43
> Note `config.url` is different, which may be caused by relative path. Please make sure the host is the same.
> 
> ```
> customAxios.get(URL); // what value of `URL` is?
> ```

It's the same URL: 

http://localhost:8000/profiles/get_AuthenticatedUser_ProfileInfo/
http://192.168.43.76:8000/profiles/get_AuthenticatedUser_ProfileInfo/

It just happens that when I'm testing my React web app, because the frontend and backend **both run in the same machine**, I can accesss the server using my local IP (127.0.0.1, localhost).

But because my React Native app runs in my mobile device and not in my computer, I need to use the actual IP of my machine (192.168.43.76) as baseURL to get access to the API.

NOTE: Machine and cellphone are connected via a WIFI-hostpot created in my cellphone.

#### Just in case, I took this screenshot of the console, using in the web app as base URL the actual IP address (192.168.43.76:8000):
![axios](https://user-images.githubusercontent.com/24553679/95338860-61d3b580-0881-11eb-8352-a671f4fdf402.PNG)


#### Compare it now against the screenshot of the React Native app:
![axios-native](https://user-images.githubusercontent.com/24553679/95338538-099cb380-0881-11eb-9c5f-ecd63aaab768.PNG)

Please let me know if there's something wrong I'm not seeing.

**Comment by chinesedfan** [comment] 2020-10-07 14:12
OK. `statusText/headers/request` are provided by the xhr object, instead of axios. It's normal that they are different between different environment/browsers.

**Comment by eldano1995** [comment] 2020-10-07 17:28
> OK. `statusText/headers/request` are provided by the xhr object, instead of axios. It's normal that they are different between different environment/browsers.

Mmmmm: too bad. 

Nothing I can do then ??

**Comment by chinesedfan** [comment] 2020-10-08 02:17
Closing due to axios has nothing to do. You can jump out the surface differences and think what the real feature you need. For example, if want to handle errors by same codes, then you can write something compatible with both environments.

**Closed by chinesedfan** 2020-10-08 02:17 UTC
Labels: status:more info needed, type:question
