### ISSUE TITLE
axios-0.20.0 index.d.ts Cannot find name 'ProgressEvent'.

### ISSUE THREAD

**Issue by xenoterracide** [axios/axios#3347] opened 2020-10-19 23:02 UTC
## Describe the bug

getting this error from the definitions via yarn2.
```
➤ YN0000: [@bb/common-framework]: ../../../../../.yarn/cache/axios-npm-0.20.0-535d9e0086-6cf2e96317.zip/node_modules/axios/index.d.ts(63,40): error TS2304: Cannot find name 'ProgressEvent'.
```

this is from

```
└─ axios@npm:0.20.0
   ├─ Version: 0.20.0
   │
   └─ Dependencies
      └─ follow-redirects@npm:^1.10.0 → npm:1.13.0
```

doesn't happen if I use 0.19.2. I don't have any usage of `ProgressEvent` myself.

#### To Reproduce

I suspect putting this in a typescript file, and built with yarn2 is enough, it might actually be a bug in `axios-logger`

```
import { AxiosLogger } from '@new10com/axios-logger';
```

#### Environment
```
├─ @bb/common-framework@workspace:ts/lib/common/packages/framework
│  └─ @new10com/axios-logger@npm:0.1.1 (via npm:^0.1.1)
│     └─ axios@npm:0.19.2 (via npm:^0.19)
│
```

```
> node --version                                                    # services -> feature/RS2-1243-logging $ — » +
v12.18.3
> yarn :g:tsc --version                                        # services -> feature/RS2-1243-logging $ — » + RC=1
Version 4.0.3
```

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by sk-** [comment] 2020-10-21 02:02
Duplicate of #3219

**Closed** 2020-10-23 11:23 UTC
Labels: status:possible bug
