### ISSUE TITLE
Content-type headers automatically change on PUT 

### ISSUE THREAD

**Issue by larviz** [axios/axios#2929] opened 2020-04-24 18:00 UTC
If I use this function with FormData as the data automatically changes Content-type headers to 
_Content-Type: multipart/form-data; boundary=----WebKitFormBoundarygUCRrzJieLA2q33y_
ignoring my custom header.

If i use the function with data empty it sends properly my custom header. I have a createProduct function using POST with the same FormData and header and it works great. I don't know what I'm doing wrong :(

This is my code:

`static updateProduct(data, id_product) {
        const url = ${API_BASE_URL}+'/producto/'+${id_product};
        return axios.put(url, data, {
            headers: {'Content-Type': 'application/json'};
        });
    }`

**Comment by nuralimov** [comment] 2020-04-24 19:36
Same problem

**Comment by chinesedfan** [comment] 2020-04-25 11:21
Duplicate of #1603.

**Closed by chinesedfan** 2020-04-25 11:21 UTC
