### ISSUE TITLE
When an OPTION request is sent using a token request, IE11 and the following indicate that the list cannot find the request header

### ISSUE THREAD

**Issue by liudid** [axios/axios#2372] opened 2019-08-25 11:11 UTC
When sending OPTION requests with token requests, IE11 and below said that the list could not find the request header. They tried various methods, such as reducing the browser blocking script, using es6-primise, using babel-polyfill. All browsers except IE browser were normal, and asked for your help. Look at the reason. Thank you.
![DIOX$EM@O0E$YJ5B30$QSYU](https://user-images.githubusercontent.com/31311845/63649116-2a34a780-c76c-11e9-9f3c-2bbec55d5483.png)

**Comment by ryouaki** [comment] 2019-09-15 08:24
Ask your friend who given the api。

**Comment by chinesedfan** [comment] 2019-12-04 14:46
Duplicate of #2371.

**Closed by chinesedfan** 2019-12-04 14:46 UTC
