### ISSUE TITLE
axios.get is not a function

### ISSUE THREAD

**Issue by maddyexplore** [axios/axios#5056] opened 2022-10-07 07:53 UTC

**Comment by eihabkhan** [comment] 2022-10-07 08:11
Duplicate of #5038

**Comment by jasonsaayman** [comment] 2022-10-07 09:12
Update to v1.1.1 this should slove the issue

**Closed by jasonsaayman** 2022-10-07 09:12 UTC

**Comment by NTpspE** [comment] 2022-10-07 09:50
> Update to v1.1.1 this should slove the issue

I'm having the same issue as the original author, on unpkg.com it's using 1.1.1 and axios.post and axios.get "is not a function" so the issue still occurs.

**Comment by eihabkhan** [comment] 2022-10-07 09:52
I found that going back to v1.0.0 solved the issue, so: https://unpkg.com/axios@1.0.0/dist/axios.min.js

**Comment by 1engels** [comment] 2022-10-07 10:22
They just fix it with 1.1.2.

**Comment by kongebra** [comment] 2022-10-15 15:26
Still get this problem with version `1.1.3`
