### ISSUE TITLE
axios 0.19.1 breaks jest tests that use nock

### ISSUE THREAD

**Issue by EvgenyOrekhov** [axios/axios#2654] opened 2020-01-12 15:42 UTC
**Describe the bug**
After upgrading axios from 0.19.0 to 0.19.1 all tests that use nock got broken. They now produce the following error:

```text
Error: Cross origin http://localhost forbidden
```

**To Reproduce**
Repo with minimal test case that reproduces the issue: https://github.com/EvgenyOrekhov/js-framework/tree/axios-bug.

Note that [previous commit](https://github.com/EvgenyOrekhov/js-framework/tree/150ebe811c9531b7699c030e7921514e469fe84e) (which has axios 0.19.0) works fine, the test passes.

```js
import axios from "axios";
import nock from "nock";

it("makes HTTP requests", async done => {
  const scope = nock("https://example.com/foo/")
    .get("/bar")
    .reply(200, { foo: "bar" });

  await axios.get("https://example.com/foo/bar");

  scope.done();
  done();
});
```

**Expected behavior**
The test should pass.

**Environment:**
 - Axios Version: 0.19.1
 - OS: Ubuntu 19.10
 - Browser: n/a
 - Browser Version: n/a
 - Additional Library Versions: nock 11.7.2

**Additional context/Screenshots**
Jest error with stack trace:

```text
 FAIL  src/http.test.js
  ✕ makes HTTP requests (34ms)

  ● makes HTTP requests

    Network Error

      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:83:14)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at XMLHttpRequestEventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at XMLHttpRequestEventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:132:7)
      at dispatchError (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:62:3)
      at Object.validCORSHeaders (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:77:5)
      at receiveResponse (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:847:21)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:679:38)
      at Request.onRequestResponse (node_modules/request/request.js:1066:10)
      at respond (node_modules/nock/lib/playback_interceptor.js:299:11)
      at respondUsingInterceptor (node_modules/nock/lib/playback_interceptor.js:341:7)
      at node_modules/nock/lib/playback_interceptor.js:281:7

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Cross origin http://localhost forbidden
        at dispatchError (/home/user/my-app/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
        at Object.validCORSHeaders (/home/user/my-app/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:77:5)
        at receiveResponse (/home/user/my-app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:847:21)
        at Request.<anonymous> (/home/user/my-app/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:679:38)
        at Request.emit (events.js:321:20)
        at Request.onRequestResponse (/home/user/my-app/node_modules/request/request.js:1066:10)
        at OverriddenClientRequest.emit (events.js:321:20)
        at respond (/home/user/my-app/node_modules/nock/lib/playback_interceptor.js:299:11)
        at respondUsingInterceptor (/home/user/my-app/node_modules/nock/lib/playback_interceptor.js:341:7)
        at /home/user/my-app/node_modules/nock/lib/playback_interceptor.js:281:7 undefined
```

**Comment by textbook** [comment] 2020-01-12 21:53
This seems to be related to using jsdom's XHR, as a workaround you can switch the [test environment][1] to `"node"`.

  [1]: https://jestjs.io/docs/en/configuration.html#testenvironment-string

**Comment by killerchip** [comment] 2020-02-06 16:55
Hmm... switching the test environment to "node", does not help when you test a react app. `jsdom` is needed for the tests to work that rely on browser environment.

**Comment by killerchip** [comment] 2020-02-06 17:16
Here's how you can solve this. (If you don't test for CORS).

Have `nock` include `Access-Control-Allow-Origin` in the response.

```
.reply(200, 'hello world', {'Access-Control-Allow-Origin': '*'})
```

**Comment by Qwerios** [comment] 2020-02-26 11:14
I ended up having to setup a persistent OPTIONS handler as well. My final code looked like this:

```javascript
// Your configuration of headers and target url
//
const allowedHeaders = [
  'ClientName',
  'ClientVersion',
  'Content-Type',
  'Authorization',
];
const nockHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': allowedHeaders.join(',') };
const url = 'https://example.com';

// Persistent OPTIONS handler
//
nock(url).intercept(/./, 'OPTIONS').reply(200, undefined, nockHeaders).persist();

// Actual mock call
//
nock(url).defaultReplyHeaders(nockHeaders).post(path).reply(200, mockResponse);
```

I also did not have the option of switching to the `node` environment for Jest

**Comment by MaffooBristol** [comment] 2020-05-29 15:30
I've had this bug but not with "nock" (I'll be honest, I don't even know what nock is!)

I want to continue using browser-style testing...  what has changed in the _patch_* release that's causing such issues?

*(realising that axios is still pre v1.0.0)

**Comment by MaffooBristol** [comment] 2020-05-29 15:38
I get the feeling it's something to do with the changes to the `withCredentials` behaviour as it appears to be a CORS regression. I have this file called `axiosSetup.js`:

```
/* eslint-disable id-blacklist */
import axios from 'axios';

import NetworkError from '/shared/errors/NetworkError';
import TooManyRequestsError from '/shared/errors/TooManyRequestsError';

export default function axiosSetup() {
  if (axios.defaults.hasBeenSetup) {
    return;
  }
  axios.defaults.hasBeenSetup = true;
  axios.defaults.withCredentials = true;
  axios.interceptors.response.use(
    (res) => res,
    (error) => {
      if (!error?.response) {
        throw new NetworkError(error);
      }
      if (error?.response?.status) {
        if (error.response.status === 429) {
          throw new TooManyRequestsError(error);
        }
      }
      throw error;
    },
  );
}
```

... and this test is failing:

```
  const blankAxiosOpts = { withCredentials: false, headers: null };
  it('should work normally with request', async () => {
    axiosSetup();
    const { data } = await axios.get('https://checkip.amazonaws.com/', blankAxiosOpts);
    expect(data).toMatch(/\d+\.\d+\.\d+\.\d+/gim);
  });
```

... so I'm not sure if it's that something has regressed in Axios, or if I was doing something stupid and now it's only come to light in 0.19.1 / 0.19.2

**Comment by zWingz** [comment] 2020-06-04 06:07
resolved by `axios.defaults.adapter = require('axios/lib/adapters/http');`

**Comment by pramod-2019** [comment] 2020-06-10 11:58
I was also getting the same error with **node+jest** in **axios post** and was getting error **Error: Response for preflight has invalid HTTP status code 400**  and got resolved by **axios.defaults.adapter = require('axios/lib/adapters/http');**

Thank you everyone.

**Comment by EvgenyOrekhov** [comment] 2020-06-13 13:04
I confirm that [zWingz's workaround](https://github.com/axios/axios/issues/2654#issuecomment-638622896) works. Feel free to close this issue.

**Comment by DanJClarke** [comment] 2020-09-01 10:32
Where would I add the `axios.defaults.adapter = require('axios/lib/adapters/http');` in the jest.config.js or the actual spec?

**Comment by Qwerios** [comment] 2020-09-01 10:36
In your spec file @DanJClarke

**Closed** 2020-10-24 12:36 UTC
Labels: type:regression

**Comment by drydenwilliams** [comment] 2020-12-03 12:10
If you checkout the Jest docs for [test environment](https://jestjs.io/docs/en/configuration#testenvironment-string) you can add a docblock in the specific test file to change the envrironment e.g. changing the `.ts` file to `node` would be: 

```
/**
 * @jest-environment node 
 */

describe('api-client', () => {
  it('should intercept a 401 status code', (done) => {
    const statusCode = 401
    const testError = [
      { code: 'AUTHENTICATION_FAILURE', message: 'Authentication Failure' },
    ]
    const scope = nock(apiUrl!).get('/products').reply(statusCode, testError)

    fetchProducts()
      .then()
      .catch((error) => {
        expect(error.response.status).toBe(statusCode)
        expect(sessionStorage.removeItem).toHaveBeenCalledTimes(1)
        scope.done()
        done()
      })
  })
});
```

**Comment by okanthony** [comment] 2020-12-07 14:37
@drydenwilliams per @killerchip's comment this won't work if you need the browser env for your tests. @zWingz's suggestion resolves the issue, and if you're using `jest` you can prevent duplication throughout your tests by putting the fix in your setup file

```
// config/jest/setup.js
import axios from 'axios';
axios.defaults.adapter = require('axios/lib/adapters/http');

// jest.config.js
module.exports = {
  moduleDirectories: ['node_modules', 'src'],
  transform: {
    '^.+\\.(js)$': 'babel-jest'
  },
  setupFiles: ['<rootDir>/config/jest/setup.js'],
};
```

**Comment by chen86860** [comment] 2021-04-16 03:52
By settting  a `testURL` option which is a valid URL you want in jest config will resovle this problem.

**Comment by henrikra** [comment] 2021-04-26 07:43
If you are making node application (backend etc) set Jest`testEnvironment ` to `node` so axios won't act like browser client when doing requests. More info here: https://jestjs.io/docs/configuration#testenvironment-string

**Comment by Antonio-Riccelli** [comment] 2024-04-17 16:17
I wonder if anyone is still struggling with this kind of issue. I tried @zWingz 's solution but getting an `Cannot find module 'axios/lib/adapters/http' from /mySetupFile` error.

**Comment by patrickfeeney03** [comment] 2025-07-08 09:23
> I wonder if anyone is still struggling with this kind of issue. I tried [@zWingz](https://github.com/zWingz) 's solution but getting an `Cannot find module 'axios/lib/adapters/http' from /mySetupFile` error.

Add `axios.defaults.adapter = 'http'` to your test file
and in jest.config.ts add:
```
const config = {
  moduleNameMapper: {
    // Force CommonJS build for http adapter to be available.
    // via https://github.com/axios/axios/issues/5101#issuecomment-1276572468
    '^axios$': require.resolve('axios'),
  },
}
````

Explained here: https://www.npmjs.com/package/nock#axios
