### ISSUE TITLE
get request params URI encoding

### ISSUE THREAD

**Issue by GuramDuka** [axios/axios#1111] opened 2017-10-02 11:38 UTC
#### Summary

function encode(val) in buildURL.js
encodes spaces as '+'
this is wrong, because not all http servers decodes '+'

I comment line out and it working for me.

function encode(val) {
  return encodeURIComponent(val).
    replace(/%40/gi, '@').
    replace(/%3A/gi, ':').
    replace(/%24/g, '$').
    replace(/%2C/gi, ',').
    // replace(/%20/g, '+').
    replace(/%5B/gi, '[').
    replace(/%5D/gi, ']');
}

#### Context

- axios version: *e.g.: v0.16.0*
- Environment: *e.g.: node v6.9.4, chrome 54, windows 7*

**Comment by rolfb** [comment] 2017-10-06 08:36
Can you have provide an example of the data that failed encoding before you commented this line out?

**Comment by GuramDuka** [comment] 2017-10-06 08:41
view    :  {
  type        : "Номенклатура",
  parent     : '00000000-0000-0000-0000-000000000000',
  groups    : true,
  elements  : false,
  filter        : 'Таблица.ЭтоГруппа ИЛИ Таблица.ОстатокОбщий <> 0'
}

spaces in filter value
string is mix of utf-8 cyrillic and latin symbols

**Comment by rolfb** [comment] 2017-10-06 08:45
Did the issue only occur in the `filter` value?

Can you provide the final URL before and after commenting out the line?

**Comment by GuramDuka** [comment] 2017-10-06 08:54
BEFORE:
http://localhost:3000/api/backend?r=%7B%22r%22:%7B%22type%22:%22%D0%9D%D0%BE%D0%BC%D0%B5%D0%BD%D0%BA%D0%BB%D0%B0%D1%82%D1%83%D1%80%D0%B0%22,%22parent%22:%2200000000-0000-0000-0000-000000000000%22,%22groups%22:true,%22elements%22:false,%22filter%22:%22%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0.%D0%AD%D1%82%D0%BE%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B0+%D0%98%D0%9B%D0%98+%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0.%D0%9E%D1%81%D1%82%D0%B0%D1%82%D0%BE%D0%BA%D0%9E%D0%B1%D1%89%D0%B8%D0%B9+%3C%3E+0%22,%22cols%22:[%22%D0%9A%D0%BE%D0%B4%22,%22%D0%9D%D0%B0%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%22,%22%D0%90%D1%80%D1%82%D0%B8%D0%BA%D1%83%D0%BB%22,%22%D0%9F%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%22,%22%D0%9E%D1%81%D1%82%D0%B0%D1%82%D0%BE%D0%BA%D0%9E%D0%B1%D1%89%D0%B8%D0%B9%22,%22%D0%9D%D0%B0%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%9F%D0%BE%D0%BB%D0%BD%D0%BE%D0%B5%22,%22%D0%94%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D0%9D%D0%BE%D0%BC%D0%B5%D0%BD%D0%BA%D0%BB%D0%B0%D1%82%D1%83%D1%80%D1%8B%22,%22%D0%94%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D0%9D%D0%BE%D0%BC%D0%B5%D0%BD%D0%BA%D0%BB%D0%B0%D1%82%D1%83%D1%80%D1%8B%D0%92%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B5HTML%22]%7D,%22m%22:%22dict%22,%22f%22:%22list%22%7D

AFTER:
http://localhost:3000/api/backend?r=%7B%22r%22:%7B%22type%22:%22%D0%9D%D0%BE%D0%BC%D0%B5%D0%BD%D0%BA%D0%BB%D0%B0%D1%82%D1%83%D1%80%D0%B0%22,%22parent%22:%2200000000-0000-0000-0000-000000000000%22,%22groups%22:true,%22elements%22:false,%22filter%22:%22%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0.%D0%AD%D1%82%D0%BE%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B0%20%D0%98%D0%9B%D0%98%20%D0%A2%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D0%B0.%D0%9E%D1%81%D1%82%D0%B0%D1%82%D0%BE%D0%BA%D0%9E%D0%B1%D1%89%D0%B8%D0%B9%20%3C%3E%200%22,%22cols%22:[%22%D0%9A%D0%BE%D0%B4%22,%22%D0%9D%D0%B0%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%22,%22%D0%90%D1%80%D1%82%D0%B8%D0%BA%D1%83%D0%BB%22,%22%D0%9F%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%22,%22%D0%9E%D1%81%D1%82%D0%B0%D1%82%D0%BE%D0%BA%D0%9E%D0%B1%D1%89%D0%B8%D0%B9%22,%22%D0%9D%D0%B0%D0%B8%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%9F%D0%BE%D0%BB%D0%BD%D0%BE%D0%B5%22,%22%D0%94%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D0%9D%D0%BE%D0%BC%D0%B5%D0%BD%D0%BA%D0%BB%D0%B0%D1%82%D1%83%D1%80%D1%8B%22,%22%D0%94%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%D0%9D%D0%BE%D0%BC%D0%B5%D0%BD%D0%BA%D0%BB%D0%B0%D1%82%D1%83%D1%80%D1%8B%D0%92%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B5HTML%22]%7D,%22m%22:%22dict%22,%22f%22:%22list%22%7D

**Comment by rolfb** [comment] 2017-10-06 08:59
Thanks. Do you have any information on the server that didn't accept the `+` octet as a space?

**Comment by GuramDuka** [comment] 2017-10-06 09:18
Server: Apache/2.4.27 (Win64) OpenSSL/1.1.0f

I apologize for the fact that unwittingly misled you. The problem is not the HTTP server. The problem is in the app's library. Not all libraries applications follow the recommendations www.w3.org. It's ironic, but the variant with %2B instead of + , allows for higher compatibility with all libraries.

**Comment by rolfb** [comment] 2017-10-06 09:35
I assume that you mean `%20`?

Looking at the RFC-3986 standard for URIs there's the following information in 2.3:

```
      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="```

gen-delims being reserved in the path of the URI and sub-delims being reserved after the `?` in params, and in a later standard `[` and `]` were added. So `+` shouldn't be an issue as it's within the standard, but I can clearly see that it is.

**Comment by GuramDuka** [comment] 2017-10-06 09:45
> I assume that you mean %20?
Yes, I was wrong.

**Comment by davidlaym** [comment] 2018-07-12 17:23
I'm facing a similar issue in which i'm posting to a legacy server that doesn't accept `+` as space and needs `%20`. Is there a way to configure the encoding or skip it?

**Comment by davidlaym** [comment] 2018-07-12 18:03
To answer my own question, I found out about `paramsSerializer` in the config parameter and then found the default implementation of `paramsSerializer` in the code 
https://github.com/axios/axios/blob/ae218d0131ecbd683310272c10b0273fd1d97de4/lib/helpers/buildURL.js#L5-L13

and 

https://github.com/axios/axios/blob/ae218d0131ecbd683310272c10b0273fd1d97de4/lib/helpers/buildURL.js#L35-L58
This led me to implement my own version overriding the encoder and bypassing some of the util functions as I'm working on ES6 and nodejs and I can use some built in alternatives: 

```js

function encode(val: any) {
  return encodeURIComponent(val)
    .replace(/%40/gi, '@')
    .replace(/%3A/gi, ':')
    .replace(/%24/g, '$')
    .replace(/%2C/gi, ',')
    .replace(/%5B/gi, '[')
    .replace(/%5D/gi, ']');
}

function customSerializer(params: any): string {
  return Object.keys(params)
    .map((key: any) => {
      var val: any = params[key];
      if (val === null || typeof val === 'undefined') {
        return;
      }
      var keyName = key;
      if (Array.isArray(val)) {
        keyName = key + '[]';
      } else {
        val = [val];
      }
      return val
        .map((v: any) => {
          if (Object.prototype.toString.call(v) === '[object Date]') {
            v = v.toISOString();
          } else if (v !== null && typeof v === 'object') {
            v = JSON.stringify(v);
          }
          return encode(key) + '=' + encode(v);
        })
        .join('&');
    })
    .join('&');
}
```

**Comment by drakej** [comment] 2019-04-19 15:47
You're violating the spec here, at least current ones from what I see. Axios broke what was working in jQuery so I think it's safe to say that you should use %20 as it's most compatible regardless of what old specs say about + being used for URLs.

**Comment by drakej** [comment] 2019-04-19 15:58
I just realized that you set this and it's not Axios itself. Sorry my misunderstanding in how things work. You can ignore my comment, and really the issue is Qs.stringify.

Since you can set a custom serializer, this issue isn't Axios anyways. Sorry if I wasted your time on this. I think you can actually close this as it's not an Axios bug at all.

**Comment by meteorlxy** [comment] 2019-06-04 09:09
I guess `%20` is ` `, and `%2B` is `+`.

![image](https://user-images.githubusercontent.com/18205362/58866574-729f7480-86eb-11e9-848b-805e255a24d3.png)

Is this a typo or intended?

https://github.com/axios/axios/blob/2ee3b482456cd2a09ccbd3a4b0c20f3d0c5a5644/lib/helpers/buildURL.js#L11

**Comment by k-kusumitha** [comment] 2019-07-26 07:33
Same issue here

**Comment by ruscon** [comment] 2019-09-05 11:03
I have the same issue with `#` symbol

**Comment by CristianPinzaru** [comment] 2019-09-09 20:57
Same issue with `[` and `]`...

**Comment by cambraca** [comment] 2019-11-21 15:34
Created PR #2563 to fix this and other similar issues.

**Comment by jasonsaayman** [comment] 2020-05-27 12:39
On this I don't think this should be implement as mentioned previously if you'd like to use another format, you can set a custom paramsSerializer as follows:

```js
axios.defaults.paramsSerializer: function(params) {
  // return a query string
}
```

Using the qs library:
```js
axios.defaults.paramsSerializer: function(params) {
  return qs.stringify(params, { indices: false }); // param=value1&param=value2
}
```

**Closed by jasonsaayman** 2020-05-27 12:39 UTC
Labels: component:encoding

**Comment by Cactusbone** [comment] 2020-11-30 14:31
> On this I don't think this should be implement as mentioned previously if you'd like to use another format, you can set a custom paramsSerializer as follows:

Indeed we can use a custom paramsSerializer to use RFC 3986, however I believe it should be the default, because latest web servers won't accept RFC 1738 encoded params, however old servers should accept RFC 3986 (at the very least the %20 encoding for spaces is backward compatible). 

Using a custom paramsSerializer must be done every time we use axios, so it's quite error prone imo.
