### ISSUE TITLE
custom config passed by axios.create lost in the interceptor

### ISSUE THREAD

**Issue by suzhihao** [axios/axios#2903] opened 2020-04-17 03:32 UTC
Axios Version : 0.19.x
Custom config passed by axios.create lost in the interceptor
```js
const client = axios.create({custom1: 'xxx'})
client.interceptors.response.use(res => {
  config.custom1 // undefined
  config.custom2 // xxx
  return res.data
})
client.get('/xxx', {custom2: 'xxx'})
```

**Comment by chinesedfan** [comment] 2020-04-17 14:54
Duplicate of #2587.

**Closed by chinesedfan** 2020-04-17 14:54 UTC
