### ISSUE TITLE
Request interceptors should be able to access the expected final URL

### ISSUE THREAD

**Issue by boutell** [axios/axios#4793] opened 2022-06-17 19:56 UTC
#### Is your feature request related to a problem? Please describe.

An interceptor cannot be used for request signing purposes because it cannot access the final URL. Generating the final URL yourself involves duplicate logic to interpret the `baseURL` and `params`, which is risky and a maintenance burden.

A workaround exists, but relies on "deep imports" which creates an expectation of stability for submodules of Axios that is probably not valid.

#### Describe the solution you'd like

Export a `buildURL` method from axios, so that it is possible to call `axios.buildURL(config)` to predict what the final URL will be using the same mechanisms Axios uses internally. This method would take all appropriate config parameters into account, i.e. `baseURL` and `params`, unlike the internal `buildURL` helper which only really deals with `params`.

#### Describe alternatives you've considered

This hack works, but it's probably not stable for the long term:

```
import buildURL from 'axios/lib/helpers/buildURL';
import buildFullPath from 'axios/lib/core/buildFullPath';

instance.interceptors.request.use(async config => {
  config.headers['My-Signature-Header'] = await sign({
    url: buildFullPath(config.baseURL, buildURL(config.url, config.params)),
    // ... etc.
  })
  return config;
});
```

I'm guessing you'd prefer folks not rely on that, as `lib/helpers` and `lib/core` are not part of the official API of Axios.

#### Additional context

See also #1549. On that ticket it was suggested that a custom adapter was the way to go, but looking at the source for the core adapters, they depend on importing the same private, undocumented APIs I'm using above so I don't see how this helps.

Thanks for all your work on Axios. It is appreciated.

**Comment by Hasan-Jawaheri** [comment] 2022-08-30 10:21
Yeah I am facing the same issue. Would be great if those functions can be exported or somehow accessible without reaching deep into library implementation

**Comment by jamesmbourne** [comment] 2023-02-18 00:35
This is [preventing me from supporting Axios 1.x](https://github.com/jamesmbourne/aws4-axios/issues/701) in https://github.com/jamesmbourne/aws4-axios/ as the AWSv4 signature relies on the final URL.

In previous versions I bolted together `buildURL`, `combineURLs`, and `isAbsoluteURL` but now these are not exported from the module.

I understand the reason for this in not wanting to have any internal change result in a breaking change, but knowing what the final URL Axios is going to make a request to is crucial.

**Comment by jamesmbourne** [comment] 2023-05-02 22:25
@DigitalBrainJS perhaps a duplicate of #5000?

**Comment by Theodore100billy** [comment] 2023-05-03 02:28
It will definitely help you out if you apply from my perspective

**Comment by Mifrill** [comment] 2024-01-02 20:44
any updates on this?

**Closed** 2024-09-26 18:33 UTC
