### ISSUE TITLE
HTTPS calls too slow on Internet Explorer when using self-signed certificate

### ISSUE THREAD

**Issue by dparasam** [axios/axios#1747] opened 2018-08-21 18:09 UTC
#### Summary

HTTPS calls on Internet Explorer too slow when using self-signed certificates.

The code looks like:
`
let response = await axios.get('https://127.0.0.1')
`
I have self-signed certificate at that URL and this runs fairly quickly on Firefox, Chrome and Safari.  On Internet Explorer however it takes well over a minute.  I don't see any errors or warnings in the developer console on Internet Explorer.  If I make a request to a site that has non-self-signed certificate or if I switch to plain HTTP instead of HTTPS, the slowness goes away.

#### Context

- axios version: v0.18.0
- Environment: Internet Explorer 11.1884.14393.0

**Comment by OpenGG** [comment] 2018-08-22 08:50
Axios uses `XMLHttpRequest()` on web. Could you make the same request with `XMLHttpRequest()` and see if that's slow too?

If this issue is caused by IE, it can't be fixed by Axios.

**Comment by chinesedfan** [comment] 2020-01-21 10:23
Maybe try the new `fetch` api. If you still want to use axios, you will need an adapter until #1219 is solved.

**Closed by chinesedfan** 2020-01-21 10:23 UTC
