### ISSUE TITLE
can't config `maxBodyLength`

### ISSUE THREAD

**Issue by sabakugaara** [axios/axios#1323] opened 2018-01-26 10:18 UTC
#### Summary

`maxBodyLength` is a option for [follow-redirect](https://www.npmjs.com/package/follow-redirects#options) which is default transport for axios in node.js environment.

so, can't upload file > 10M

#### Context
- axios version: all version
- Environment: node all version

**Comment by sabakugaara** [comment] 2018-01-26 11:41
follow-redirect add this option in `v1.3.0` https://github.com/olalonde/follow-redirects/commit/847a47fb00ea2dcb7a8886ca16d9d82dc6accb5d

**Comment by Khaledgarbaya** [comment] 2018-01-30 12:18
duplicate of https://github.com/axios/axios/issues/1286

**Closed by Khaledgarbaya** 2018-01-30 12:18 UTC
Labels: feature
