### ISSUE TITLE
Can't post FormData since Axios 0.25.0

### ISSUE THREAD

**Issue by TomCorvus** [axios/axios#4406] opened 2022-01-19 13:36 UTC
#### Describe the issue
I can't post FormData since `"axios": "^0.25.0",`

`Error: Request failed with status code 400`

#### Example Code
```js
export const client = axios.create({
        baseURL: URL_API,
        withCredentials: true,
        responseType: 'json',
	timeout: 30000,
});

const params = new FormData();

params.append('name', data.model);
params.append('idFuel', data.idFuel);
params.append('power', data.idPower);

client.post(`/app/society/${idSociety}/vehicle`, params, { headers: { "Content-Type": "multipart/form-data" } })
```

#### Expected behavior, if applicable
That it works

#### Environment
 - Axios Version: 0.25.0
 - Node.js Version: v14.17.6
 - OS: iOS 15, Android 11 (But on all platforms and versions)
 - Additional Library Versions: React Native 0.64.3

#### Additional context/Screenshots
No problem with  `"axios": "^0.24.0",`

I saw this PR https://github.com/axios/axios/pull/3757 on 0.25.0, but I don't know what I have to change in code.

Thanks for your help 👍

**Comment by dawidchyrzynski** [comment] 2022-01-20 15:39
I'm having the same problem since updating to 0.25.0.

**Comment by diego-paired** [comment] 2022-01-20 16:03
We have the same issue, with the following code:

```
  const data = new FormData();
  data.append(name, {
    uri: toUri(filePath),
    name: fileName,
    type,
  });
  return await post<T>(endpoint, data, {
    headers: {
      Accept: 'application/json',
      'Content-Type': 'multipart/form-data;',
      'cache-control': 'no-cache',
    },
  });
```

The backend throws a `Multipart: Boundary not found` error

**Comment by azuken** [comment] 2022-01-21 09:16
Same behaviour with same context (React Native), but with `application/x-www-form-urlencoded` and `URLSearchParams`.

I have a bad request 400 error.

Sample : 

```ts
  const url = `https://XXXX.com/XXXX/token`;
  const params = new URLSearchParams({
    client_id: payload.client_id,
    code: payload.code,
    [...]
  });

  return await axios.post(url, params, {
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    }
  });
```

**Comment by DigitalBrainJS** [comment] 2022-01-28 23:14
This problem appears to be due to someone recklessly optimizing the `isFormData` function in the utils.js file. This could break form detection logic in a non-browser environment where FormData is not a native object that can be recognized by the `Object.prototype.toString` method. Fixed in #4413 with some additional benefits.

**Comment by marf** [comment] 2022-01-31 11:34
Same issue here, could the PR be merged and released, please.

**Comment by tapz** [comment] 2022-01-31 12:20
Why are this kind of useless "optimizations" even done? Why change something that works? Nobody will see any speed improvement.

**Comment by LarissaGuder** [comment] 2022-02-01 19:27
Thx bro <3.
I have the same issue here, and just downgrading to  "^0.24.0" version, solved my problem.
Waiting for the release.

**Comment by Eduardo-lunardi** [comment] 2022-02-01 19:30
Same issue here, could the PR be merged and released, please.

**Comment by jasonsaayman** [comment] 2022-02-02 11:49
Merged, I will release tonight closing

**Closed by jasonsaayman** 2022-02-02 11:49 UTC
Labels: type:question, type:confirmed bug

**Comment by TomCorvus** [comment] 2022-02-10 10:27
Any news about the next release @jasonsaayman?

**Comment by falkenhawk** [comment] 2022-02-11 21:53
@TomCorvus I believe https://github.com/axios/axios/pull/4448 should be reviewed and merged first

**Comment by kocyigityunus** [comment] 2022-02-14 18:50
if you are having any issues with multipart form data upload on react native. 
please check: [https://stackoverflow.com/a/71116822](url)

**Comment by tapz** [comment] 2022-02-15 08:30
0.26.0 does not work with React Native. Could someone please test the changes with RN before releasing?

**Comment by raajnadar** [comment] 2022-02-19 14:51
This issue is due to no boundary in the 'Content-Type'. Downgrading to 0.24.0 adds this automatically.

**Comment by kenikori** [comment] 2022-02-23 11:37
It works for me:
```js
const formData = new FormData();
...
const response = await networking.post('/URL', formData, {
  headers: {
    'Content-Type': 'multipart/form-data',
  },
  transformRequest: (data, headers) => {
    return formData;
  },
});
```

Versions:
react-native: 0.67.2
axios: 0.26.0

**Comment by raajnadar** [comment] 2022-02-23 19:16
> @kenikori is it the official way to post FormData with Axios now? Or is it just a crutch?

If you read the docs they say there is no need to add custom content type from our end we need to use a method provided by axios, which will handle the default headers for api calls.

**Comment by tapz** [comment] 2022-02-24 10:41
I'm not going to add any bubble gum code to fix a bug in axios. I'll just wait for a version that actually works. Not even sure if there is any need to upgrade 0.24.0 any time soon as this version works just fine.

**Comment by hirbod** [comment] 2022-03-04 00:14
Thanks @kenikori
Wish I would've seen that before I wasted 5 frickin hours understanding, why image uploads are broken for me out of the blue

**Comment by hirbod** [comment] 2022-03-04 00:32
Just found out, thanks to this comment:
https://stackoverflow.com/questions/56235286/react-native-post-form-data-with-object-and-file-in-it-using-axios/71116822#71116822

that you don't need to return "formData" in your transformRequest, it is just enough to return "data".

```tsx
const formData = new FormData();
...
const response = await networking.post('/URL', formData, {
  headers: {
    'Content-Type': 'multipart/form-data',
  },
  transformRequest: (data) => {
    return data; // thats enough
  },
});
```

**Comment by schteff** [comment] 2022-03-11 07:50
This is a shorter form, since it is still needed in 0.26.1

```
axios.post(url, formData, {
  headers: { 'Content-Type': 'multipart/form-data' },
  transformRequest: formData => formData,
})
```

The headers value might only be needed if you have modified the default Content-Type for axios. (just a guess since I have read that axios should set the correct Content-Type based on the FormData type)

In which axios version will the fix that closed this issue be released?

**Comment by mpespo** [comment] 2022-03-17 15:59
Hello! Any news about the fix? thanks!!

**Comment by CossyCossy** [comment] 2022-03-19 19:13
> This is a shorter form, since it is still needed in 0.26.1
> 
> ```ts
> axios.post(url, formData, {
>   headers: { 'Content-Type': 'multipart/form-data' },
>   transformRequest: formData => formData,
> })
> ```
> 
> The headers value might only be needed if you have modified the default Content-Type for axios. (just a guess since I have read that axios should set the correct Content-Type based on the FormData type)
> 
> In which axios version will the fix that closed this issue be released?

Works perfectly for me

**Comment by VictorPulzz** [comment] 2022-04-01 15:28
This really strange bug, please fix this!

**Comment by pods13** [comment] 2022-04-06 11:29
Axios 0.26.1
This is what worked for me;
```
const formData = new FormData();
...
const response = await networking.post('/URL', formData, {
  headers: {
   ...formData.getHeaders()
  }
});
```

**Comment by princefishthrower** [comment] 2022-04-07 08:34
@pods13 - In some environments, TypeScript will say that `getHeaders()` doesn't exist on type `FormData` - like in React Native

@kenikori - thank you, you are a great scholar for finding this hack and have saved me from completely smashing my keyboard. I think this should be the 'accepted' way as it looks like it will work on any environment (browser, node, react native)

**Comment by brettins** [comment] 2022-04-25 20:35
React Native now works as of Axios `0.27.0`!

**Comment by c-info** [comment] 2022-04-26 09:51
Thx bro <3.
I have the same issue here, and just downgrading to "^0.24.0" version, solved my problem.
Waiting for the release.

**Comment by symonxdd** [comment] 2022-04-27 01:57
For my college project I needed to upload a file. I found some article that explains how to do that in Vue and I had literally struggled for 5 hours straight with this piece of crap bug to just find out that the authors app used an old version of axios which didn't include this pathetic bug which should never had been introduced, ever...

I think I'm done with axios for a few years.

**Comment by Wexleron** [comment] 2022-04-28 10:45
> Thanks @kenikori Wish I would've seen that before I wasted 5 frickin hours understanding, why image uploads are broken for me out of the blue

2 days for me, then i give up for 2 weeks and take a rest:-) I did exactly by the book, every help on internet was exactly same and didnt functioned. I still ahve problems. but at least I know wheres the catch

**Comment by jasonsaayman** [comment] 2022-04-29 14:01
@Wexleron please give the latest version a try and let me know if that solves this

**Comment by Wexleron** [comment] 2022-04-29 14:15
@jasonsaayman Hi, schteff's tip worked for me. Simply updating the Axios did not.

Thanks to Schteff.

The tip:

> This is a shorter form, since it is still needed in 0.26.1
> 
> ```ts
> axios.post(url, formData, {
>   headers: { 'Content-Type': 'multipart/form-data' },
>   transformRequest: formData => formData,
> })
> ```
> 
> The headers value might only be needed if you have modified the default Content-Type for axios. (just a guess since I have read that axios should set the correct Content-Type based on the FormData type)
> 
> In which axios version will the fix that closed this issue be released?

**Comment by DigitalBrainJS** [comment] 2022-04-29 14:54
@Wexleron  Can you please run the following code on your platform and then post the result here?
```js
import axios from "axios";
import utils from "axios/lib/utils.js";

const form = new FormData();
const prototype = FormData.prototype;

console.log(
  JSON.stringify({
    VERSION: axios.VERSION,
    client: typeof navigator !== "undefined" && navigator.userAgent,
    node: typeof process !== "undefined" && process.version,
    isFormData: utils.isFormData(form),
    toString: String(form),
    stringTag: form[Symbol.toStringTag],
    constructor: prototype.constructor,
    props: Object.getOwnPropertyNames(prototype)
  })
);
```

**Comment by DigitalBrainJS** [comment] 2022-04-29 15:38
@kocyigityunus Axios uses this kind of check internally (https://stackoverflow.com/questions/39468022/how-do-i-know-if-my-code-is-running-as-react-native) besides React Native must emulate the browser environment, so the main globals should be present.

**Comment by Wexleron** [comment] 2022-04-29 15:44
> @Wexleron can you also provide info about the environment? Are you trying to run axios on react native or node or browser ? What are the versions, of react native, node, browser, etc?
React Native 17.0.1, Expo 5.4.3, node 16.14.2, running on Android 11 Device. It works now. I am sorry if I am not helpful, I am pretty much in learning process still. Also I am on react native as my secondary skill, I primarily focus on Python & Django backend..

**Comment by gavrichards** [comment] 2022-05-05 13:54
I've tested `0.27.2` today in React Native and found it works, where it previously wasn't.

**Comment by jasonsaayman** [comment] 2022-05-05 14:01
Please donrt use 0.27.0 that was a borked release, please use the latest version

**Comment by quantrpeter** [comment] 2022-06-10 06:35
none of above solutions works in axios@0.27.2 with "react-native": "0.68.2", :-(

**Comment by Srh07** [comment] 2022-06-13 09:27
> I've tested `0.27.2` today in React Native and found it works, where it previously wasn't.

I've tested `0.27.2` with "react-native": "0.67.4" and I can confirm this works, without the need to use "transformRequest"

**Comment by rizqirizqi** [comment] 2022-07-13 09:07
Just tested `0.27.2` and it's working as expected now.

**Comment by VoiceDictionary** [comment] 2022-08-29 02:06
in my case it as an ID10T error...
//no worky as 'file'
formData.append("**file**", imgData);

//now it worky as 'image'
formData.append("**image**", imgData);

ENV
"axios": "^0.27.2",
"expo": "^45.0.6",
"react": "17.0.2",

**Comment by rizaldimaulidia** [comment] 2022-10-29 13:16
I have added transformRequest according to @Wexleron answer. But i have still can't fix this issue. But after quite a while I have found a solution to fix this issue, the key is **don't set "Conten-type: multipart/form-data" manually, just remove it, let axios create that header automatically**. The folowing code will fix this issue :

`const formData = new FormData();
...
const response = await networking.post('/URL', formData, {
  transformRequest: () => formData,
});`

Env:
"axios": "^1.1.3"
"react": "18.2.0"

**Comment by erbaafidotama** [comment] 2022-11-10 07:42
> I have added transformRequest according to @Wexleron answer. But i have still can't fix this issue. But after quite a while I have found a solution to fix this issue, the key is **don't set "Conten-type: multipart/form-data" manually, just remove it, let axios create that header automatically**. The folowing code will fix this issue :
> 
> ```
> const formData = new FormData();
> ...
> const response = await axios.post('/URL', formData, {
>   transformRequest: () => formData,
> });
> ```
> 
> Env: "axios": "^1.1.3" "react": "18.2.0"

Thanks for the solution. I follow that code, and i can throw formData to backend.

env:
"axios": "^1.1.3",
"react": "^18.2.0",

**Comment by markusand** [comment] 2023-02-14 11:14
Still having this error with 1.3.3. Axios is not setting Content-Type headers and have to use this workaround.

> This is a shorter form, since it is still needed in 0.26.1
> 
> ```ts
> axios.post(url, formData, {
>   headers: { 'Content-Type': 'multipart/form-data' },
>   transformRequest: formData => formData,
> })
> ```
> 
> The headers value might only be needed if you have modified the default Content-Type for axios. (just a guess since I have read that axios should set the correct Content-Type based on the FormData type)
> 
> In which axios version will the fix that closed this issue be released?

**Comment by jmgrady** [comment] 2023-03-01 15:31
I am having the error with 1.3.4 as well.

**Comment by blaisebarre** [comment] 2023-04-22 21:30
Solved ?

**Comment by ibrahimvectra** [comment] 2023-05-20 12:23
dont think so . I still use 0.24.0

> Solved ?

**Comment by jaques30081983** [comment] 2023-06-12 10:37
I tried with 1.4.0 but still have to use that workaround to make it work ->

axios.post(url, formData, {
   transformRequest: () => formData,
})

**Comment by dreamingofcows** [comment] 2023-08-14 22:17
I am using Axios 1.4 (also tried with 1.3.4) and the work around still does not work for me:

If I look at the actual request payload it still just sends the string "[object Object]" instead of the actual data... help...

```
axiosConfig
      .post(
        `/url`,
        applicationFormData,
        {
          transformRequest: () => applicationFormData,
        }
      );
      
```

**Comment by dreamingofcows** [comment] 2023-08-15 19:42
In case anyone else is still struggling with this: 
I managed to get it to work but I needed to add another line to the post request, I have NO IDEA why it works but it does.  I guess adding it finally convinces Axios that it is supposed to be a file upload

``axios.post(
        `/url`,
        applicationFormData,
        {
          transformRequest: () => applicationFormData,
           **onUploadProgress: () => null,**
        }
      );
     ``

**Comment by Enliven26** [comment] 2023-08-20 09:48
For anyone using nextjs 13 beta, axios 1.4.0

CLIENT:
`axios.post(url, formData);`

SERVER:
`await request.formData();`

**Comment by Enliven26** [comment] 2023-08-20 09:50
> I am using Axios 1.4 (also tried with 1.3.4) and the work around still does not work for me:
> 
> If I look at the actual request payload it still just sends the string "[object Object]" instead of the actual data... help...
> 
> ```
> axios.post(
>         `/url`,
>         applicationFormData,
>         {
>           transformRequest: () => applicationFormData,
>         }
>       );
>       
> ```

convert the data into string (for example using JSON.stringify()) or blob before appending to formdata object

**Comment by kocyigityunus** [comment] 2023-08-20 09:51
@Enliven26 make sure to be using the right request headers

**Comment by myrs** [comment] 2023-09-13 09:42
I just switched from `0.24` to `1.5.0`, and it works for me! I'm also stringifying data before appending it to form, i.e.

```
// payload = <some object>
const formData = new FormData();
formData.append('key', JSON.stringify(payload));
axios.post(url, formData);
```

**Comment by artyorsh** [comment] 2023-11-10 12:02
It seems the https://github.com/axios/axios/pull/6056 breaks the `transformRequest` hotfix

**Comment by artyorsh** [comment] 2023-11-10 12:02
It seems the https://github.com/axios/axios/pull/6056 breaks the `transformRequest` patch

**Comment by piers-smartwyre** [comment] 2023-11-24 11:28
We still require the `transformRequest: () => formData` workaround in `1.6.1`.

**Comment by SirWernich** [comment] 2024-06-04 03:26
> We still require the `transformRequest: () => formData` workaround in `1.6.2`.

this also works in `1.6.7`.

for quite some time i tried using our axios wrapper class, axios directly and fetch to upload a file to a dotnet backend and only the fetch was working even though i was not doing or setting any specific things. tried the `transformRequest` tweak and it worked first time.

**Comment by gregfenton** [comment] 2024-11-02 23:13
> Hi Guys, I tried all the solutions that were added in this discussion, but I still find myself having problems, Axios shows error 404

If you are getting a 404 response, that means the URL you are trying to make a request to does not exist.

Your code `api.post('/MissingPersonReport/findFace', ...)` is going to a server, and that server is replying that the request you are making has no endpoint configured (it is "404 - NOT FOUND").

So check your server logs to see what is happening.  Check your configuration of `api` to validate the host and port of the API server.

Your code is attempting to call:

```
https://api-abcd-prd.azurewebsites.net//MissingPersonReport/findFace
```

Is that the URL you expect it to be?

I also see in your JS console output:

![image](https://github.com/user-attachments/assets/65d5689d-d217-4078-827d-12cb870f6d28)

So maybe you don't have your `api` configured correctly?  Why is `192.168.15.101:8081` showing up?

**Comment by gregfenton** [comment] 2024-11-03 21:51
@bot-leo Is the backend API actually returning a 404?

If so, what URL is the client attempting to fetch that it is 404?  Why would one client get 404 when another gets a valid response (200)?

The response is not a client/react-native/axios thing.  It is the server's response to a client request.  So at the server end, what is different between the RN/axios request and other clients that do not get a 404?

**Comment by dan-pugsley** [comment] 2025-03-05 16:59
For anyone still struggling with this, the latest axios version has a `postForm` function ([docs](https://axios-http.com/docs/multipart)), which solved the problem for me.

**Comment by erbaafidotama** [comment] 2025-03-06 07:48
> For anyone still struggling with this, the latest axios version has a `postForm` function ([docs](https://axios-http.com/docs/multipart)), which solved the problem for me.

Thanks @dan-pugsley

**Comment by kbruccoleri** [comment] 2025-04-01 18:14
https://github.com/axios/axios/blob/d1178cad4c4fe21be3d36a5a89c1590f474b4d89/lib/defaults/index.js#L44-L54

We had set `axios.defaults.headers.common['Content-Type'] = 'application/json';`

This will override the guessing behavior - it will take your FormData and JSON.stringify it to match your default.

In older versions, Axios would guess despite the set content type.

**Comment by rohit9625** [comment] 2025-07-16 14:24
Thanks @dan-pugsley, I can confirm that using the postForm api worked for me.
