### ISSUE TITLE
Axios @1.2.0 brakes on 128 byte text file

### ISSUE THREAD

**Issue by ghost** [axios/axios#5319] opened 2022-11-28 20:07 UTC
### Describe the bug

In axios@1.2.0 - When the text file size is greater than 127 bytes it returns something like `"\u001f�\b\u0000\u0000..."` but in previous version (tested in 1.1.3) it is returning correct text string.

||Version|File size|Response|
|-|-|-|-|
|✅|1.1.3|127 B|`"aaaaaaaaaaaaaaaaaaaaaaaaaaaa..."`|
|✅|1.2.0|127 B|`"aaaaaaaaaaaaaaaaaaaaaaaaaaaa..."`|
|✅|1.1.3|128 B|`"aaaaaaaaaaaaaaaaaaaaaaaaaaaa..."`|
|❌|1.2.0|128 B|`"\u001f�\b\u0000\u0000\u0000..."`|

### To Reproduce

https://runkit.com/avaogntheme/5fc9c5e149e735001aa7fe37

### Code snippet

```js
const axios113 = require("axios@1.1.3")
const axios120 = require("axios")

const url127 = "https://meimg.b-cdn.net/text-127.txt" // 127 byte txt file
const url128 = "https://meimg.b-cdn.net/text-128.txt" // 128 byte txt file

const options = { responseType: 'text' }


console.log('------------- TESTING WITH 127 BYTES FILE -------------')

console.log('✅ Axios Version 1.1.3')
const axios_113_127b = await axios113.get(url127, options)
console.log(axios_113_127b.data)

console.log('✅ Axios Version 1.2.0')
const axios_120_127b = await axios120.get(url127, options)
console.log(axios_120_127b.data)


console.log('------------- TESTING WITH 128 BYTES FILE -------------')

console.log('✅ Axios Version 1.1.3')
const axios_113_128b = await axios113.get(url128, options)
console.log(axios_113_128b.data)

console.log('❌ Axios Version 1.2.0')
const axios_120_128b = await axios120.get(url128, options)
console.log(axios_120_128b.data)
```

### Expected behavior

Expected to return a valid string such as `"aaaaaaaaaaaaaaaaaaaaaaaaaaaa..."` 
But it returns something like `"\u001f�\b\u0000\u0000\u0000..."`

### Axios Version

`1.2.0`

### Node.js Version

`18.11.0`

**Comment by mdecurtins** [comment] 2022-11-28 21:09
We are seeing this as well.

**Comment by Tronikelis** [comment] 2022-11-29 18:18
probably duplicate of #5296

**Comment by JawadAhbab** [comment] 2022-11-30 15:05
> This is caused by https://meimg.b-cdn.net/text-127.txt having a proper `Content-Length` header of `127` and no `Content-Encoding` header set, while https://meimg.b-cdn.net/text-128.txt has no `Content-Length`, yet it has `Content-Encoding: gzip`.
> 
> Responsible piece of code:
> 
> https://github.com/axios/axios/blob/786b113a40011faaee95da0b02eaa7de06944d7a/lib/adapters/http.js#L403-L407
> 
> FWIW it's working fine on `2.x` branch -
> 
> https://github.com/axios/axios/blob/88c3bc1ca753c85759df6ad2287ceea01e09831e/lib/adapters/http.js#L314-L318

This is strange because two version of Axios is responding differently! I want to be confirm that is this intentional by Axios?

**Comment by deepak786** [comment] 2022-12-05 21:49
Use release 1.2.1

**Comment by jasonsaayman** [comment] 2022-12-06 06:38
Please try v1.2.1, if the issue persists please open and @ me

**Closed by jasonsaayman** 2022-12-06 06:38 UTC
