### ISSUE TITLE
Network Error" for valid HTTPS request on Android

### ISSUE THREAD

**Issue by NareshNama** [axios/axios#2539] opened 2019-11-11 11:28 UTC
it is not working in android (react native app)

**Comment by ngocdh383** [comment] 2019-11-12 03:32
the same problem

**Comment by rodgomesc** [comment] 2019-11-22 12:39
same problem

**Comment by NareshNama** [comment] 2019-11-26 09:21
any solution ?

**Comment by bmcn99** [comment] 2019-11-29 22:18
Just ran into this, we were using the same code pointed to few different http servers without issue. Today I pointed it at our final https location and am now getting the same generic "Network error". I read here: https://github.com/axios/axios/issues/973#issuecomment-329967881 that android https is not supported by axios but that is for the emulator only.. right? My error is on a Samsung A5 android physical device.

**Comment by chinesedfan** [comment] 2019-12-03 15:14
Duplicate of #973. Let's track in there.

**Closed by chinesedfan** 2019-12-03 15:14 UTC

**Comment by a728384698** [comment] 2019-12-13 07:16
https://www.jianshu.com/p/5d67e719606a

**Comment by a728384698** [comment] 2019-12-13 07:23
https://www.jianshu.com/p/5d67e719606a

**Comment by magic990619** [comment] 2020-04-20 06:38
same here
