### ISSUE TITLE
Request header content-type was not present in the Access-Control-Allow-Headers list.

### ISSUE THREAD

**Issue by sumitmoga** [axios/axios#2935] opened 2020-04-29 16:46 UTC
I'm getting axios post error in IE browser it working fine on other browsers. Its throw above error when i try to send post data. after comparing with chrome i found in request headers there is no content-type and Method show type OPTION . how to fix this.

**Comment by jasonsaayman** [comment] 2020-04-29 19:05
Hi,

Please could you use an issue template provided by the repository?

Thanks

**Comment by sumitmoga** [comment] 2020-04-30 07:05
@jasonsaayman , Sorry i didn't know what is missing here..and what you want to point out

**Comment by jasonsaayman** [comment] 2020-05-03 11:35
When opening a issue please use the template as follows for example a bug issue:



**Describe the bug**
A clear and concise description of what the bug is. **If your problem is not a bug, please file under Support or Usage Question**

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment:**
 - Axios Version [e.g. 0.18.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

I am closing this issue, please open a new one using one of the templates provided.

**Closed by jasonsaayman** 2020-05-03 11:35 UTC
Labels: support
