### ISSUE TITLE
Can't use a custom config property

### ISSUE THREAD

**Issue by matneves** [axios/axios#3077] opened 2020-06-29 13:44 UTC
#### Describe the bug
When using `axios.create`, if I pass a custom property it is not being visible on the interceptors.

#### To Reproduce
Something like:

```js
const instance = axios.create({
      baseURL: 'http://myurl.com',
      withCredentials: false,
      loader: true // Custom property
});

instance.interceptors.request.use(
      config => {
        console.log('request', config); // Does not show the "loader" property

        if (config.loader) {
          showLoader();
        }

        return config;
      }
);
```

#### Expected behavior
It should be available for further use on the interceptors, because the same code is working on version 0.18.1.

#### Environment
 - Axios Version: 0.19.1 and 0.19.2

#### Additional context/Screenshots
Please let me know if I'm doing this wrong, and there's a new way to do.

**Comment by vincentSea** [comment] 2020-07-01 04:31
same here...

**Comment by chinesedfan** [comment] 2020-07-11 04:50
Duplicate of #2587 and see https://github.com/axios/axios/issues/3009#issuecomment-649503739.

**Closed by chinesedfan** 2020-07-11 04:50 UTC
Labels: status:possible bug
