### ISSUE TITLE
302 code catch error with error.response undefined

### ISSUE THREAD

**Issue by picbenoit** [axios/axios#1303] opened 2018-01-19 15:08 UTC
Hello,

I'm using axios 0.17.1.

When I send a request to my API with axios and that my server returns a 302 status code (redirection), the error.response object is undifined on catch function. The error object I have when a 302 request is send :

![image](https://user-images.githubusercontent.com/22802680/35156888-86c76f24-fd32-11e7-90fa-f092c8582aa3.png)

My server is working properly and returning code 302, I can see it in firefox console. I also tried the request on postman.

Is anyone can help me ?

Thank you,

Ben.

**Comment by emilyemorehouse** [comment] 2018-01-19 15:43
Hi Ben,

Can you post a snippet of your Axios request code (feel free to redact or hide any sensitive URLs) so we can see how you're making the request?

**Comment by picbenoit** [comment] 2018-01-22 09:10
Hi emilyemorehouse,

```
api.get('/user', {
    params: {
        include: 'profile,studies,studies.feedbackForms,studies.feedbackForms.alerts,studies.structures,permissions,structures,feedbackForms'
    }
}).then((response) => {
    commit('changeUser', response.data.data); // On commit l'action
    dispatch('switchStudy', state.user.studies.data[0]); // L'édutes utilisées par défaut
    dispatch('switchLang', state.user.profile.data.language !== null ? state.user.profile.data.language : state.currentStudy.language); // On demande à changer de lang
    router.replace(nextRoute); // On passe à la page suivante
}).catch((error) => {
    console.log(error);
});
```

When I use another route ('/users/myself') which doing the same as '/user' whitout 302 redirection, call is working well.

api variable is build like that : 

```
var instance = axios.create({
    baseURL: process.env.API_BASEURL,
    timeout: 5000,
});

if (LocalStorage.has('tokens')) {
    instance.defaults.headers.common['Authorization'] = "Bearer " + LocalStorage.get.item('tokens').access_token;
}

export default instance;
```

Thank you for your help,

Ben

**Comment by picbenoit** [comment] 2018-01-26 08:31
no one reproduces this error with a request that returns 302 status code ?

for the moment I use a new route that doing the same job as the redirect one.

**Comment by audrium** [comment] 2018-01-29 07:55
Same problem here. Error response object is undefined on 302 status code

**Comment by michaeldzjap** [comment] 2018-01-29 09:37
#1153 Seems to be related, if not exactly the same issue,

**Comment by Khaledgarbaya** [comment] 2018-01-30 12:12
Possible duplicate of https://github.com/axios/axios/issues/1153

**Closed by Khaledgarbaya** 2018-01-30 12:12 UTC

**Comment by picbenoit** [comment] 2018-01-30 16:40
@Khaledgarbaya maybe but for me, the problem is on FF

**Comment by audrium** [comment] 2018-02-20 13:05
Are you planning to fix this?

**Comment by franklixuefei** [comment] 2018-05-03 00:52
Please fix this.

**Comment by tgdn** [comment] 2020-04-03 09:21
Any news on this?
