### ISSUE TITLE
FormData appears to be handled differently/incorrectly in 0.27

### ISSUE THREAD

**Issue by dwightwatson** [axios/axios#4643] opened 2022-04-27 00:30 UTC
#### Describe the bug
Form uploads appear to have broken between v0.26 and v0.27. Requests that used to work without issue no longer work.

Here is sample code that accepts a file and attempts to upload it to Cloudinary using form data.

```js
export const upload = (file) => {
  const formData = new FormData();
  formData.set("file", file);
  formData.set("upload_preset", CLOUDINARY_UPLOAD_PRESET);

  return axios.post(
    `https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD}/upload`,
    formData
  );
};
```

Inspecting the v0.26 request in with Chrome shows that it at least understands the content provided:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/1100408/165413540-02c0e2bb-9676-448b-9a57-06c88a32a8c6.png">

Inspecting the v0.27 request in Chrome it appears to show more raw data - as if the form data wasn't handled correctly and is corrupted.
<img width="543" alt="image" src="https://user-images.githubusercontent.com/1100408/165413575-04b53606-bb97-4c70-95f7-8618c8ef4087.png">

I've attempted to use the alternate FormData syntax for v0.27 as suggested in the documentation but I have the same issue.

```js
export const upload = (file) => {
  return axios.post(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD}/upload`, {
    file: file,
    upload_preset: CLOUDINARY_UPLOAD_PRESET
  }, {
    headers: {
      "Content-Type": "multipart/form-data"
    }
  });
};
```

#### To Reproduce
I couldn't get this running on RunKit because it's a Node environment, where my issue is in the browser using the native FormData vs the `form-data` npm package. However, the code below can be used (making a dummy request to `/api`) that would demonstrate the difference in request handing between the two affected versions.

```js
export const upload = (file) => {
  const formData = new FormData();
  formData.set("file", file);
  formData.set("additional_parameter", "additional_parameter");

  return axios.post("/api", formData);
};
```

#### Expected behavior
I would have expected the request with form data that worked in v0.26 to continue to work in v0.27 without issue.

#### Environment
 - Axios Version 0.27
 - Browser: Chrome
 - Browser Version: 100
 - Node.js Version: 18.0.0
 - OS: maxOS 12.3.1

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Yusoo** [comment] 2022-04-27 02:03
I had the same problem

**Comment by GuoSirius** [comment] 2022-04-27 02:05
![image](https://user-images.githubusercontent.com/48358523/165423749-eb64f871-a34e-49b6-9f7a-36a775505e05.png)
 
this is needed!

**Comment by philBrown** [comment] 2022-04-27 04:07
Duplicate of https://github.com/axios/axios/issues/4631

**Comment by jasonsaayman** [comment] 2022-04-27 09:24
Fixing this in 0.27.2

**Closed by jasonsaayman** 2022-04-27 09:24 UTC
Labels: status:possible bug
