### ISSUE TITLE
About array type merge in params

### ISSUE THREAD

**Issue by llwwbb** [axios/axios#2945] opened 2020-05-05 03:17 UTC
https://github.com/axios/axios/blob/16b5718954d88fbefe17f0b91101d742b63209c7/lib/core/mergeConfig.js#L19

keys in mergeDeepPropertiesKeys will be merged by utils.deepMerge but utils.deepMerge can only merge objects. Array type field will be converted like {‘0’: 'a', '1': 'b'}, no longer an array.

**Comment by jasonsaayman** [comment] 2020-05-05 11:32
Hi @llambda 

Please can you fill out the issue template when creating an issue?

Thanks

**Comment by llwwbb** [comment] 2020-05-06 04:15
@jasonsaayman Ok I describe it in detail

**Describe the bug**
In the latest master branch, If params contains array type fields, it will be coverted to object.

**To Reproduce**
```js
axios.get('http://www.google.com', { params: { array: [0, 1, 2, 3] } });
```

**Expected behavior**
v0.19.2  'array' value in params is normal [0, 1, 2, 3]

But in master, it is {"0": 0, "1": 1, "2":2, "3":3 }, See screenshot below

**Environment:**
 - Axios Version master

**Additional context/Screenshots**
v0.19.2 <img width="469" alt="0 19 2" src="https://user-images.githubusercontent.com/7372183/81138014-1dbb4c80-8f93-11ea-9ab7-534b4ad9202e.png">
master <img width="556" alt="master" src="https://user-images.githubusercontent.com/7372183/81138020-22800080-8f93-11ea-951c-47feedd3090c.png">

**Comment by chinesedfan** [comment] 2020-05-08 03:55
Duplicate of #2567. And maybe you can try #2844.

**Closed by chinesedfan** 2020-05-08 03:55 UTC
Labels: status:more-info-needed
