### ISSUE TITLE
Am I capturing 'this' in the right way in 'then'?

### ISSUE THREAD

**Issue by j4nos** [axios/axios#2584] opened 2019-12-02 13:27 UTC
Why do I get `Network error` message?

```
axios.defaults.headers.post['Content-Type'] = 'application/json';
axios({
  method: 'post',
  url: url,
  data: pages
}).then(response => {
  this.setState({
    pages: response.data
  })
}).catch(function (error) {
  console.log(error);
});
```

**Comment by chinesedfan** [comment] 2019-12-03 09:05
Duplicate of #2583.

**Closed by chinesedfan** 2019-12-03 09:05 UTC
