### ISSUE TITLE
DELETE not sending config.data in v0.20.0

### ISSUE THREAD

**Issue by tamsler** [axios/axios#3249] opened 2020-09-01 22:17 UTC
#### Describe the bug
When using axios.delete and sending config.data, the server receives no body

#### To Reproduce
Make a call using axios delete and send data via the config object. This used to work in v0.19.2 but doesn't work in v0.20.0 anymore.

```js
axios.delete(BASE_URL + '/user', {
    headers: {
        Authorization: this.authToken
    },
    data: {'userId':'abcd1234'}
})
```

#### Expected behavior
Server should receive data-> body

#### Environment
 - Axios Version [0.20.0]
 - Node.js Version [12.18.3]

#### Additional context/Screenshots
using v0.19.2 server gets:
'body': '{"userId":"abcd1234"}'

using v0.20.0 server gets:
'body': None

**Comment by DRoet** [comment] 2020-09-02 07:32
duplicate of https://github.com/axios/axios/issues/3220

**Comment by 14glwu** [comment] 2020-09-03 02:26
I also meet this problem

**Comment by denis-gorin** [comment] 2020-09-03 09:35
quick workaround

```
axios({
    method: 'delete', 
    url :BASE_URL + '/user', 
    headers: {Authorization: this.authToken},
    data: {'userId':'abcd1234'}
})
```

**Comment by chinesedfan** [comment] 2020-09-03 15:35
Duplicate of #3220. Sorry for the breaking.

**Closed by chinesedfan** 2020-09-03 15:35 UTC
Labels: status:possible bug

**Comment by jasonsaayman** [comment] 2020-10-23 16:41
Hi,

Axios version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks
