### ISSUE TITLE
Axios 1.2.2 release?

### ISSUE THREAD

**Issue by LoiLock** [axios/axios#5400] opened 2022-12-21 08:25 UTC
### Describe the issue

From what I can gather, v1.2.2 includes various fixes for things like brotli and gzip, these have been fixed for several weeks now. Are there any plans to release these fixes to npm soon?

**Comment by tada5hi** [comment] 2022-12-22 18:36
@jasonsaayman it would be great if you could comment briefly on this

**Comment by sshehab1** [comment] 2022-12-28 08:56
@DigitalBrainJS can you comment on this? 1.2.1 is still causing issues

**Comment by DigitalBrainJS** [comment] 2022-12-28 22:14
@sshehab1 Yes, I'm aware of this. The issue is fixed in the repository, an npm release is required, but I can't do it, since I'm not a collaborator there.

**Comment by jasonsaayman** [comment] 2022-12-29 06:32
Closing as this has been released

**Closed by jasonsaayman** 2022-12-29 06:32 UTC
