### ISSUE TITLE
transfer-encoding chunked not handled for application/json

### ISSUE THREAD

**Issue by DaveStein** [axios/axios#1768] opened 2018-08-29 16:09 UTC
#### Summary

I am receiving JSON via chunked encoding. `response.data` comes back as a `string`. It is not properly parsed as the headers instruct.  I would expect to get a JSON object back for `res.data`.

Response Headers:
```
Content-Type: application/json
Transfer-Encoding: chunked, chunked
```

Response Data:
```
23\r\n
{"rejected":0,"inserted/updated":1}\r\n
0\r\n
\r\n
\r\n
```

Theoretically this response would also be valid:

```
18\r\n
{"rejected":0,"inserted/update\r\n
5\r\n
d":1}\r\n
0\r\n
\r\n
\r\n
```

#### Context

- axios version: *e.g.: 0.18.0*
- Environment: *e.g.: node v8.10.0, High Sierra*

**Comment by OpenGG** [comment] 2018-08-30 14:34
Need online demo.

**Comment by DaveStein** [comment] 2018-08-30 15:26
@OpenGG Hm I am not sure how to go about doing that, given that this API is not mine and I don't have a random server to generate an endpoint to give back this value. The API I am using is an authenticated one and I can't put an API key in a test script. Any suggestions?

**Comment by RikkiGibson** [comment] 2018-09-01 20:43
So response.data comes back as a string of the chunked-encoded data? That's really weird.

**Comment by RikkiGibson** [comment] 2018-09-01 20:54
I just played with one of the axios unit tests to explore this and found that:
- The test passed with `Transfer-Encoding: chunked`
- The test showed the same bad behavior as in @DaveStein's description with  `Transfer-Encoding: chunked, chunked`

I think this is an issue with the underlying transport (i.e. the nodejs built-in http module)

**Comment by DaveStein** [comment] 2018-09-13 14:51
I believe `chunked, chunked` might be a bug on external API. I am reporting this to them. At least if my coworkers read https://tools.ietf.org/html/rfc7230#section-3.3.1 correctly.

**Comment by Marcholio** [comment] 2019-02-13 18:31
Can you verify whether this is still an issue?

**Comment by DaveStein** [comment] 2019-02-13 18:44
Gonna have someone check in a bit. Our current hack is below. We'll just always return `res.data` and see what happens :) But like I said above, not sure that `chunked, chunked` is valid.

```
function getData(res) {
  const transferEncoding = res.headers['transfer-encoding'];
  if (!transferEncoding || transferEncoding !== 'chunked, chunked') {
    return res.data;
  }

  const splitString = res.data.split('\r\n');
  return JSON.parse(splitString[1]);
}
```

**Comment by DaveStein** [comment] 2019-02-13 19:43
My coworker said this is fixed `v0.19.0-beta.1`

**Comment by DaveStein** [comment] 2019-02-13 21:34
Oops, sorry. Mistaken. Still broken in beta.

**Comment by danny-waite** [comment] 2019-09-18 22:21
I have a similar/same issue.

a GET request to `https://wpdemo.gatsbycentral.com/wp-json` `result.data` is an object
but with a request to https://engineersf.com/wp-json `result.data` is a `string`

both servers return different headers and have different content lengths

**Comment by etino** [comment] 2020-02-17 13:58
I have the same issue.

The server response set Transfer-Encoding= chunked.

When I try to parse JSON I get the following error:

`(node:14940) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token F in JSON at position 1`

The response data begins and ends with unattended characters as follow:
```
7F5
{
  "message": "OK"
  ....
}
0
```

The string is not parsable by `JSON.parse()` function.

The test is made with the latest master branch commit.

Is available a beta version that solves this problem?

**Comment by etino** [comment] 2020-02-18 07:15
I've used regex to make a workaround to this issue.

```javascript
const chunksParser = body => {
  return body
    .replace(/^(\w{1,3})\r\n/, "") // remove initial chunks info
    .replace(/\r\n(\w{1,3})\r\n/, "") // remove in-body chunks info
    .replace(/(\r\n0\r\n\r\n)$/, ""); // remove end chunks info
};
```

The details are in [this StackOverflow post](https://stackoverflow.com/a/60275498/1891624)

**Comment by DaveStein** [comment] 2020-02-18 15:04
I had only ever left the fix in that I posted above.

**Comment by jasonsaayman** [comment] 2020-07-01 17:10
Closed, merged in #2419

**Closed by jasonsaayman** 2020-07-01 17:10 UTC
Labels: component:headers

**Comment by sroettering** [comment] 2022-11-23 09:21
Hi, there seems to be a regression on this topic with the new 1.2.0 version. In version 1.1.3 this was still fixed but now it is broken again.

**Comment by timothee-alby** [comment] 2022-11-23 16:54
Hello, I'm seeing this as well: chunked responses ara not handled well (getting gibberish string in `response.data` instead of the JSON object). Reverting to `1.1.3` fixes that.

**Comment by spyndutz** [comment] 2022-11-24 00:07
I experienced the exact same issue processing the response `transfer-encoding: chunked`. Currently reverting to `1.1.3` to avoid this issue.

**Comment by eleven-net-cn** [comment] 2022-11-24 04:19
The same exception about `transfer-encoding: chunked` with axios@1.2.0, and revert to v1.1.3 will work fine.

**Comment by fahmidme** [comment] 2022-11-27 02:05
I was facing the same issue and reverting to `v1.1.3` worked.

Note that I had to `npm uninstall` first then `npm install axios@1.1.3`.

Thanks to above answers

**Comment by khadirbaaoua** [comment] 2022-11-28 10:19
Same here, reverting from 1.2.0 to 1.1.3 fixed it.

**Comment by HTM-Joaquim** [comment] 2022-11-29 18:09
I think its worth mentioning that even downgrading to 1.1.3, if you have the option `decompress: false` it will still not work.

**Comment by ajacksified** [comment] 2022-12-04 13:38
Can confirm, just downgraded to 1.1.3 to fix this issue.

**Comment by maxscott** [comment] 2022-12-05 00:18
Experiencing this with chunked `text/html` also, and resolved by downgrading to 1.1.3. So the issue doesn't seem confined to `application/json`.

**Comment by scrummitch** [comment] 2022-12-13 21:29
Similar issue. Downgraded from 1.2.1 to 1.2.0 to fix the brotli encoding issue, then had the same issue using cloudflare which seemed to chunk my json responses

**Comment by noontz** [comment] 2023-01-19 15:46
Can confirm downgrading to 1.1.3 from 1.2.0 fixed this issue reading responses in node from requests to azure functions

**Comment by ilonachan** [comment] 2025-04-04 11:37
The currently latest version 1.8.3 STILL has this problem. In my case it's not just the chunked body, but also the HTTP header that's simply dumped into the data field. This issue should not be closed.
