### ISSUE TITLE
Property 'crossDomain' does not exist on type 'AxiosRequestConfig'. TS (2339)

### ISSUE THREAD

**Issue by DemoHu** [axios/axios#2369] opened 2019-08-22 03:14 UTC
"axios": "^0.19.0"
```
import axios, { AxiosRequestConfig } from 'axios'

axios.defaults.crossDomain = true  //Property 'crossDomain' does not exist on type 'AxiosRequestConfig'. TS (2339)
```

```
export interface AxiosRequestConfig {
  url?: string;
  method?: Method;
  baseURL?: string;
  transformRequest?: AxiosTransformer | AxiosTransformer[];
  transformResponse?: AxiosTransformer | AxiosTransformer[];
  headers?: any;
  params?: any;
  paramsSerializer?: (params: any) => string;
  data?: any;
  timeout?: number;
  withCredentials?: boolean;
  adapter?: AxiosAdapter;
  auth?: AxiosBasicCredentials;
  responseType?: ResponseType;
  xsrfCookieName?: string;
  xsrfHeaderName?: string;
  onUploadProgress?: (progressEvent: any) => void;
  onDownloadProgress?: (progressEvent: any) => void;
  maxContentLength?: number;
  validateStatus?: (status: number) => boolean;
  maxRedirects?: number;
  socketPath?: string | null;
  httpAgent?: any;
  httpsAgent?: any;
  proxy?: AxiosProxyConfig | false;
  cancelToken?: CancelToken;
}
``` 

**There is no “crossDomain” in interface**

**Comment by mazerab** [comment] 2019-10-16 20:15
Hello, are there any plans to fix this simple issue soon, and is there a workaround available I could try? Thank you.

**Comment by chinesedfan** [comment] 2020-03-29 10:08
Duplicate of #1963.

**Closed by chinesedfan** 2020-03-29 10:08 UTC
Labels: feature:typescript
