### ISSUE TITLE
Unable to POST data in axios

### ISSUE THREAD

**Issue by awais-ilyas** [axios/axios#1195] opened 2017-11-21 14:42 UTC
I am using this code to POST the data to Web API
var param = {
                args: {
                    myStringVal: '979251e4-6c9f-460d-ba32-1b6fe58ce8a3'
                }
            };

axios({
                method: 'post',
                url: 'api/Application/Action/MyWebAPIMethod',
                data: JSON.stringify(param),
            });

and my Web API code is like this:
public class MyClassVM 
        {
            public string myStringVal { get; set; }
        }
 public MessageVM<SupervisorUserEntity> MyWebAPIMethod(MyClassVM args){
 // my code goes here
}

Issue is: When I pass the myStringVal: '979251e4-6c9f-460d-ba32-1b6fe58ce8a3' it gives me null in Web API [args.myStringVal  = null ].

How can I pass the values in axios POST.

Thanks in advance

**Comment by at88mph** [comment] 2017-11-21 23:46
@awais-ilyas , I don't think you would normally stringify the POST payload.  Try this:

**Comment by dlgoodchild** [comment] 2017-11-26 16:38
I've recently started moving from using jQuery for AJAX work to Axios, just because it seems to be all the rage. But I was shocked to learn I can't do a simple POST.

So, here's what I first tried:
```
axios.post('/api/event/item', {
    event_id: eventId,
    item_id: itemId,
    description: description
  })
  .catch(function (error) {
    console.log(error);
  });
```
On the backend (using PHP) $_POST was completely empty. So I did some googling, and this works (with the use of a polyfill, sigh):

```
const params = new URLSearchParams();
params.append('event_id', eventId);
params.append('item_id', itemId);
params.append('description', description);
axios({
  method: 'post',
  url: '/api/event/item',
  data: params
});
```

This works. So I need to use `URLSearchParams`? Well this was frustrating because the docs show that the first method should work.

Anyone else having this trouble?

**Comment by at88mph** [comment] 2017-11-27 04:50
@dlgoodchild Are you trying to send it as Form data?  I found my POST body was empty too, but I had to use this to transform it into something Form-like:
```
   ...
      data: params,
      transformRequest: [
        function(data, headers) {
          const serializedData = []

          for (const k in data) {
            if (data[k]) {
              serializedData.push(`${k}=${encodeURIComponent(data[k])}`)
            }
          }

          return serializedData.join('&')
        }
      ],
   ...
```

Agreed, the POST functionality needs work.

**Comment by dlgoodchild** [comment] 2017-11-27 10:23
Ahh good approach! For the benefits of anyone landing here, in the end I got it working using in 3 variants:
1. FormData
2. URLSearchParams
3. querystring.stringify (part of Node)

The problem with the first 2 options is browser compatibility (check with caniuse.com). The last is another depdendency.

I wasn't aware of the `transformRequest` option, this looks good and is a great option if you want minimise dependencies and work cross browser particularly for older versions.

I think the documentation is what makes Axios frustrating for many people. The number of StackOverflow questions relating to POST using Axios is a good indication there's a problem somewhere and general misunderstanding.

**Comment by yuri-wisestamp** [comment] 2017-11-30 11:58
Have the same problem - spent few hours on research, finally found this issue. Thoughts: POST shouldn't be complicate, and shouldn't require dependencies or extra configuration. This feels like AngularJS 1 all over again. I'll pass on using this library for now.

**Comment by yuri-wisestamp** [comment] 2017-11-30 11:59
Have the same problem - spent few hours on research, finally found this issue. Thoughts: POST shouldn't be complicate, and shouldn't require dependencies or extra configuration. This feels like AngularJS 1 all over again. I'll pass on using this library for now.

**Comment by dlgoodchild** [comment] 2017-11-30 12:01
@yuri-wisestamp couldn't agree more, it's a very odd/unusal design choice. I've mostly stopped using it now as I felt spurned by the hours I lost debugging it due to lack of good documentation to lay this out from the outset.

**Comment by Antoinebr** [comment] 2017-12-21 16:06
Post with Axios and PHP is a true nightmare ! 

I spent two hours, without getting any result...

**Comment by richgoldmd** [comment] 2018-01-09 00:42
Non-form-encoded posts do not populate $_POST in PHP. You have to read the post body:

```
$body = file_get_contents('php://input');
```
if you expect json:
```
$json=json_decode($body);
```

**Comment by Antoinebr** [comment] 2018-01-09 10:49
I fixed my issue like that : 

### Front 

✋userSearchParams() doesn't work everywhere ( https://caniuse.com/#search=URLSearchParams() ) 

```JavaScript 
        let params = new URLSearchParams();
        params.append('email', this.email );
        params.append('url', userInfo.url );
        this.$http.post(
          'http://localhost:9999/api/record.php', params
          )
        .then((response) => {
          if (response.data.message === "success" )  this.$router.push( 'thankyou' );
        })
        .catch( (error) =>   console.log(error) ) ;

``` 

### Back 

``` 

print_r( $_POST ); 

// $_POST['email'] = 'lol@google.fr'
// $_POST['url'] = 'http://google.fr'

```

**Comment by Legym** [comment] 2018-02-01 05:23
I got mine to work by installing qs.

```
          import qs from "qs";


        const params = {
            name: "User",
            startTime: "2:00PM",
            endTime: "3:00PM",
            status: "pending",
            invitation: "test",
        };

        axios.post("DOMAIN/event/new", qs.stringify(params))
            .then((response) => {
                console.log(response);
            })
            .catch((error) => {
                console.log(error);
            });
```

**Comment by ArmandoHerra** [comment] 2018-02-09 19:48
@Legym Thanks! I got mine working as well with qs.stringify! Damn I was about to stop using axios since I could not get my POST requests to work correctly!

Many thanks!

**Comment by Legym** [comment] 2018-02-12 21:53
I actually found a better solution without the need for an external library. The Post request Header is set to form. You'll need to change the header if you are sending a JSON object


```
        const params = {
            name: "User",
            startTime: "2:00PM",
            endTime: "3:00PM",
            status: "pending",
            invitation: "test",
        };

axios.post('DOMAIN/event/new', params, {
     headers: {
          'content-type': 'application/json',
     },
] })
```

**Comment by transient-ad** [comment] 2018-02-20 09:08
@Legym    Thank  you very  much!

**Comment by lerpinglemur** [comment] 2018-05-22 02:19
I really don't understand why POST doesn't work.

**Comment by hifall** [comment] 2018-05-28 04:39
The URLSearchParams approach doesn't work for Safari in macOS.

**Comment by hifall** [comment] 2018-05-28 04:42
Ridiculous how a simple POST operation can be managed to appear so thorny in a 'modern' library. Kudos!

**Comment by latanoel** [comment] 2018-06-21 15:00
Has anyone been able to POST a file and data via axios?
I'm using PHP's Laravel framework.

**Comment by dlgoodchild** [comment] 2018-06-21 19:00
@latanoil honestly, there's little to no upside to using axios. Best to stick to a simpler, better supported, better documented Ajax library. Jquery is tried and tested and works perfectly well and you'll have none of the issues found here.

**Comment by latanoel** [comment] 2018-06-22 11:54
Thanks @dlgoodchild for the advice. I have struggled with this for a couple of days now. I'll just stick to jQuery.

**Comment by HellsingMatt** [comment] 2018-07-19 09:56
axios({
  method: 'post',
  url: 'http://blahblahblah',
  params: {
    key1: value1,
    key2: value2
  }
})

work this way, use _params_, not _data_

**Comment by mallochine** [comment] 2018-07-20 12:50
@HellsingMatt ok. I'm using PHP. It looks like axios completely craps up with PHP. Are you using PHP backend?

**Comment by HellsingMatt** [comment] 2018-07-21 05:55
@mallochine never learnt PHP yet, all my backend using node.js

**Comment by richgoldmd** [comment] 2018-08-01 13:38
I'm using PHP. No issues. 
In some cases I want json (usually), so I set the header accordingly. In cases where I want $_POST populated I use a library like qs or my own smaller simpler implementation (which wouldn't handle all cases but is adequate for me) to convert to a query string.

See this SO post for an example on one such function: https://stackoverflow.com/a/1714899/6728516

This quirk of Axios has been addressed in the main documentation for a long time, though admittedly it could be a bit more descriptive.

I generally find using JSON so much more versatile that I rarely do this any longer. See my comment above for a method for retrieving the posted JSON in PHP.

**Comment by songoo** [comment] 2018-10-10 16:54
Bloody hell.

**Comment by monkeymonk** [comment] 2018-10-16 14:36
It work with me using "params", and I use PHP with this. 
Note that this is axios inside nativescript-vue 2.0.0.

@HellsingMatt Thank you!

**Comment by pratikpagade** [comment] 2018-10-29 23:12
> I got mine to work by installing qs.
> 
> ```
>           import qs from "qs";
> 
> 
>         const params = {
>             name: "User",
>             startTime: "2:00PM",
>             endTime: "3:00PM",
>             status: "pending",
>             invitation: "test",
>         };
> 
>         axios.post("DOMAIN/event/new", qs.stringify(params))
>             .then((response) => {
>                 console.log(response);
>             })
>             .catch((error) => {
>                 console.log(error);
>             });
> ```

P

**Comment by pratikpagade** [comment] 2018-10-29 23:13
Please can you post the php backend code with all cors headers and content type. I have tried both axios and fetch both  are not working.

**Comment by Daniel217D** [comment] 2018-11-10 19:17
It's seems like mistake in documentation, but should use params object, no data and it's working. I've spent 2 hours to understand it((
<pre>
axios({
  method: 'post',
  url: '/wp-admin/admin-ajax.php?action=data_fetch',
  params: {
    key: value
  }
})
</pre>

**Comment by pratikpagade** [comment] 2018-11-13 05:35
Thanks alot Daniil. I appreciate your help. Thanks for letting me know the
error.

**Comment by AndrianD** [comment] 2018-11-22 18:01
> I fixed my issue like that :
> 
> ### Front
> ✋userSearchParams() doesn't work everywhere ( https://caniuse.com/#search=URLSearchParams() )
> 
> ```js
>         let params = new URLSearchParams();
>         params.append('email', this.email );
>         params.append('url', userInfo.url );
>         this.$http.post(
>           'http://localhost:9999/api/record.php', params
>           )
>         .then((response) => {
>           if (response.data.message === "success" )  this.$router.push( 'thankyou' );
>         })
>         .catch( (error) =>   console.log(error) ) ;
> ```
> 
> ### Back
> ```
> 
> print_r( $_POST ); 
> 
> // $_POST['email'] = 'lol@google.fr'
> // $_POST['url'] = 'http://google.fr'
> ```

It help so much, thank you!

**Comment by Twinsen343** [comment] 2018-11-27 02:05
> ```
> axios({
>   method: 'post',
>   url: 'http://blahblahblah',
>   params: {
>     key1: value1,
>     key2: value2
>   }
> })
> ```
> work this way, use _params_, not _data_

works for me too thanks, much cleaner approach.

**Comment by simkessy** [comment] 2018-12-11 04:08
I have an Axios instance already created with the base url. 

I want to make a post using that instance. What's the correct setup? 

This works: 

        axios({
            method: "post",
            url: "https://slack.com/api/chat.postMessage",
            params: {
                token: this.token,
                channel: this.channel,
                text: "Testing API"
            },
            transformRequest: [
                (data, headers) => {
                    console.log("data-in-transform", data);
                    delete headers.post["Content-Type"];
                    return data;
                }
            ]
        });


This does not work: 

```
    ax = axios.create({
        baseURL: `https://slack.com/api/`,
        params: {
            token: this.token,
            channel: this.channel
        },
        withCredentials: false,
        transformRequest: [
            (data, headers) => {
                delete headers.post["Content-Type"];
                return data;
            }
        ]
    });
        this.ax.post("chat.postMessage", {
            withCredentials: false,
            params: {
                text: "Testing API"
            },
            transformRequest: [
                (data, headers) => {
                    console.log("data-in-transform", data);
                    delete headers.post["Content-Type"];
                    return data;
                }
            ]
        });
```

**Comment by brij-dev** [comment] 2019-03-17 09:11
I spent 15 days to solve this issue :( Here is the Code

     Axios({

            method: apiMethod,
            url: root_url, // Api URL
            data: (apiMethod === 'POST')? Qs.stringify(apiParams) : undefined, // API post parameters,
            params:(apiMethod === 'get')? apiParams : undefined, //API get params
			headers:{
              'Accept': 'application/json',
              'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
            },

        }).then(function (response) { // On Success
            console.log('Response', response.data );

            successCallback(response.status, response.data);
        })
        .catch(function (error) { // On Failure
            console.log('error', error);

            errorCallback(error.status, error.data);
        })
        .then(function () { // Always
            alwaysCallback(false);
        });

**Comment by emfluenceindia** [comment] 2019-05-30 10:17
That's simply horrible. Such a long discussion for just sending a POST request and at the end we have no concrete solution yet.

I am facing the same issue and already spent 3 days. Tried all combinations and options possible and still finding myself at the same situation. Hence my backend is also written in PHP, I too feel that `axios` has major issues with POST and PHP combination, which is simply unaccepted!!

jQuery handles these things exceptionally well and I am going to switch back to it again. I don't want to install additional dependencies just for sending a POST request!

Also, the thread is **closed** without a proper solution!!

**Comment by dlgoodchild** [comment] 2019-05-30 11:22
It was closed by @awais-ilyas, he should ideally reopen it, if that's possible.

**Comment by emfluenceindia** [comment] 2019-05-30 11:24
Yeah! But the thread does not take me anywhere. Sending a POST request to PHP using JSON object is still been a pain! @dlgoodchild is there any workaround yet since I am a late comer to this thread?

**Comment by dlgoodchild** [comment] 2019-05-30 11:40
yeah @emfluenceindia there are plenty of workarounds mentioned in this thread that don't require using JSON.

**Comment by emfluenceindia** [comment] 2019-05-30 11:43
I saw them. Does this mean it is still not possible to POST as JSON?

**Comment by dlgoodchild** [comment] 2019-05-30 12:11
This thread isn't really about posting JSON. Posting JSON as a post body isn't an issue, this thread is about using the data: attribute, like with jQuery and having that somehow populate $_POST in PHP.

**Comment by nightmareT** [comment] 2019-07-16 12:16
> I've recently started moving from using jQuery for AJAX work to Axios, just because it seems to be all the rage. But I was shocked to learn I can't do a simple POST.
> 
> So, here's what I first tried:
> 
> ```
> axios.post('/api/event/item', {
>     event_id: eventId,
>     item_id: itemId,
>     description: description
>   })
>   .catch(function (error) {
>     console.log(error);
>   });
> ```
> 
> On the backend (using PHP) $_POST was completely empty. So I did some googling, and this works (with the use of a polyfill, sigh):
> 
> ```
> const params = new URLSearchParams();
> params.append('event_id', eventId);
> params.append('item_id', itemId);
> params.append('description', description);
> axios({
>   method: 'post',
>   url: '/api/event/item',
>   data: params
> });
> ```
> 
> This works. So I need to use `URLSearchParams`? Well this was frustrating because the docs show that the first method should work.
> 
> Anyone else having this trouble?

I met this problem today and i have spent nearly a whole day on this. it`s weird because the document of axios told me to use first method which didn`t work. thank u, bro

**Comment by stefkwan** [comment] 2019-07-23 06:35
did you guys put 
app.use(express.json())
at the app.js?

**Comment by jonataswalker** [comment] 2019-08-05 22:37
This should be enough:

```javascript
const formData = new FormData();
formData.append('action', 'some-action');
formData.append('page', 1);

axios
  .post('/async/index.php', formData, {
    retry: 3,
    retryDelay: 100,
  })
  .then(res => {
    console.log('get', res.data);
  })
  .catch(console.log);
```

PHP

```php
print_r($_POST);
```

**Comment by woodpav** [comment] 2019-08-31 18:08
The answer is to add the following. Axios uses url-form-encoded by default.

    headers: {
      "Content-Type": "text/plain"
    }

**Comment by NathanielRN** [comment] 2019-09-16 23:53
None of these solutions worked for me, and I think it's because for node.js users the README is misleading because you _must have a data object_ for post requests because the config object is the _3rd argument_ passed in. The `.post` function has this interface

```post(url: string, data?: any, config?: AxiosRequestConfig): AxiosPromise;```

so you must call the `.post` function like this

```
await axios.post(
        `http://localhost:3000/your/path/here`,
        {},
        {
          params: {
            ID: 12345,
            name: 'testUser',
          },
        },
      );
```

**Comment by nicolardi** [comment] 2019-09-26 22:21
@NathanielRN  this solution works but it's not optimal. It appends all the parameters to the url. Similar to the "get".

**Comment by NathanielRN** [comment] 2019-09-26 22:25
> @NathanielRN this solution works but it's not optimal. It appends all the parameters to the url. Similar to the "get".

@nicolardi Sorry I'm not too familiar with url request performance. While is adding the parameters to the url not optimal? Even if it is like a "get"?

**Comment by stoplion** [comment] 2019-11-05 21:25
This is not a good solution.

**Comment by yasuf** [comment] 2019-11-05 23:00
Reopening for investigation

**Comment by luizrobertomeier** [comment] 2019-12-05 06:30
Here is the thing: the problem isn't with Axios. If you use cURL or Postman with the same parameters (method: Post, Body: {"something":"value"}, headers set to json) it works. However, if you do it using Axios or even Fetch API in your Vue, React, Angular (whatever) you'll see your Chrome or (any other browser) "changing" the Request Method (see the Network tab) to OPTIONS and NOT POST anymore. The reason behind it is... CORS (Cross-origin resource sharing). I found it out because I'm making my API using NestJS and I forgot to enable CORS. When enabled, the Request Method is set to POST (as we wished) and Axios will be able to return your JSON (or any other format). Some frameworks set the CORS automattically (e.g. Laravel) where others you must set/enable it manually.

**Comment by latanoel** [comment] 2019-12-05 08:20
> This should be enough:
> 
> ```js
> const formData = new FormData();
> formData.append('action', 'some-action');
> formData.append('page', 1);
> 
> axios
>   .post('/async/index.php', formData, {
>     retry: 3,
>     retryDelay: 100,
>   })
>   .then(res => {
>     console.log('get', res.data);
>   })
>   .catch(console.log);
> ```
> 
> PHP
> 
> ```
> print_r($_POST);
> ```

solution by @jonataswalker is the best approach to handle POST using Axios. Using FormData() worked for me.

**Comment by 1shaked** [comment] 2019-12-21 11:43
so i have kind of the same problome. i am using Vue.js for my front and i found out the since i did the update to the last version (axios , and vue) i can not send the data in any way. in my last project i could send data in any of the format.
##In older versions working fine and in the updated not working at all.

`axios.post('/actions/posts/create_questionnaire' , { questionnaire : form })`

my advise if the post does not work try to use a older version of axios and the freamwork you are using.

**Comment by jsseidel** [comment] 2019-12-27 20:28
I ran into this problem with a django backend. Fortunately I have a workaround using GET but axios.post definitely doesn't work as documented.

**Comment by JukkaHau** [comment] 2020-01-11 19:43
It might be that it's not axios problem but cors.
If you are posting from node server to php backend then your php script needs to have cors:

https://stackoverflow.com/a/55392661

and also not use $_POST but $data = file_get_contents('php://input');

**Comment by alvarotrigo** [comment] 2020-01-14 17:53
This seems to be working to retrieve the $_POST value in PHP:

```js

    axios.post(url, {test: 'dafasfasfa'},{
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            "Access-Control-Allow-Origin": "*"
        }
    })
```

**Comment by jsseidel** [comment] 2020-01-14 21:17
I finally got this working with a django backend (with cors installed and configured) like this, using a combination of @alvarotrigo 's and @latanoel's ideas: 

```
const formData = new FormData();
formData.append('a1', this.form.a1);
formData.append('a2', this.form.a2);
formData.append('a3', this.form.a3);

axios
  .post(url, formData, {
    headers: {
      'Content-type': 'application/x-www-form-urlencoded',
    }
  })
etc
```
When you include the POST args inline as the docs suggest, POST is empty in the backend. Also, you cannot set Access-Control-Allow-Origin because that violates cors.

**Comment by cjxonix** [comment] 2020-01-18 13:46
Also, cam across this method too
`const paramsCompose = (formData) => {
    const str = [];
    for (let p in formData) {
        str.push(encodeURIComponent(p) + '=' + encodeURIComponent(formData[p]));
    }
    const body = str.join('&');
    console.log('PARAMS ' + body);
    return body;
};`


Then you ...
`return axios.post(url,
        paramsCompose({
            image_url: image_url,
            cover_name: cover_name
        }))
        .then(res => {
            const tx = res.data;
            console.log(tx);
            return res.data
        });`

**Comment by fabriciobraga** [comment] 2020-01-23 18:52
After few days and trying all the previous options... I still have no success on solve the problem. 

What we have, in fact is:

- The Axios 'post' method doesn't work as documented;
- Execute a simple 'post' call to a REST service became a hell, using Axios;

I just can't believe it's serious... sorry but I'll be back to use another API. Goodbye Axios.

**Comment by tsega** [comment] 2020-01-27 19:11
@fabriciobraga I was trying to figure out why this was happening in my application as well. I spent the entire day scouring the Internet for the solution. However, I found out that it was a very simple issue. My user create `action` looked like this at first:

```
createUser(context, user) {
    this.$axios.$post("/api/users/", user).then(response => {
      context.dispatch("fetchUsers");
    });
 }
```
The `user` parameter there is an object containing the `email` and `password` of the new user. I tried to `console.log` the user object and it reported that the properties were undefined! 🤔 

<img width="933" alt="Screen Shot 2020-01-27 at 10 00 04 PM" src="https://user-images.githubusercontent.com/206924/73204812-bb131300-4150-11ea-893a-67faa896e2e4.png">

So I spread the user object when passing it to the **$post** method and now it works!

```
 this.$axios.$post("/api/users/", {...user})
```
In my case, the user object was being sent as empty object and my API reported it be so. If you're facing the same problem maybe you should try this.

One other possible scenario is that your data is being sent just fine but not in the format that your API is expecting (e.g. a common format for PHP scripts is form-data while most Node.js APIs expect JSON). So you need to figure this out; [see the discussions above](https://github.com/axios/axios/issues/1195#issuecomment-347021460).

**Comment by Amosss** [comment] 2020-01-28 22:47
Having the same problem apparently
`axios.post("api", { API: 1, version: "0.1b"...})....`
Results with empty API and version when reaching my Java rest server.

**Comment by chinesedfan** [comment] 2020-01-29 05:28
This is one of the most commented and opened issue. Believe me that I have read every comment in this thread. Lots of users got confused how to post data by axios. Someone gave their hits or conclusions and new users missed their directions again.

Remember that axios is only a request client. **If you didn't see the expected response, check whether things that axios sends match what the server expects.** Here are my main steps to solve post or even all axios problems. And I also hope users can open issue with following questions answered. Maybe update the issue template later.

1. Which side did you run your codes? The browser or the server side.
1. What parameters do you want to send? Should use `config.params` or `config.data`?
1. If `params`, how to encode them? Is the default `config.paramsSerializer` enough or should use a customized?
1. If `data`, did you encode them with the correct `content-type` header? Most post problems failed here.
    1. The header `application/json` requires `JSON.stringify` and the header `application/x-www-form-urlencoded` requires `qs.stringify`.
    1. The default `config.transformRequest` will set `application/x-www-form-urlencoded` for URLSearchParams, and `application/json` for Javascript objects. Please check sources codes in `lib/defaults.js` to get accurate understandings.
1. Did you meet other problems, i.e. CORS/ATS/Promises, and know how to solve them?

I know they looks like complex and I am planing to write a tutorial explains as detailed as possible. But I am not a native speaker and a little worried about my article level. Forgive me to lock it and please wait for my or someone from the community to give a well-written document. This is open source. We need everyone's contribution.

**Closed** 2020-04-24 05:59 UTC
Labels: type:documentation
