### ISSUE TITLE
seperate Axios instances are sharing data (Headers)

### ISSUE THREAD

**Issue by ThomasSmWatson** [axios/axios#1239] opened 2017-12-14 16:03 UTC
## Instructions

a simple way of creating this issue:
classA
```
const axios = require('axios')
const ClassA = class{
  constructor(){
    const mAxInst = axios.create({baseUrl: 'url1'})
    mAxInst.defaults.headers.comon['Accept'] = 'HeaderA'
  }
}

```

classB

```
const axios = require('axios')
const ClassA = class{
  constructor(){
    const mAxInst = axios.create({baseUrl: 'url2'})
    mAxInst.defaults.headers.comon['Accept'] = 'HeaderB'
  }
}

```
app.js

```
//require class A/B jazz
const mObjA = new ClassA()
const mObjB = new ClassB()
 mObjA.get() //does an axios.get
.then(data => {}) 
```
## Summary
The headder for mObjA will be HeaderB
I believe this is an issue with the call of a post/put/get/etc

## Context

- axios version: *e.g.: v^0.17.1
- Environment: *e.g.: node v6.11.4

**Comment by betalb** [comment] 2017-12-19 17:21
Not sure that this is intended behaviour to mutate internal state of axios

Instead pass additional headers when calling `mAxInst.request` if they need to be different every time.

The code that does merging of configs is not doing full clone, that's why common headers are shared

**Comment by hkan** [comment] 2017-12-20 16:58
> The code that does merging of configs is not doing full clone, that's why common headers are shared

Well, isn't that a bug? Creating an instance is all about having different configs between requests. That is why I (tried to) use instances for, at least.

**Comment by betalb** [comment] 2017-12-20 18:33
Well, mucking internal state, which is not advertised in documentation, is always a bad idea.

Considering that you can achive the same behaviour using public API, there is no point in increasing complexity of merge method used

**Comment by hkan** [comment] 2017-12-20 23:17
@betalb can you explain your comment with a sample code?

Meanwhile, I solved my issue with this workaround:

    axios.put(endpoint, input, {

        // Deleting Authorization header, because we have one as global Axios
        // config and Amazon does not play nice with it.
        transformRequest: [function (data, headers) {
            delete headers.common.Authorization
            return data
        }],
    })

**Comment by betalb** [comment] 2017-12-21 06:49
`transformRequest` is a separate story, there you can mutate headers, according to documentation.

The question to devs in this case is why transform request is called before merging headers into shallow object. This is causing issues with not cloned common and method specific headers. But this change will be breaking.

```
  // Transform request data
  config.data = transformData(
    config.data,
    config.headers,
    config.transformRequest
  );

  // Flatten headers
  config.headers = utils.merge(
    config.headers.common || {},
    config.headers[config.method] || {},
    config.headers || {}
  );
```

Also strange that you have `Authorization` in common headers, I see that only `Accept` is inside of common defaults.

**Comment by hkan** [comment] 2017-12-21 11:09
I added `Authorization` myself. Because %99 of the HTTP requests are to my server and it requires user's token. There is only one request that I send to Amazon S3 to upload images. 

BTW, this also did **not** work:

    axios.put(endpoint, input, {
        headers: {
             Authorization: null,
        }
    })

Tried `null`, `void 0`, `undefined` and empty string. None of them actually wipe the default one. Funny thing is, `Authorization: null` (actual `null`, not `'null'`) makes that header a string `'null'`. This is ultra weird. 😀

**Comment by raygesualdo** [comment] 2018-01-08 18:46
@ThomasSmWatson Setting headers per instance can (and probably should) happen when creating each instance. I've included an example below:

```javascript
import axios from 'axios'

// Using const
const axiosInstance1 = axios.create({ baseURL: 'url1', headers: { Accept: 'HeaderA' } })
const axiosInstance2 = axios.create({ baseURL: 'url1', headers: { Accept: 'HeaderB' } })
axiosInstance1.get('/')


// Using classes as before
class ClassA {
  constructor() {
    this.axiosInstance = axios.create({ baseURL: 'url1', headers: { Accept: 'HeaderA' } })
  }
}

const ClassB = class {
  constructor() {
    this.axiosInstance = axios.create({ baseUrl: 'url2', headers: { Accept: 'HeaderB' } })
  }
}

const mObjA = new ClassA()
const mObjB = new ClassB()
mObjA.axiosInstance.get('/')
```

**Comment by cassiopagnoncelli** [comment] 2018-02-05 21:28
@hkan Same problem here, global and instance headers seem quite confusing to manipulate.

I'm using `axios` for my API and using `request` as fallback to outworld calls.

**Comment by emilyemorehouse** [comment] 2018-02-20 06:57
Closing in favor of #385 - which has further discussion.
Thanks!

**Closed by emilyemorehouse** 2018-02-20 06:57 UTC
Labels: Triaged
