### ISSUE TITLE
response data contain list’s order is disorderlyd

### ISSUE THREAD

**Issue by wxy2015** [axios/axios#3964] opened 2021-08-19 07:49 UTC
#### Describe the bug
my api response a json，this json contains a list，but response.data.xx.list‘s order different from browser's network show order。this is my data，error order data key is payProjectAuditRecordInfos。
`{"code":200,"message":"OK","data":{"txcode":"16","payprocode":"8a09f94b364348d1b4ec5c5e8d455f18","projectName":"多级审核","amtFlag":"1","payamt":1,"dateflag":"1","chargeType":"0","beginDate":"2021-08-31 00:00:00","endDate":"2021-09-27 00:00:00","reviewFlag":"1","merchantName":"总商户","merchantno":"143000021","descrition":null,"imgurl":"http://192.168.102.6/file/file-service-provider/file/20210219/15/A1385365195847FD8AF0956D6D66FF5E.jpg","useFlag":"0","forceFlag":"0","reviewUserName":"shenhe2","reviewUserId":26,"reviewRoleId":7,"createTime":"2021-08-19 09:17:55","orgName":"王笑雨测试学校22222","orgId":10,"reviewStatus":"0","payWayInfos":[],"payProjectExtendInfos":[{"nodename":"SFYX","nodevalue":"Y","nodedesc":"是否允许报名(Y是，N否)"},{"nodename":"SFSH","nodevalue":"Y","nodedesc":"申请审核标识(Y需要审核，N不需要审核)"}],"payProjectAuditRecordInfos":[{"userName":"wxy1","roleName":"学校管理员","status":"1","reason":"审核通过","createtime":"2021-08-19 09:18:07"},{"userName":"shenhe2","roleName":null,"status":"0","reason":null,"createtime":null},{"userName":"sadsad","roleName":null,"status":"2","reason":null,"createtime":null}],"projectRelationResVOList":[]}}`
#### To Reproduce

```js
// Example code here
import Vue from 'vue'
import Axios from 'axios'
const service = Axios.create({
    baseURL: process.env.VUE_APP_BASE_API,
    withCredentials: true,
    timeout: 5 * 1000
})

service.interceptors.response.use(
    response => {
        console.log(response.data)
        const res = response.data
    },

)
```

#### Expected behavior
response.data's order is same as reality api resp

#### Environment
 - Axios Version [0.19.2]
 - Adapter [XHR/HTTP]
 - Browser [Chrome,]
 - Browser Version [92.0.4515.159]
 - Node.js Version [v12.16.2]
 - OS: [win10]
 - element-ui Versions [2.13.0]

#### Additional context/Screenshots
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kanatBektursyn** [comment] 2021-09-03 06:35
@jasonsaayman in `Axios.js` line: 

```javascript
  var responseInterceptorChain = [];
  this.interceptors.response.forEach(function pushResponseInterceptors(interceptor) {
    responseInterceptorChain.push(interceptor.fulfilled, interceptor.rejected);
  });
```

may be the cause of that problem?

**Comment by jasonsaayman** [comment] 2021-09-03 07:03
Yeah @kanatBektursyn that does seem to be what happens. @wxy2015 I know we don't explicitly sate this but the ordering when using an interceptor at this point is not guaranteed. If someone would like to open a pull request and see if order can be guaranteed I would for sure be up to reviewing and helping get something out.

**Comment by kanatBektursyn** [comment] 2021-09-03 09:30
@wxy2015 Could you please share more info on what is data sent by server before interception and after? `console.log` it or something?

**Comment by wxy2015** [comment] 2021-09-18 09:36
I‘m sorry。I circumvented the problem in other ways，and I can't restore the code at that time。

**Comment by kanatBektursyn** [comment] 2021-09-20 04:41
@jasonsaayman @wxy2015 Sorry I couldn't be of any help. Next time I wish we will get better results. Could we close the issue please?

**Closed** 2021-09-20 06:50 UTC
Labels: status:possible bug
