### ISSUE TITLE
cors for wikipedia API

### ISSUE THREAD

**Issue by bartoszgolebiowski** [axios/axios#2395] opened 2019-09-06 21:51 UTC
**Describe the bug**
CORS issue while using 

```
const params = 'origin=*&format=json&action=query&prop=extracts&redirects=1&explaintext=&titles=Warsaw'
const wikiAxios = axios.create({
baseURL: 'https://en.wikipedia.org/w/api.php'
})
wikiAxios.get('?${params}');
```
while using 
```
axios.get('https://en.wikipedia.org/w/api.php?${params}`) 
```
it works.

**To Reproduce**
```
const wikiAxios = axios.create({
baseURL: 'https://en.wikipedia.org/w/api.php'
})
wikiAxios.get('${params}');
axios.get('https://en.wikipedia.org/w/api.php?${params}') 
```
**Expected behavior**
Both should get data from wiki API.
**Important:**
I have checked in postman that   
https://en.wikipedia.org/w/api.php/? and  
https://en.wikipedia.org/w/api.php?  
are identical.
**Environment:**
 - Axios Version [0.19.0]
 - OS: [windows 10]
 - Browser [ Chrome, ]
 - Browser Version [e.g. 76]

**Comment by pavinduLakshan** [comment] 2019-09-07 15:42
Will this work?
```
const
params='origin=*&format=json&action=query&prop=extracts&redirects=1&explaintext=&titles=Warsaw'

const wikiAxios = axios.create({
    baseURL: 'https://en.wikipedia.org/w/api.php'
})

wikiAxios.get(`/?${params}`);
```

**Comment by pavinduLakshan** [comment] 2019-09-10 12:08
Hi..if your problem was solved or above response solved, please add a description and close the issue.

**Comment by chinesedfan** [comment] 2019-12-04 13:36
> wikiAxios.get('?${params}');

The problem is that this is not an valid `url`. axios will try to concat the parameter with the baseURL by a slash, which results in a different full url.  As this is not an issue of axios. I am going to close it.

**Closed by chinesedfan** 2019-12-04 13:36 UTC
