### ISSUE TITLE
v0.19.2 does not respect defaults.params

### ISSUE THREAD

**Issue by kurtgn** [axios/axios#2861] opened 2020-03-30 07:45 UTC
**Describe the bug**
After upgrading from v0.18.1 to v0.19.2 axios stopped respecting GET params that are set as `defaults.params` or `params` passed while creating an instance.

**To Reproduce**

```js


const newAxios = axios.create({
  baseURL: 'https://httpbin.org/get',
  params:{
    'a': 'b'
  }
});

// this request doesn't respect params set above
newAxios.get('');

// this request doesn't respect params either
newAxios.defaults.params = {'c': 'd'};
newAxios.get('');


// this is the only way to pass get params
newAxios.get('', {params: {'e': 'f'}})
```
Live example here: https://jsfiddle.net/rmjuexz8/

**Expected behavior**
All the requests from the example should have GET parameters.

**Environment:**
 - Axios Version: 0.19.2

**Comment by Juanka777** [comment] 2020-04-02 09:38
I have the same exact issue after updating to V:0.19.2. The temp solution is to revert back to 0.19.0 where the issue doesn't happen.

**Comment by chinesedfan** [comment] 2020-04-03 22:58
Duplicate of #2190. Fixed by not released yet. Sorry I don't have npm publish permissions.

**Comment by ijandc** [comment] 2020-04-14 09:59
only supports the keys below:
![image](https://user-images.githubusercontent.com/34884325/79211967-7fe3ce80-7e79-11ea-929c-ae110f2f68d5.png)

unhappy

**Comment by jasonsaayman** [comment] 2020-04-23 06:16
Hi @ijandc,

I cant seem to see or maybe it is not clear but which keys do you suggest adding to `defaultToConfig2Keys`?

Thanks

**Comment by zhangJianxing2011** [comment] 2020-06-18 03:12
in 0.19.2 ,If the second-level parameter is an array, he only returns the value of arr[0],what a fucking framework!!
expect return :
{
  "code": 200,
  "msg": "成功",
  "data": [
    {
      "id": 156,
      "name": "A",
      "is_owner": 1,
      "is_shared": 1,
      "passwords": [
        {
          "id": 344,
          "title": "ba",
          "account": "b"
        },
        {
          "id": 370,
          "title": "aaaaa",
          "account": "njksnflknsklf"
        }
      ]
    }
  ]
}

but only return :
{
  "code": 200,
  "msg": "成功",
  "data": [
    {
      "id": 156,
      "name": "A",
      "is_owner": 1,
      "is_shared": 1,
      "passwords": [
        {
          "id": 344,
          "title": "ba",
          "account": "b"
        }
      ]
    }
  ]
}
where the other params go ?

**Comment by chinesedfan** [comment] 2021-01-31 06:50
This problem should have been fixed and released. And for @ijandc, feel free to open a new issue to explain your problem.

**Closed by chinesedfan** 2021-01-31 06:50 UTC
Labels: status:review
