### ISSUE TITLE
proxy-from-env is expected to be of type CommonJS, which does not support named exports. 

### ISSUE THREAD

**Issue by pavan168** [axios/axios#5221] opened 2022-11-03 14:11 UTC
### Describe the bug

I have a NextJs app with axios version 1.1.3 and recently i've updated webpack to version 5 from version 4. 

I think with webpack 5, importing named exports from certain packages don't work. I thought it's only JSON modules. Anyhow, I picked this up from here https://webpack.js.org/blog/2020-10-10-webpack-5-release/

At the same time, this issue works fine on macOS.

### Code snippet

```js
import {getProxyForUrl} from 'proxy-from-env';
        ^^^^^^^^^^^^^^
SyntaxError: The requested module 'proxy-from-env' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'proxy-from-env';
const {getProxyForUrl} = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
file:///N:/laeb/p2/la3eb-web/node_modules/axios/lib/adapters/http.js:7
import {getProxyForUrl} from 'proxy-from-env';
        ^^^^^^^^^^^^^^
        ^^^^^^^^^^^^^
```

### Expected behavior

'proxy-from-env' package in lib/adapters/http.js should be default imported. 

### Axios Version

1.1.3

### Node.js Version

14.17

### OS

Windows 10 Pro, version 22H2

**Comment by zhouccccc** [comment] 2022-11-16 01:48
same issue!

**Comment by zhouccccc** [comment] 2022-11-16 01:57
same issue!
I found that this happens if your node version is v14, but it is normal under node version v16. I think it could be caused by axios upgrading
![image](https://user-images.githubusercontent.com/25141787/202064515-4f20fa0f-d1b4-4f38-9d5b-09541d7d58af.png)

**Comment by jmc718** [comment] 2022-11-22 00:33
Is there a fix for this?

**Comment by pavan168** [comment] 2022-11-22 15:05
Yes, I've done a fix here #5222 @jmc718 @zhouccccc but waiting for it to get approved.

**Comment by wickywills** [comment] 2023-01-05 12:45
When will the fix get approved? This is still a big issue.

**Comment by anastasialanz** [comment] 2023-01-11 22:11
I'm seeing this same issue but with an Electron build.

**Comment by monilpat** [comment] 2023-01-15 07:31
same here w/ nextjs

**Comment by sudarshan-prima** [comment] 2023-01-24 09:37
same issue in nextjs / typescript

**Comment by frontBOI** [comment] 2023-03-28 07:15
same issue here with NextJS running inside a Gitlab CI pipeline.

`error - file:///builds/user/***/frontend/node_modules/axios/lib/adapters/http.js:7
[1445](https://gitlab.com/user/***/-/jobs/4013188826#L1445)import {getProxyForUrl} from 'proxy-from-env';
[1446](https://gitlab.com/user/***/-/jobs/4013188826#L1446)        ^^^^^^^^^^^^^^
[1447](https://gitlab.com/user/***/-/jobs/4013188826#L1447)SyntaxError: The requested module 'proxy-from-env' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.`

**Comment by kratospan** [comment] 2023-08-19 06:25
same error with next@13.1.6 adn aixos@1.4.0

`import {getProxyForUrl} from 'proxy-from-env';
        ^^^^^^^^^^^^^^
SyntaxError: The requested module 'proxy-from-env' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'proxy-from-env';
const {getProxyForUrl} = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)

> Build error occurred
Error: Failed to collect page data for /
    at /mnt/www/ttmall_front_next/node_modules/next/dist/build/utils.js:963:15 {
  type: 'Error'
}`

**Comment by LaSylv** [comment] 2023-10-29 09:31
Does anyone have a workaround ?

I'm having a hard time thinking of one until this is resolved

How does it happen not more people have this issue ?

**Comment by biud436** [comment] 2023-10-31 14:47
I had the exact same error. In my case, I solved the problem by installing a new version of Node.js.

**Comment by leo1553** [comment] 2024-02-27 00:56
Same issue with a NodeJS ESM project:
- NodeJS: 14.4.0
- Axios: 1.6.7
- Typescript config:
  - target: ES2022
  - module: NodeNext
  - moduleResolution: NodeNext
  - esModuleInterop: true

**Closed** 2024-11-07 19:12 UTC
