### ISSUE TITLE
Caseless header comparison in the HTTP adapter

### ISSUE THREAD

**Issue by mastermatt** [axios/axios#2876] opened 2020-04-06 19:37 UTC
**Describe the bug**
The HTTP adapter does not use caseless comparison before overriding the `User-Agent` header or deleting the `Authorization` header.

It also overwrites any provided `Content-Length` header.

**To Reproduce**
```js
axios({
  method: 'post',
  url: 'https://postman-echo.com/post',
  auth: {
    username: 'janedoe',
    password: 's00pers3cret'
  },
  headers: {
    authorization: 'foo',
    'Content-Length': 10,
    'User-agent': 'bar'
  },
  data: {
    firstName: 'Fred',
    lastName: 'Flintstone'
  }
})  
.then(function (response) {
  console.log(response.data);
})
.catch(function (error) {
  console.log(error);
});


> { args: {},
  data: { firstName: 'Fred', lastName: 'Flintstone' },
  files: {},
  form: {},
  headers:
   { 'x-forwarded-proto': 'https',
     host: 'postman-echo.com',
     'content-length': '44',
     accept: 'application/json, text/plain, */*',
     authorization: 'foo',
     'content-type': 'application/json;charset=utf-8',
     'user-agent': 'axios/0.18.1',
     'x-forwarded-port': '443' },
  json: { firstName: 'Fred', lastName: 'Flintstone' },
  url: 'https://postman-echo.com/post' }
```

**Expected behavior**
The server should have received the following headers

```js
     'x-forwarded-proto': 'https',
     host: 'postman-echo.com',
     'content-length': '10', // not '44'
     accept: 'application/json, text/plain, */*',
     authorization: 'Basic amFuZWRvZTpzMDBwZXJzM2NyZXQ=', // not 'foo'
     'content-type': 'application/json;charset=utf-8',
     'user-agent': 'bar', // not 'axios/0.18.1'
     'x-forwarded-port': '443'
```

I have a PR ready, but saw you prefer an issue be created first.

**Comment by chinesedfan** [comment] 2020-04-07 09:08
Duplicate of #1237. And yes, please go ahead. #1291 may give you some inspirations.

**Closed by chinesedfan** 2020-04-07 09:08 UTC
