### ISSUE TITLE
The node_internals _http_client.js emit a warn

### ISSUE THREAD

**Issue by wang-ran** [axios/axios#2633] opened 2020-01-02 16:05 UTC
**Describe the bug**
 I use axios.get method with custom httpsAgent and httpAgent in node.js. The node_internals _http_client.js emit a warn when the server response http statue code 302 and headers location's protocol is different with the initiator url's protocol.

**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. **If your problem is not reproducible, please file under Support or Usage Question**

```js
// Example code here
const axios = require("axios");
const https = require("https");
const http = require("http");
const httpsAgent = new https.Agent({keepAlive: true})
const httpAgent = new http.Agent({keepAlive: true})
const url = 'https://xxxxx';
axios
  .get(url, {
    httpsAgent,
    httpAgent
  })
  .then(() => {
    console.log("success");
  })
  .catch(() => {
    console.error("error:");
  });

```
I had read the axios' code , the httpFollow and httpsFollow's options should includes customer's agent

**Expected behavior**
axios use a new agent adapter the redirect url protocol

**Environment:**
 - Axios Version: 0.19.0
 - Node Version: v12.14.0

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/12745859/71676135-5f0bd780-2dba-11ea-9689-43c701f628fa.png)

**Comment by chinesedfan** [comment] 2020-01-27 16:17
Duplicate of #1981. Can you check v0.19.1?

**Closed by chinesedfan** 2020-01-27 16:17 UTC
Labels: env:node
