### ISSUE TITLE
Data option not being set in axios.delete in v0.20

### ISSUE THREAD

**Issue by saadmanfarhad** [axios/axios#3268] opened 2020-09-09 06:12 UTC
#### Describe the bug
The data option in **axios.delete(url, {options})** api is always staying undefined, even after passing the data option with proper values.

#### To Reproduce
```js
// Example code here
const res = await axios.delete('/api/example', {data:{ id: id}});
```

#### Expected behavior
![axios_expected](https://user-images.githubusercontent.com/17143611/92560832-d7556180-f294-11ea-9599-58112f776524.png)

#### Environment
 - Axios Version [0.20.0]
 - Adapter [HTTP]
 - Browser [Chrome]
 - Browser Version [85.0.4183.83 (Official Build) (64-bit)]
 - Node.js Version [e.g. 10.19.0]
 - OS: [Linux 4.15.0-112-generic x86_64]
 - Additional Library Versions [React 16.13.1]

#### Additional context/Screenshots
But this is what I am getting:
![axios_getting](https://user-images.githubusercontent.com/17143611/92561204-93af2780-f295-11ea-9326-4f847117e359.png)

**Comment by 1inuxoid** [comment] 2020-09-09 08:24
We experience this too (Chrome 85.0.4183.83/macOS, Firefox 80.0.1 (64-bit))

**Comment by ljubomirsk** [comment] 2020-09-09 10:02
We're having this issue too.

In their CHANGELOG it says

> Small change to the data attribute doc of the config. A request body can also be set for DELETE methods but this wasn't mentioned in the documentation (it only mentioned POST, PUT and PATCH). Took my some 10-20 minutes until I realized that I don't need to manipulate the request body with transformRequest in the case of DELETE.

I'm not sure what this means since the delete method still doesn't accept 3rd parameter that would be the data.

**Comment by saadmanfarhad** [comment] 2020-09-09 10:41
> We're having this issue too.
> 
> In their CHANGELOG it says
> 
> > Small change to the data attribute doc of the config. A request body can also be set for DELETE methods but this wasn't mentioned in the documentation (it only mentioned POST, PUT and PATCH). Took my some 10-20 minutes until I realized that I don't need to manipulate the request body with transformRequest in the case of DELETE.
> 
> I'm not sure what this means since the delete method still doesn't accept 3rd parameter that would be the data.

Exactly, I also came across this CHANGELOG but couldn't figure anything out of it.

**Comment by callumcancreate** [comment] 2020-09-10 00:35
I'm having the same problem. Reverted to v0.19 in the meantime.

**Comment by chinesedfan** [comment] 2020-09-12 04:00
Duplicate of #3220. Now the temporary workaround is https://github.com/axios/axios/issues/3220#issuecomment-688566578. Sorry for the inconvenient and hope the fix can be released soon.

**Closed by chinesedfan** 2020-09-12 04:00 UTC
Labels: status:possible bug

**Comment by jasonsaayman** [comment] 2020-10-23 16:42
Hi,

Axios version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks

**Comment by rabbitao** [comment] 2020-11-13 01:59
> Hi,
> 
> Axios version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.
> 
> Thanks

version0.21.0 helpful for me.

**Comment by patkasper** [comment] 2020-11-14 21:11
0.21.0 didn't work, moving to 0.19.0 worked for me.

**Comment by foormea** [comment] 2020-11-14 21:14
0.21.0 didn't work, moving to 0.19.0 worked for me.

**Comment by pinpointpanda** [comment] 2020-12-17 21:00
Also had this problem - 0.21.0 fixed for me too. Thanks all!

**Comment by proIT324** [comment] 2021-04-12 17:31
I've upgraded Axios to v0.21.1. Finally it works perfect for me.
