### ISSUE TITLE
Can not change Contant-Type when data is FormData

### ISSUE THREAD

**Issue by TabrisK** [axios/axios#1603] opened 2018-06-13 16:04 UTC
```javascript
axios({
                method: "PUT",
                url: url,
                transformRequest: [function (data, headers) {
                    // Do whatever you want to transform the data
                    return formData;
                }],
                headers: {
                    'Content-Type': file.type
                },
                "withCredentials": false
            });
```

Launched request with Content-Type：
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryPz13ZA77aLqgPlwB

**Comment by Oceanswave** [comment] 2018-12-16 14:30
Looks like when axios detects form data in the request body, it auto-sets a multipart/form-data header, overriding the header value.

This gets tricky if you're mocking responses from the server with something like Nock, which will see a different boundary value in the response -or- needing to interact with a api that expects a multipart/related content type.

**Comment by ppozniak** [comment] 2019-02-28 14:46
I am just facing the same issue.
Have you found any way to solve this @TabrisK

**Comment by TabrisK** [comment] 2019-02-28 15:36
@ppozniak 
Unfortunately, I can't change the behavior of axios. Finally I solve the problem by using **XMLHttpRequest**.

**Comment by ppozniak** [comment] 2019-04-03 09:32
https://github.com/axios/axios/blob/283d7b306ce231f092d28e01713905e5c1600d14/lib/adapters/xhr.js#L16
This is probably the cause.

**Comment by ppozniak** [comment] 2019-04-03 15:14
One really ugly hack, without rewriting the app would be to hack object's prototype. This will make `Content-type` stay as it is.
```
transformRequest: payload => {
       // ...
        Object.setPrototypeOf(formData, null);
        return formData;
      },
```

**Comment by jasonsaayman** [comment] 2020-05-28 06:05
Fixed with #1773

**Comment by chinesedfan** [comment] 2020-06-15 07:08
@jasonsaayman I am afraid #1773 didn't solve it. Reopen for confirming.

**Comment by tymmesyde** [comment] 2020-09-05 23:30
Is there any workaround?

**Comment by Masaokb** [comment] 2020-10-25 11:00
Has this issue been solved?

In my case, using `axios.request`, `content-type` header disappeared even when I specified, but using `axios.post` didn't seem to have any problem.

**Comment by manamika** [comment] 2020-11-03 10:39
In my case, i need to override the content-type to have a version - Content-Type: multipart/form-data;version=2.0.0;boundary=B_someBoundary. Is this something that will be allowed?

**Comment by Kalinin** [comment] 2021-03-04 15:46
I have the same bug as described in issue. Still happens.

**Comment by YsBunkerchain** [comment] 2021-03-26 08:05
The Get method also not able to change the content-type when I put the data as FormData.

**Comment by shivanshr** [comment] 2021-04-08 21:27
I am not able to do so with POST(mulitpart/form-data) request, I can not set header['Content-Type'] 'mulitpart/form-data', it always changes to 'text/plain;charset=UTF-8'.
"axios": "^0.21.1",
"react-native": "0.63.4"

**Comment by norbertsongin** [comment] 2021-05-07 08:25
It's because of this part https://github.com/axios/axios/blob/master/lib/adapters/xhr.js#L18-L20
Looks like it was first reported in 2017 https://github.com/axios/axios/issues/767 but was closed without being fixed

Removing this part worked for me

**Comment by JonathanSchndr** [comment] 2021-11-12 17:30
:( same issue here in nuxt-auth with axios as dep.

**Comment by jasonsaayman** [comment] 2024-09-26 17:34
closing due to being very stale, if this is still relevant please open a new issue

**Closed by jasonsaayman** 2024-09-26 17:34 UTC
