### ISSUE TITLE
AxiosRequestConfig type is not broad enough

### ISSUE THREAD

**Issue by Mattwmaster58** [axios/axios#1858] opened 2018-10-28 18:37 UTC
#### Summary
The `AxiosRequestConfig` type is not broad enough for some use cases. For example, when using [`retry-axios`](https://github.com/JustinBeckwith/retry-axios), a custom key by the name of  `raxConfig` is set in the `AxiosRequestConfig` argument. TS will rightfully report that `raxConfig` doesn't match any type in `AxiosRequestConfig`.

#### Context

- axios version: latest
- Environment: N/A

I think the most straightforward way to fix this would be to simply add `[key: string]: any` to the `AxiosRequestConfig` interface. What are your thoughts @mzabriskie ?

**Comment by service-paradis** [comment] 2018-11-21 01:09
Same problem here using https://github.com/kuitos/axios-extensions

**Comment by chinesedfan** [comment] 2020-03-29 10:09
Duplicate of #1963.

**Closed by chinesedfan** 2020-03-29 10:09 UTC
Labels: feature:typescript
