### ISSUE TITLE
Ajax request return ERR_BAD_REQUEST Request failed width status code 400

### ISSUE THREAD

**Issue by valentin6work** [axios/axios#4648] opened 2022-04-27 10:19 UTC
#### Describe the bug
I have error ERR_BAD_REQUEST Request failed width status code 400 after send ajax post request

#### To Reproduce
WordPress 5.9.3 send any ajax request to /wp-admin/admin-ajax.php

```js
let form_data = new FormData;
form_data.append('action', 'any_action');
form_data.append('etc..','any value');

axios.post('https://myhost.com/wp-admin/admin-ajax.php', form_data)
.then(function (response)
{
	//--- 
})
.catch(function (error) {
	console.log(error);
});
```
PHP code in function.php 
```PHP
$action='any_action';
add_action("wp_ajax_nopriv_$action", "$action");
add_action("wp_ajax_$action","$action" );
function any_action)
{
	echo json_encode([
        'post'=>$_POST,
    ]);
    wp_die();
}
```

#### Expected behavior
Return result json.  Its worked until April 26th!

#### Environment
 - Axios Version [0.27.2]
 - WordPress 5.9.3

#### Additional context/Screenshots
https://prnt.sc/XI2ozoTn9Hgf

**Comment by jasonsaayman** [comment] 2022-04-27 11:54
Please check out the docs over [here](https://unpkg.com/axios/dist/axios.min.js), we have changed the way form data works.

**Comment by satanshiro** [comment] 2022-04-27 11:57
> Please check out the docs over [here](https://unpkg.com/axios/dist/axios.min.js), we have changed the way form data works.

fyi the link is for the minified dist instead of docs

**Comment by jasonsaayman** [comment] 2022-04-27 12:04
My bad [here](https://github.com/axios/axios#form-data)

**Comment by apasov** [comment] 2022-04-27 12:30
I got this 400 error with v0.27.1
After upgrading to v0.27.2 it disappeared.
Looks like it was fixed in #4640

**Comment by DigitalBrainJS** [comment] 2022-04-27 15:11
Actually, we did not change anything in working with FormData - we just added alternative shortcut methods and payload serialization to a FormData object when you set the `content-type` header to `multipart/form-data`. This is just another shorter way to submit a form without manually creating a FormData object. The old behavior should not be affected, you can still pass the FormData object manually. FormData submits fails were only due to two regression bugs in versions 0.25.0 and 0.27.0.

**Comment by anniverskehinde** [comment] 2022-04-27 18:59
🙄**I am Lerner here **

**Comment by philBrown** [comment] 2022-04-27 23:32
> regression bugs in versions 0.25.0 and 0.27.0

... and 0.27.1

**Closed** 2022-04-28 06:24 UTC
Labels: status:possible bug

**Comment by database-abstraction-jed** [comment] 2025-10-12 16:39
Nailed it https://test-suiteneglected.github.io/Y8XvbQH2mJHBHBpn7w/
