### ISSUE TITLE
Unnecessary options filtering

### ISSUE THREAD

**Issue by fengxinming** [axios/axios#2356] opened 2019-08-14 03:32 UTC
**Describe the bug**
My project is working strangely，I compare the current version with the previous one，The following code creates an BUG.

```js
// version === 0.19.0
config = mergeConfig(this.defaults, config);

// version < 0.19.0
config = utils.merge(defaults, {
    method: 'get'
  }, this.defaults, config);
```

**To Reproduce**
Custom interceptors below:

```js
const instance = axios.create({
  ...
});
instance.interceptors.request.use((opts) => {
  // `options.mask` is undefined
  if (options.mask) {
    // show mask
  }
});

// requst remote
instance( { url: '', mask: true } )
```

**Expected behavior**
customized `options` can be passed into the interceptor

**Environment:**
 - Axios Version [e.g. 0.19.0]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

**Additional context/Screenshots**

**Comment by G07cha** [comment] 2019-08-14 13:24
Duplicate of https://github.com/axios/axios/issues/2203

**Comment by jasonsaayman** [comment] 2019-09-09 19:04
@fengxinming closing this issue as it duplicates as @G07cha has mentioned.

**Closed by jasonsaayman** 2019-09-09 19:04 UTC
