### ISSUE TITLE
Axios.get is not a function

### ISSUE THREAD

**Issue by jaggi23** [axios/axios#5048] opened 2022-10-07 02:43 UTC
Hi Team, There is problem in Axios v1.1. Axios not respond with axios.get and axios.post. Please use previous version of axios for solve this problem.

**Comment by craftxbox** [comment] 2022-10-07 02:47
Duplicate of #5038

**Comment by jacobdenis** [comment] 2022-10-07 03:01
@jaggi23 use this instead as a temporary solution https://unpkg.com/axios@0.27.2/dist/axios.min.js

**Comment by jasonsaayman** [comment] 2022-10-07 09:12
Update to v1.1.1 this should slove the issue

**Closed by jasonsaayman** 2022-10-07 09:12 UTC
