### ISSUE TITLE
Axios ERR_EMPTY_RESPONSE after 2 minutes.

### ISSUE THREAD

**Issue by iraviteja** [axios/axios#1979] opened 2019-01-25 13:21 UTC
Axios shows err_empty_response at 2:01 min. I used the timeout. But it's not working.

**This is my axios code.**

export const createNetwork = networkData => dispatch => {
              axios({
                  method: "post",
                  url: "/createNetworks",
                  timeout: 1000 * 3 * 60, // Wait for 5 seconds
                  headers: {
                                  "Content-Type": "application/json"
                  },
                  data: {
                    id: 1234
                  }
                })
                  .then(res => {
                                  console.log(res.data);
                  })
                  .catch(err => {
                                  console.log(err);
                  });
              };

**server code**
`let server = app.listen(port, err => {
  if (err) throw err;
  console.log(`Server is running in port ${port}`);
});`

server.timeout = 5 * 60 * 1000;

**This is my route**

app.post("/createNetworks",(req,res)=>{
   setTimeout(function(){ res.json({status:true,message:"It's working"}) }, 3000);
})

**Comment by baranovxyz** [comment] 2019-01-28 10:06
got the same issue

**Comment by pb-expa** [comment] 2019-02-06 19:50
+1 All routes we had were working as is til just recently. It seems like we are seeing chronic and systemic issues with POST requests now with axios. POST requests that had been working before, now timeout with blank responses.

**Comment by fugasjunior** [comment] 2019-05-13 12:08
I've got the same issue. Axios gives ERR_EMPTY_RESPONSE after 2 minutes. The server seems configured correctly, as passing the query directly into browser returned the response after more than 5 minutes.

**Comment by MrPeak** [comment] 2019-06-25 11:11
Same issue.

**Comment by luxueyan** [comment] 2019-07-24 10:13
Same too! No guys have a resolution？

**Comment by chinesedfan** [comment] 2020-01-20 15:49
Duplicate of #1873.

**Closed by chinesedfan** 2020-01-20 15:49 UTC
