### ISSUE TITLE
AxiosError.from no longer exported in v1.7.8

### ISSUE THREAD

**Issue by jeramysoucy** [axios/axios#6726] opened 2024-12-03 19:15 UTC
### Describe the bug

After upgrading to 1.7.8, `AxiosError.from` was no longer defined, which is a breaking change.

From index.d.ts in v1.7.7:

```
export class AxiosError<T = unknown, D = any> extends Error {
  constructor(
      message?: string,
      code?: string,
      config?: InternalAxiosRequestConfig<D>,
      request?: any,
      response?: AxiosResponse<T, D>
  );

  config?: InternalAxiosRequestConfig<D>;
  ...
  static from<T = unknown, D = any>(
    error: Error | unknown,
    code?: string,
    config?: InternalAxiosRequestConfig<D>,
    request?: any,
    response?: AxiosResponse<T, D>,
    customProps?: object,
): AxiosError<T, D>;
  ...
}
```

From index.d.cts in v1.7.8:

```
declare class AxiosError<T = unknown, D = any> extends Error {
  constructor(
      message?: string,
      code?: string,
      config?: axios.InternalAxiosRequestConfig<D>,
      request?: any,
      response?: axios.AxiosResponse<T, D>
  );

  config?: axios.InternalAxiosRequestConfig<D>;
  code?: string;
  request?: any;
  response?: axios.AxiosResponse<T, D>;
  isAxiosError: boolean;
  status?: number;
  toJSON: () => object;
  cause?: Error;
  static readonly ERR_FR_TOO_MANY_REDIRECTS = "ERR_FR_TOO_MANY_REDIRECTS";
  static readonly ERR_BAD_OPTION_VALUE = "ERR_BAD_OPTION_VALUE";
  static readonly ERR_BAD_OPTION = "ERR_BAD_OPTION";
  static readonly ERR_NETWORK = "ERR_NETWORK";
  static readonly ERR_DEPRECATED = "ERR_DEPRECATED";
  static readonly ERR_BAD_RESPONSE = "ERR_BAD_RESPONSE";
  static readonly ERR_BAD_REQUEST = "ERR_BAD_REQUEST";
  static readonly ERR_NOT_SUPPORT = "ERR_NOT_SUPPORT";
  static readonly ERR_INVALID_URL = "ERR_INVALID_URL";
  static readonly ERR_CANCELED = "ERR_CANCELED";
  static readonly ECONNABORTED = "ECONNABORTED";
  static readonly ETIMEDOUT = "ETIMEDOUT";
}
```

### Expected behavior

`from` should not have been removed in a patch release.

### Axios Version

1.7.8

**Comment by Ehteshamali1109** [comment] 2024-12-04 07:30
Thank you, @jeramysoucy, for reporting this issue!

### Acknowledgment
You’re absolutely right—removing AxiosError.from in a patch release (v1.7.8) introduces an unexpected breaking change, as patch releases should ideally be backward compatible. This can disrupt projects relying on AxiosError.from for custom error handling.

### Root Cause
The change seems to be related to the restructuring of type definitions and the AxiosError implementation in v1.7.8. The from static method, which previously allowed creating custom AxiosError instances, was removed. This removal was not documented in the release notes, which can lead to confusion for developers upgrading.

### Expected Behavior
The from method should either:

Be reinstated to maintain backward compatibility.
If its removal is intentional, it should be clearly marked as a breaking change in a major release (e.g., v2.0.0) with documentation providing an alternative approach.
### Suggested Next Steps
For Axios Team:

Confirm whether the removal of AxiosError.from was intentional or an oversight.
If it was intentional, provide migration guidance and mark this as a breaking change.
If it was unintentional, consider reinstating the method in the next patch release.
For Developers Encountering This Issue: As a temporary workaround, you can create a utility function to replicate the functionality of AxiosError.from. Here’s an example:

```ts
import axios, { AxiosError, AxiosResponse, InternalAxiosRequestConfig } from 'axios';

function createAxiosError<T = unknown, D = any>(
  error: Error | unknown,
  code?: string,
  config?: InternalAxiosRequestConfig<D>,
  request?: any,
  response?: AxiosResponse<T, D>,
  customProps?: object
): AxiosError<T, D> {
  const axiosError = new axios.AxiosError(
    (error as Error).message,
    code,
    config,
    request,
    response
  );

  if (customProps) {
    Object.assign(axiosError, customProps);
  }

  return axiosError;
}

// Usage
const customError = createAxiosError(new Error('Something went wrong'));
```
### Additional Context
This change likely impacts developers using custom error handling workflows. It's critical for the Axios team to address this, as the removal of from without a clear alternative might result in significant refactoring for affected projects.

Thank you again for highlighting this, and we appreciate the Axios team's attention to maintaining compatibility and providing clear communication around changes.

**Comment by jasonsaayman** [comment] 2024-12-04 08:06
reverted these changes in v1.7.9 which should solve any issues. i will re-look the original proposal as it seems to have caused breaking change which I was un-aware of when merging

should this not solve it please @ me and I will re-look

**Closed by jasonsaayman** 2024-12-04 08:06 UTC
