### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Request failed with status code 404

### ISSUE THREAD

**Issue by masserra** [axios/axios#2561] opened 2019-11-20 10:32 UTC
**Getting this verbose error warning on my terminal spilled over countless times in between all processes.**
I decided to do "git checkout master" changing the code in the folder while the server was running and watching for changes. This created an unhandled warning that doesn't want to disappear. I downloaded and reinstalled everything from git and also restarted the computer, cleared yarn/npm caches but the error still occurs.

I found that in future versions Node will crash instead but for now these will actually stay indefinitely. **I was reluctant to post here, although it's important to notice that I'm not using Axios directly**, a third party is, but all the solutions I find seem to address direct usage of Axios where they have direct access to the code. 

**How can I solve this without having any access to the code that created the error?** Since this seems to be caused by not having a failure handler **.catch()** or a **try/catch** I imagined it could actually be part of an actual unhandled error inside the Axios codebase. 

**Error**
```js
(node:2585) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/Users/masserra/Desktop/shopify/themes/ck-slate/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/masserra/Desktop/shopify/themes/ck-slate/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/masserra/Desktop/shopify/themes/ck-slate/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:2585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
```

**Environment:**
 - Axios 0.18.0
 - OSX 10.15.1
 - @shopify/slate-tools ^1.0.0-beta.19

**Comment by deepp2887** [comment] 2019-11-21 13:58
I am getting the same above error while using the Shopify slate theme.

**Comment by Neath7** [comment] 2019-11-22 10:10
I am also getting this error 🤪

**Comment by rodgomesc** [comment] 2019-11-22 12:40
same error

**Comment by PiotrekFilipecki** [comment] 2019-11-22 13:27
I also have this error while using Shopify Slate Theme

**Comment by LuisAlejandro** [comment] 2019-11-24 03:22
Same error here

**Comment by emovi** [comment] 2019-11-25 01:55
Same error here

**Comment by deepp2887** [comment] 2019-11-25 14:21
Simply update the return Axios code in the slate-analytics/index.js file.

`node_modules/@shopify/slate-analytics/index.js `

Update the code in line 95

`return axios('https://v.shopify.com/slate/track', axiosConfig).catch(() => {});`

**Comment by emovi** [comment] 2019-11-25 16:31
Thank you @deepp2887. It worked fine.

**Comment by masserra** [comment] 2019-11-27 09:59
Yeahhh! Cheers @deepp2887 !! Can't believe, no more chaos!

**Comment by masserra** [comment] 2019-11-27 10:21
I think the discussion should continue though, as this will not be the actual solution to the problem, if there is one at all of course. Any time one will update/reinstall the dependencies this fix will go away.

I tried taking it back to see if the promise, once caught, would disappear and it didn't. In an attempt to actually resolve the underlying Promise warning (and without really knowing much about Promises) I decided to try a few more things like `return Promise.reject(error.response);` and similar variations but without success... 

Is this really something that is possible and worth chasing or not really? Maybe more important would be to make **@shopify/slate-analytics** add this catch to their code, but It feels weird that once we get this error warning we cannot really get rid of it...

**Comment by asimontsev** [comment] 2019-12-04 12:00
@masserra I agree that the solution is not very great, however, it is not a bug in Axios. The reason is that the Slate tracking service is down (or moved). It looks like this problem is already reported to Shopify team: 

https://github.com/Shopify/slate/issues/1075

Since Slate is "on low maintenance", it may take a while for them address this issue. Anyway, it is better to discuss the Slate issue there.

**Comment by chinesedfan** [comment] 2019-12-04 12:59
> Maybe more important would be to make @shopify/slate-analytics add this catch to their code, but It feels weird that once we get this error warning we cannot really get rid of it

@masserra Yes, please ask @shopify/slate-analytics to provide a way to handle this kind of error. A simple fix is adding an optional function to catch it. If users do not set, @shopify/slate-analytics catches the error by itself.

As this is not an issue of axios, I am going to close it. Future updates can be tracked in Shopify/slate#1075.

**Closed by chinesedfan** 2019-12-04 12:59 UTC

**Comment by mrleolg** [comment] 2020-04-22 01:54
I like the answer 666...
