### ISSUE TITLE
Sometime response.data is string instead of object

### ISSUE THREAD

**Issue by huy-lv** [axios/axios#1723] opened 2018-08-13 04:42 UTC
I don't know why but with the same api, sometime axios's response.data is string instead of object. See the below figure.

![image](https://user-images.githubusercontent.com/7688070/44013145-f9ba29a6-9eed-11e8-8d02-c41c5f0169e9.png)

#### Context

- axios version: 0.18.0
- Environment: React native Expo SDK 29, window 10

**Comment by robmcguinness** [comment] 2018-08-17 18:12
@huy-lv,

Is the `content-type` the same for both responses?

**Comment by huy-lv** [comment] 2018-08-17 22:59
Nope, i tried 
`if(typeof data === 'string'){
   data = JSON.parse(data)
}
`
But it throws parse exception because the content in case of string is shorter case of object

**Comment by huy-lv** [comment] 2018-08-18 07:08
@robmcguinness Yes, it's application/json

**Comment by kim-knudsen** [comment] 2018-08-19 12:14
I see the same behaviour. I found that in my case the API response would sometimes contain invalid JSON data, i.e. `JSON.parse` would throw. For some reason Axios seems to swallow this error, and ends up setting the invalid JSON string on the `data` property.

**Comment by nighttiger1990** [comment] 2018-08-20 12:14
I got this problem, too.

**Comment by nighttiger1990** [comment] 2018-08-20 13:01
I've checked with Axios, XMLHttpRequest, fetch
1./ Axios and XMLHttpRequest got same problem
2./ fetch work perfectly

**Comment by OpenGG** [comment] 2018-08-22 13:40
I know there are some chars can lead to that problem, just need to be sure.
Could you capture the response and attach it as file?

**Comment by huy-lv** [comment] 2018-08-24 12:41
@OpenGG sorry for late response, what you need here :D 
https://1drv.ms/t/s!AnakDtCf8CG5hIgn2Hemy6zanFi50Q

**Comment by OpenGG** [comment] 2018-08-25 07:34
@huy-lv Not what I'm expected. Please save the response with curl, then attach the saved file by dropping it to this issue's reply area.

**Comment by OpenGG** [comment] 2018-08-25 07:39
@huy-lv 

Never mind, found it.
I pasted it on gist and tried loading with axios, can't see any error.

file: https://gist.github.com/OpenGG/ac72e79f9ef088e993213473116c0cd0
demo: https://codepen.io/OpenGG/pen/bxEqKL

**Comment by nighttiger1990** [comment] 2018-08-28 02:52
@OpenGG it happen on React-Native. Web App work perfectly.

**Comment by OpenGG** [comment] 2018-08-28 04:16
@nighttiger1990 

Could you make an online demo on expo, and share it? This demo should make the same request with both Axios and XMLHttpRequest, to determine whether Axios or RN cause this issue.

**Comment by nighttiger1990** [comment] 2018-09-01 19:44
@OpenGG can you give me your mail i'll send you api, i can't public that
https://github.com/nighttiger1990

**Comment by Druthi** [comment] 2018-09-09 12:44
Any luck with this issue? I'm facing it too

**Comment by nighttiger1990** [comment] 2018-09-10 03:03
@Druthi now im using 'fetch' instead of 'axios'

**Comment by iOSleep** [comment] 2018-10-11 09:10
any update?

**Comment by luatnd** [comment] 2018-11-23 03:07
This might not your case but in my case: 
My API response string is not valid JSON, so axios cannot parse to JSON, then it return raw string instead.

**Comment by petercutting** [comment] 2019-04-03 07:24
I have migrated my app (redux-saga,axios) to webpack4 and now response.data is a string instead of object. The migration changes I made are minimal to compile successfully
package.json
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-dev-middleware": "^3.6.1",
    "webpack-dev-server": "^3.2.1"
    "file-loader": "^3.0.1",

webpack-config.js
    added    mode: 'development',     to module.exports
    commented out     colors: true,      in devServer
    commented out  json-loader

**Comment by petercutting** [comment] 2019-04-03 08:16
I ran JSON.parse(response.data) and the JSON is corrupt. (Unexpected token : in JSON at position 8181)

                "municipality": "ddrNote": ""      should be

                "municipality": "",
                "addrNote": ""
I compared with my pre migration webpack3 code where the JSON in response.data is OK (object). So the migrated code is managing to corrupt the JSON in response.data and that is why it is appearing as a string. So now the question is why is the JSON corrupt

**Comment by petercutting** [comment] 2019-04-03 09:02
I solved the problem by downgrading to     "webpack-dev-server": "3.1.10"

I have a devServer proxy which I guess is the cause of the response corruption for versions greater then 3.1.10

**Comment by nyilmaz** [comment] 2019-04-03 11:03
@petercutting it is also a problem in production environment, haven't you observed?

**Comment by petercutting** [comment] 2019-04-03 11:29
@nyilmaz my problem turned out to be caused by webpack-dev-server. webpack-dev-server would not be used in a production environment

**Comment by goodmorninggoaway** [comment] 2019-05-22 04:10
@petercutting did you open an issue against webpack-dev-server? I couldn't find on.

**Comment by petercutting** [comment] 2019-05-23 10:23
@goodmorninggoaway I dont remember. probably not

**Comment by bluenote10** [comment] 2019-06-16 15:48
Irrespective of the webpack-dev-server issues, Axios shouldn't silently swallow `JSON.parse` exceptions, right?

I was just testing the robustness of an app by sending malformed JSON from the backend. The Axios request silently fails to decode the JSON. The header `content-type` still says `"application/json"`, but `response.data` is the raw unparsed string, and my app crashes unexpectedly as a follow up.

It's quite crazy that a library with 60k stars has such a basic bug for half a year :confused:

**Comment by nyilmaz** [comment] 2019-06-17 06:21
> Irrespective of the webpack-dev-server issues, Axios shouldn't silently swallow JSON.parse exceptions, right?

Parfectly valid

**Comment by matinzd** [comment] 2019-06-25 06:37
Any update on this bug for react native!?

**Comment by ruimcf** [comment] 2019-07-18 11:09
I found that this happens when the json response from the server is invalid, use a json validator like https://jsonlint.com/ to make sure that your json is correctly formatted

**Comment by fed135** [comment] 2019-08-13 18:57
The error swallowing issue is being tracked, I will be closing this issue as it's essentially a duplicate of it.

Please reach out if you have any questions.

**Closed by fed135** 2019-08-13 18:57 UTC

**Comment by nyilmaz** [comment] 2019-08-19 06:09
@fed135 please link the relevant issue if any, thanks.

**Comment by kingeke** [comment] 2019-09-04 18:23
Anyone solved this yet?, I'm using laravel as my API, so i logged my response before sending it to my app. The logged response is a valid JSON but the received response has the last "}" brace missing at the end, making it an invalid response. I don't know why this is behaving like this on my mobile app, cause for the frontend app it which uses axios too it works fine, tried on postman too, it works fine. any ideas or solutions pls??

**Comment by matinzd** [comment] 2019-09-04 18:27
It happens when data gets too large :( I didnt have any problems since the data array was small!

**Comment by kingeke** [comment] 2019-09-04 18:36
@matinzd I paginate my data, and only return 20

**Comment by kingeke** [comment] 2019-09-04 18:38
@matinzd and also, my fronend app uses the same endpoint, and it doesn't experience that, only the mobile app with react native does sometimes

**Comment by bluenote10** [comment] 2019-09-04 18:44
@fed135 Is this the right issue to track as a follow up? #61

**Comment by damzylee** [comment] 2019-11-07 08:43
please my laravel api is coming out as a string alongside <!--, and looping through is like looking through a string

**Comment by damzylee** [comment] 2019-11-07 09:59
I have finally found a solution to mine. 
The data i was getting was === <!-- {"data":[{"id":2,"name":"beryl","email":"beryl@gmail.com","subscription_id":null,"number":"678904987653","user_id":null,"type":"okayna","country":"nigeria","state":"lagos","address":"maryland","image":null,"profile":null,"YOE":null,"created_at":null,"updated_at":null},{"id":1,"name":"mamacita","email":"mamacita@gmail.com","subscription_id":null,"number":"09876534567","user_id":null,"type":"bitch","country":"nigeria","state":"lagos","address":"gbagada","image":null,"profile":null,"YOE":null,"created_at":null,"updated_at":null}]}
app.js:1813 

And I solved it by:

 Axios.get(uri)
        .then((response) => {
            let ValidJson = '';
            let myArray = '';
            let moyo = response.data;
            console.log(moyo);
            ValidJson = moyo.replace("<!-- ","");
            myArray = JSON.parse(ValidJson);
            this.companies = myArray.data;
        }).catch(error => console.log(error));
    },

**Comment by marcosrd91** [comment] 2020-01-30 15:46
I have the same error
 :(

**Comment by arrlancore** [comment] 2020-02-10 04:06
Got the same issue, after check in jsonlint.com I have the data with NaN which json cannot parsing it as below. So we need to ensure our backend sent the valid JSON data.

```js
Error: Parse error on line 186:
...,	"position_name": NaN,	"group_name": 
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

**Comment by tuanhai2712** [comment] 2020-02-27 09:10
Same error, who can fixed it :|

**Comment by zhming0** [comment] 2020-03-25 22:34
☝️  I made a quick PR to address this issue. Hopefully it hopes

**Comment by LMestre14** [comment] 2020-05-12 11:06
Getting this issue in react-native with axios 0.19.2
Any update on the issue?

**Comment by mbish0p** [comment] 2020-05-17 18:33
I got this same issue, I solved this problem make change in method od axios, if you had 'GET' method you can t send body because you can get this issue, to solve this you need to change to 'POST' and it will be working
