### ISSUE TITLE
Don't send default header

### ISSUE THREAD

**Issue by kyeotic** [axios/axios#382] opened 2016-07-19 21:34 UTC
If a header has been set as a default, there does not appear to be any way to skip it on an individual request. Setting `null` or `undefined` doesn't do anything.

**Comment by rubennorte** [comment] 2016-07-20 20:43
Could you provide some code example that shows that behaviour? What default header are you trying to unset?

**Comment by tyrsius** [comment] 2016-07-20 20:53
If I set `axios.defaults.headers.common['Content-Type'] = 'application/json'`, I cannot unset that that header for an individual request, I can only set it to another value.

**Comment by rubennorte** [comment] 2016-07-20 21:08
How did you tried to unset the header? Using something like this?

```javascript
axios.request('/path', {
  headers: {
    'Content-Type': null
  }
});
```

**Comment by tyrsius** [comment] 2016-07-20 21:09
Yes. That did not work

**Comment by rubennorte** [comment] 2016-08-07 09:19
Sorry I missed the `method` in my example. Could have been that what made it not work?

**Comment by tyrsius** [comment] 2016-08-07 18:35
I have tried setting the method as well. I suspect it has to do with an `Object.assign()` somewhere just not paying attention to the `undefined` value.

**Comment by mzabriskie** [comment] 2016-08-13 03:51
@tyrsius what version of axios are you using? I just wrote a test to try and reproduce this and it passed. I'm wondering if this may have been fixed in a newer version.

For reference here is my test:

```js
it('should remove default headers when config indicates', function (done) {
  var instance = axios.create();
  instance.defaults.headers.common['Content-Type'] = 'application/json';

  instance.post('/foo/bar/', {
    firstName: 'foo',
    lastName: 'bar'
  }, {
    headers: {
      'Content-Type': null
    }
  });

  getAjaxRequest().then(function (request) {
    testHeaderValue(request.requestHeaders, 'Content-Type', null);
    done();
  });
});
```

**Comment by Madalosso** [comment] 2016-09-13 15:53
I had this problem too.
I'm trying to remove the header 'Authorization' from 'common' but the only way that I've found to make it work was delete the property from the axios.defaults.header, make the request, and then insert the property back again.
This will be easier when [this](https://github.com/mzabriskie/axios/issues/385) bug is fixed

**Comment by chipit24** [comment] 2016-09-29 21:04
This is also a problem for me (using axios v0.14.0), especially for endpoints that use `Access-Control-Allow-Headers`, in which case I need to make sure certain headers aren't sent with the request at all.

**Comment by SepiaGroup** [comment] 2016-10-19 05:12
i am using version 15.2 and when i do

```
headers: {
      'Content-Type': null
    }

```
it does set the header value to null. but i really need the header name to be removed completely. 

for example when using s3 and generating a presigned url to post a file to a bucket you can not have an Authenticate header. but i have a default Authorization set because the vast majority of my requests require it for my own api. 

the way i got around this is by doing the following 

```
    var instance = axios.create();
    instance.defaults.headers.common = {};

    instance.put(signedUrl, file, {headers: {'Content-Type': file.type}})
        .then(function (result) {
            console.log(result);
        })
        .catch(function (err) {
            console.log(err);
        });
```

**Comment by paseo** [comment] 2016-11-23 06:00
#545

**Comment by axelgenus** [comment] 2017-02-21 10:51
I had the same problem but solved with

`delete axios.defaults.headers.common["Authorization"]; // or which ever header you have to remove`

**Comment by Christilut** [comment] 2017-05-20 15:00
I have the exact situation as @SepiaGroup 
I tried to overwrite it with `null` and `''` but then AWS sees `null` as my Authorization and complains.
I tried to delete it from the instance but then my Authorization is deleted globally so I get 403 on my own server.

I guess my workaround will be to use an old `XHR` for this but it makes me sad :(

**Comment by yaronlevi** [comment] 2017-06-07 13:24
+1 Also stuck with not being able to clear the default header for a specific call.

**Comment by lukasborawski** [comment] 2017-06-08 14:04
+1

**Comment by ojczeo** [comment] 2017-06-09 12:59
+1

**Comment by tannerlinsley** [comment] 2017-06-13 03:31
I'm also seeing this behavior in the latest version (0.16.2).  Sadness ensues :(

**Comment by lzp4ever** [comment] 2017-06-22 11:52
I think we could create a logout method that recreate the axios instance to replace the old one.
```
let instance = axios.create({options})

function: logout () {
    instance = axios.create({options})
}
```

**Comment by wdews** [comment] 2017-06-22 22:53
@lzp4ever that would work in most instances, I expect. But in cases where someone has added request and response interceptors, or done more configuration of the instance beyond simply passing in config options, wouldn't your approach require that all of that be redone?

Just wondering if perhaps @axelgenus's solution is cleaner and requires less "resetting" of an entire Axios instance from which you're attempting to remove a particular customized header from.

**Comment by maryokhin** [comment] 2017-06-27 12:31
Would be nice to be able to NOT send the default header without deleting properties :)

**Comment by InsidiousMind** [comment] 2017-07-14 18:42
Getting this same problem, except with 'Content-Length' and not 'Content-Type'.

For some reason, Axios always has Content-Length set to 78. I'm making a PUT request, and in order for it to work, Content-Length must be set to the size of the file (in this case a tar.gz file). Also uploading to a Amazon S3 instance.

**Comment by MrFahey** [comment] 2017-07-18 09:33
+1

**Comment by Jenan** [comment] 2017-07-19 13:53
+1

**Comment by oodgaard** [comment] 2017-07-24 08:07
+1

**Comment by dkanas** [comment] 2017-07-26 14:56
+1

**Comment by Spacelapp** [comment] 2017-07-28 09:49
+1

**Comment by shyamchandranmec** [comment] 2017-08-02 13:55
+1 Please fix this issue.

**Comment by michaelcpuckett** [comment] 2017-08-11 10:17
+1

**Comment by matthewlilley** [comment] 2017-08-19 11:09
+1

**Comment by vw98075** [comment] 2017-08-24 17:56
+1 

We run into the same issue. Most of front-end apps we build need to consume multiple Rest webservices. Unable to opt out the security header is a big problem for us.

**Comment by tanbowensg** [comment] 2017-08-31 10:46
+1

**Comment by deb0rian** [comment] 2017-08-31 17:07
+1

I'm using default instance that was created by VueJS, I have to send Authorization across the system, but I have 1 request I have to make remote and even removing it from a new instance, removes it globally, which is bad. This is not working:

`var rAxios = axios.create({
            baseURL: brokerUrls.signInUrl
        });
        rAxios.defaults.headers.common = [];`

Removes everywhere, in axios. and in rAxios. :(

**Comment by mukeshyadav** [comment] 2017-09-12 12:50
Try this, its solve my problem:

delete axios.defaults.headers.common["Authorization"]; // and create your own headers

**Comment by wdews** [comment] 2017-09-12 12:56
@mukeshyadav That solution has been mentioned several times further up in this thread.

The point made is that this isn't necessarily the ideal solution. Imagining a scenario where you've added your own custom request/response interceptors to an Axios instance, but you want one specific request to not include headers used everywhere else, you'd have to delete the header(s) and re-add after the request is completed.

Conversely, wondering if there's a way you can, with relative easy, simply duplicate an Axios instance to use in these types of one-off cases.

**Comment by luskin** [comment] 2017-09-13 20:19
+1

**Comment by aaronatmycujoo** [comment] 2017-09-28 13:09
```
transformRequest: [(data, headers) => {
    delete headers.common.Authorization
    return data
}]
```

works for me

**Comment by wdews** [comment] 2017-09-29 13:21
@aaronatmycujoo That seems like the sexiest interim solution. Although, wondering if deleting the header like that removes it from an Axios instance further up the chain. May have to create a deep copy of `headers` or something.

I'll have to test that.

**Comment by aaronatmycujoo** [comment] 2017-10-02 11:15
from what i can tell it doesn't. although there could be an edge case that i'm not triggering

**Comment by wdews** [comment] 2017-10-02 11:59
@aaronatmycujoo I set up a test scenario in Codepen to verify and it looks like it's just making a deep copy of `headers` to pass into the `transformRequest` callback.

[See Codepen here](https://codepen.io/wdews/pen/JrywdV?editors=1010)

So it appears this works as expected; headers that are set on an Axios instance and removed on a per-request basis using the `transformRequest` callback do not impact the Axios instance on which they're deleted.

Nice!

**Comment by apoca** [comment] 2018-06-26 11:43
@SepiaGroup you don't need to add headers in whole your requests... Do this:

`axios.defaults.headers.common = {};`
`axios.defaults.headers.common.accept = ‘application/json’;`

And in headers of request you'll only see ‘application/json’

**Comment by vidukapoor** [comment] 2018-06-29 10:36
+1 thanks @axelgenus ur solution worked

**Comment by Raid55** [comment] 2018-07-07 09:18
@aaronatmycujoo FTW!!! His solution worked like a charm...ty!

**Comment by shuangq** [comment] 2018-08-13 13:16
Faced the same issue when trying to upload files to S3 (only allow one auth mechanism).
Tried the solution from @SepiaGroup  but it also removes the auth header globally for all the following instances :(
@aaronatmycujoo This solution works perfectly for me! 🎉
Thank you guys for saving my day!

**Comment by bigsee** [comment] 2018-08-31 22:55
+1

**Comment by watch-janick** [comment] 2018-09-04 13:40
+1

**Comment by nickgrealy** [comment] 2019-01-23 13:50
Not sure if this is common knowledge, but there is a set of ["forbidden headers"](https://fetch.spec.whatwg.org/#forbidden-header-name), which cannot be deleted.

- `Accept-Charset`
- `Accept-Encoding`
- `Access-Control-Request-Headers`
- `Access-Control-Request-Method`
- `Connection`
- `Content-Length`
- `Cookie`
- `Cookie2`
- `Date`
- `DNT`
- `Expect`
- `Host`
- `Keep-Alive`
- `Origin`
- `Referer`
- `TE`
- `Trailer`
- `Transfer-Encoding`
- `Upgrade`
- `Via`

**Comment by putu-eka-mulyana** [comment] 2019-04-22 17:43
error
===
TypeError: Cannot convert undefined or null to object
   
<code>delete axios.defaults.headers.cummon["Authorization"];</code>

**Comment by bitttttten** [comment] 2019-04-22 19:15
You have a typo @putu-eka-mulyana 

`delete axios.defaults.headers.common["Authorization"];`

**Comment by tourze** [comment] 2019-05-17 12:46
+1, remove the charset from content-type

**Comment by sirajalam049** [comment] 2019-08-05 15:47
+1, remove Auth header for just one request, take in request config object without deleting explicitly, just by passing some value like undefined or null

**Comment by rizen** [comment] 2019-09-18 02:36
+1, remove Auth header for just one request, take in request config object without deleting explicitly, just by passing some value like undefined or null

**Comment by lutzklai** [comment] 2019-11-06 23:23
I have an OPTION request before my PUT request, so @aaronatmycujoo 's transformRequest solution worked for my OPTION request, but the Authorization header was still applied to my PUT request.

Ultimately i ended up making separate instances for auth vs public requests so my auth header was only applied to the auth instance.

```js
// do not configure auth header
export const publicAxios = axios.create(...)

// configure auth header
export const authAxios = axios.create(...)

// no auth header present for public instance
publicAxios.put(...)
```

**Comment by sandervanhooft** [comment] 2019-12-18 11:05
@rizen PR #1845 by @codeclown would allow unsetting headers by passing `null`. Would this solve the issue?

**Comment by rizen** [comment] 2019-12-18 14:14
> @rizen PR #1845 by @codeclown would allow unsetting headers by passing `null`. Would this solve the issue?


Yes

**Comment by MLDMoritz** [comment] 2020-01-08 00:50
What a long journey. Hope #1845 get's merged asap.

**Comment by iyerusad** [comment] 2020-01-17 07:58
> ```
> transformRequest: [(data, headers) => {
>     delete headers.common.Authorization
>     return data
> }]
> ```

From axios documentation:
> This is only applicable for request methods 'PUT', 'POST', 'PATCH' and 'DELETE'
----

I am running into rather similar situation but with a GET request:
1. GET http://www.saasserviceprovider.com/notpublicapi with header of `Authorization: Bearer mytoken`

2. Redirects to AWS S3 endpoint. Redirect URL has a query string: `X-Amz-Signature=blahblahblah` appended.

3. AWS S3 rejects call because two Authenication:
  - Header: Authorization bearer token
  - Query string: X-Amz-Signature=blahblahblah

Neither `transformRequest`, `transformResponse`, `axios.interceptors.request`, `axios.interceptors.response` appears to be able to allow me to inject myself into the process and temporarily remove the Authorization Header when hitting the redirection to AWS S3.

Same call with request api/postman/etc works.

**Comment by mikhoq** [comment] 2020-03-27 01:05
> I am running into rather similar situation but with a GET request:
> 
> 1. GET http://www.saasserviceprovider.com/notpublicapi with header of `Authorization: Bearer mytoken`
> 2. Redirects to AWS S3 endpoint. Redirect URL has a query string: `X-Amz-Signature=blahblahblah` appended.
> 3. AWS S3 rejects call because two Authenication:
> 
> * Header: `Authorization bearer token`
> * Query string: `X-Amz-Signature=blahblahblah`
> 
> Neither `transformRequest`, `transformResponse`, `axios.interceptors.request`, `axios.interceptors.response` appears to be able to allow me to inject myself into the process and temporarily remove the Authorization Header when hitting the redirection to AWS S3 - presumably if I could get in after a redirect I could do something to effect of `delete headers.Authorization`.
> 
> Same call with request api/postman/etc works.
> 
> Seriously though... has to be better way (within axios)

@iyerusad Did you find any better way than your workaround? I'm facing the same issue, and it's frustrating that I don't seem to be able to intercept the redirect and delete the Authorization header just for that follow-up / redirect request (to amazon in this case) 🤔

**Comment by iyerusad** [comment] 2020-03-27 01:27
> @iyerusad Did you find any better way than your workaround? I'm facing the same issue, and it's frustrating that I don't seem to be able to intercept the redirect and delete the Authorization header just for that follow-up / redirect request (to amazon in this case) 🤔

Not really - using option **B.** from below.

**_The options I evaluated:_**
**A.** Adopt alternative wrapper/client (e.g. fetch api? request? request seemed to work but is apparently deprecated). This might be cleanest option but means switching to another http client syntax.

**B.** Wrap my workaround into a function and use that function for requests that I know run into this issue - ugly seemingly less efficient but using this at the moment.

**C.** Hope I am an idiot and using axios wrong and there is saner workaround with axios.

**D.** Axios get fix/patch?

**Comment by chinesedfan** [comment] 2020-03-27 12:07
@mikhoq @iyerusad Would you mind to open a new issue to track your problem? Because it is different with the current one, which may have been fixed in #2844.

**Comment by iyerusad** [comment] 2020-03-27 21:35
No problem - Opened #2855. 

@mikhoq  please add comment there if you have public repro endpoint.

**Comment by guanzo** [comment] 2020-04-03 03:37
So apparently `transformRequest` does get called for `GET` requests? I tried [this ](https://github.com/axios/axios/issues/382#issuecomment-332831141)and it worked
```js
transformRequest: [(data, headers) => {
    delete headers.common.Authorization
    return data
}]
```

But the docs say

>   // `transformRequest` allows changes to the request data before it is sent to the server
  // This is only applicable for request methods 'PUT', 'POST', 'PATCH' and 'DELETE'

Which made me think `transformRequest` wouldn't be called for `GET` requests? But it is, so what does `This is only applicable for request methods` actually mean?

**Comment by idjemaoune** [comment] 2020-04-13 10:16
this works:
headers: {
          'content-type': 'application/json',
          'Authorization': null,
   }

**Closed** 2020-06-04 18:57 UTC
Labels: component:headers

**Comment by tylercaceres** [comment] 2020-08-01 05:25
Was this resolved?

**Comment by tylercaceres** [comment] 2020-08-01 14:57
> ```
> transformRequest: [(data, headers) => {
>     delete headers.common.Authorization
>     return data
> }]
> ```
> 
> works for me

documentation says 
> // This is only applicable for request methods 'PUT', 'POST', 'PATCH' and 'DELETE'
is there a way to get this to work with 'GET' requests?

**Comment by Roms1383** [comment] 2020-11-16 06:02
Tried setting `{ headers: { 'Content-Type' = null } }` without success,
so to add to @axelgenus helpful [comment](https://github.com/axios/axios/issues/382#issuecomment-281309372), I had to go a bit further :
```ts
import Axios from 'axios'
const client = Axios.create({
  // ...
  transformRequest: [(data, headers) => {
    // add required "Content-Type" whenever body is defined
    if (data) headers['Content-Type'] = 'application/x-www-form-urlencoded'
    return data
  }],
})
// completely remove "Content-Type" from instance by default
delete client.defaults.headers.common['Content-Type']
delete client.defaults.headers.post['Content-Type']
delete client.defaults.headers.put['Content-Type']
delete client.defaults.headers.patch['Content-Type']
// ...
```

Use case was implementing requests layer for [Bitstamp API](https://www.bitstamp.net/api/) **V2** authentication method.

**Comment by JerbyIchrak** [comment] 2021-05-02 16:33
> I have an OPTION request before my PUT request, so @aaronatmycujoo 's transformRequest solution worked for my OPTION request, but the Authorization header was still applied to my PUT request.
> 
> Ultimately i ended up making separate instances for auth vs public requests so my auth header was only applied to the auth instance.
> 
> ```js
> // do not configure auth header
> export const publicAxios = axios.create(...)
> 
> // configure auth header
> export const authAxios = axios.create(...)
> 
> // no auth header present for public instance
> publicAxios.put(...)
> ```

I tried this solution ,it seems right but didn't work for me because i need to add some custom interceptors , so i made a **seperate file** containing another instance i called it publicInstance and i used it for all my public routes . It works !

**Comment by yulafezmesi** [comment] 2021-06-10 11:12
Sperate your auth interceptor and use it whenever necessary.

```javascript
if (getAuthToken()) {
  httpClient.interceptors.request.use(authInterceptor);
} else {
  httpClient.interceptors.request.eject(authInterceptor);
}
```

**Comment by EKOLX** [comment] 2021-07-21 10:32
I tried every single suggestion from each post but none of them help.
Axios still sending 'Content-Type' whenever I try to delete it.
From React Native app I'm trying to upload file into AWS S3 via presigned url, and with Content-Type I get 403 error.
I tried it with postman and without any headers, it uploads successfully, but I don't understand why I can't exclude Content-Type with http request.

**Comment by Pixelatex** [comment] 2021-07-26 12:42
@EKOLX is correct... just been through this whole circus myself. Why the bleeping hell is it so hard to remove a default header.

I need to work with some major company's api who refuse to accept a request that doesn't have exactly the params that they specify.. in this case that you can't send a content-type header...

**Comment by jasonsaayman** [comment] 2021-07-26 12:54
@Pixelatex please can you open a new issue and then tag me in it? Then I can have a look.

**Comment by SaimumIslam** [comment] 2021-10-07 06:27
just keep the header in axios it works like charm.
{```

      "Content-Type": "",
}
```

**Comment by kameshdhana** [comment] 2022-11-23 14:00
> I had the same problem but solved with
> 
> `delete axios.defaults.headers.common["Authorization"]; // or which ever header you have to remove`

The problem is if I remove it the endpoint call fails

**Comment by Rickyv92** [comment] 2023-06-30 21:16
Having this issue, using "axios ^0.18.0"

This companies application injects an 'x-api-key' using interceptors.

I've tried using the methods posted above, but the only ones that remove the x-api-key remove them globally and breaks the entire app.

Any updates or help would be very helpful.

Thanks

**Comment by iyerusad** [comment] 2023-06-30 21:50
> Having this issue, using "axios ^0.18.0"

Using `"axios": "^0.21.1"`, issue appears to be resolved. 

In any case current is `1.4.0`, should update as 0.18 is pre-1.0 and ~5 years old.

**Comment by Rickyv92** [comment] 2023-07-01 01:34
> In any case current is `1.4.0`, should update as 0.18 is pre-1.0 and ~5 years old.

Good point, i'll look into upgrading
