### ISSUE TITLE
cancelToken source pending .

### ISSUE THREAD

**Issue by volkanciloglu** [axios/axios#1705] opened 2018-08-01 08:03 UTC
I use VUE, VUEX and axios . 

I want the previous request  to be canceled  when the same request is made. 

There's a problem with the jet.

```
const videos_list = async ({
  state,
  commit
}, type) => {

  if (token.videos) {
    // token.videos variabla getting other js file object parameters . 
    token.videos.cancel()
  }

  const CancelToken = axios.CancelToken;

  const REQUEST = await axios.post(`${state.url}`, {
    params: [1,2,3]
  }, {
    cancelToken: new CancelToken(function (cancel) {
      token.videos = cancel;
    })
  });

}
```

I see console log problem : 

> Uncaught (in promise) TypeError: _axios_canceltoken__WEBPACK_IMPORTED_MODULE_7__.default.videos.cancel is not a function

**Comment by sprlwrksAprilmintacpineda** [comment] 2018-08-02 11:08
have you tried

```jsx
import Axios from 'axios';
const token;

const videos_list = async ({ state, commit }, type) => {
  if (token.videos) {
    // token.videos variabla getting other js file object parameters . 
    token.videos.cancel()
  } else {
    token.videos = Axios.CancelToken.source()
  }

  const REQUEST = await axios.post(`${state.url}`, {
    params: [1,2,3]
  }, {
    cancelToken: token.videos.token
  });
}
```

**Comment by VCodepp** [comment] 2018-08-02 11:30
I solved this problem like this

```
import token from './axios.token'; // this json file.
token.cancel = axios.CancelToken;

const albums_list = async ({
  commit,
  state
}, params) => {
  try {
    if (token.videos!== undefined) {
      token.videos();
    }
    const REQUEST = await axios.post(`url`, {
      data: data
    }, {
      cancelToken: new token.cancel(function executor(c) {
        token.videos = c;
      })
    });
    token.videos = undefined;
  } catch (e) {}
};

```

I do not know which one is better. your code or this code

**Comment by Marcholio** [comment] 2019-02-10 17:02
Can this now be closed as the problem is solved?

**Comment by PLQin** [comment] 2019-03-12 04:00
```
instance.interceptors.request.use(config => {
    /* some logic */
    return  {
            headers: {},
            method: config.method,
            url: ""
          };
});
```

Is the simplest !

**Closed** 2020-01-26 05:09 UTC
