### ISSUE TITLE
request intercepters order is reversed

### ISSUE THREAD

**Issue by latel** [axios/axios#1663] opened 2018-07-09 18:18 UTC
```javascript
const axios = require('axios');

axios.interceptors.request.use(function(config) {
	console.log(1);
}, undefined);


axios.interceptors.request.use(function(config) {
	console.log(2);
}, undefined);

axios.get('http://www.baidu.com').then(function() {
	console.log('ok');
}).catch(function() {
	console.log('fail');
});
```

which prints:

```bash
node index.js
2
1
fail
```

**Comment by delirius325** [comment] 2018-07-17 16:57
Hi @latel ,

I'd like to know your use case please, why do you need two interceptors back to back?

Thanks,

**Comment by delirius325** [comment] 2018-07-17 17:16
Hey there @latel,

an axios contributor/manager can correct me if I'm wrong, but as I understand it (and from that comment in the code), the interceptors are saved in a stack. Therefore, when comes the time to execute the interceptors' forEach in the request, it starts with the last added interceptor (first in, last out).

Here's the part of the code where a stack is mentioned:

```javascript
// axios.js line 1263
/**
* Add a new interceptor to the stack
*/
```

Now here's the definition of the forEach method

```javascript
// axios.js line 1298
InterceptorManager.prototype.forEach = function forEach(fn) {
  utils.forEach(this.handlers, function forEachHandler(h) {
    if (h !== null) {
      fn(h);
    }
  });
};
```
Therefore I believe it's normal for axios to behave the way it behaves. 

On a side note, may I know your use case? Why do you need two interceptors back to back like this? If one interceptor must be executed before the other, then I suggest you just build one interceptor that does the whole thing.

Also, you might want to add this inside your interceptors
```javascript
return config;
```

This way you'll get 
```javascript
node index.js
2
1
ok
```

Hope this helps :) !

**Comment by OpenGG** [comment] 2018-08-07 12:13
This actually was asked a year ago, but it got closed and no changes had been made.

https://github.com/axios/axios/issues/841

If this feature is to stay, at least it should be documented.

**Comment by latel** [comment] 2018-08-14 06:27
Thank you for your reply @delirius325,

I think sometimes it's better to have an option to specify the order we really need, whether it's reverse or not. The default execute oder of *request intercepters* and *response intercepters* are opposite, which is a confusing thing.

think about the follow situation:

1. we have a request modules which just wrappers axios for default behaviour management, and expose `beforeEach` and `afterEach` hook, and it also defines a request intercepter which just mark every request with a uniq id index.
    
```javascript
import axios from 'axios';

const beforeEach = (succFn, errFn) =>
  requestInterceptors.push(axios.interceptors.request.use(succFn, errFn));
const afterEach = (succFn, errFn) =>
  responseInterceptors.push(axios.interceptors.response.use(succFn, errFn));
const ejectBefore = interceptorId =>
  axios.interceptors.request.eject(interceptorId);
const ejectAfter = interceptorId =>
  axios.interceptors.response.eject(interceptorId);

// this interceptor add a uniq id index
beforeEach(config => {
  config.id = uniqIndexedId();
  return config;
});

export { beforeEach, afterEach }
```

2. and here we have a module which import the above request module, and define interceptors using the`beforeEach` hook.

```javascript
import { beforeEach } from '@/service/request';

beforeEach(config => {
    console.log(config.id); // => ERROR
});
```
this fails because the later registered interceptor is executed before the interceptor which is registered in request module.


I think we do need the *first-in-first-out* order because sometimes we have to convergence some logic into a single module, and ensure that these interceptors are executed earlier.

**Comment by danZheng1993** [comment] 2018-12-24 17:09
This is required, because I am using `axios-case-converter` and custom case converter for specific fields. Please check this link: https://www.npmjs.com/package/axios-case-converter
My backend was built with Rails and it requires `_destory` to remove a field.
But using `axios-case-converter`, there's no way to make the request with field name `_destroy`.
I've tried various strings like `Destroy` and `_destroy` but plugin just parsed everything to `destroy`.
So I need another interceptor to process this edge case, but axios api seems like to run the interceptors randomly. In some cases, the interceptors run in desired order, but some cases, my custom interceptor runs first.
I need help on this as soon as possible.

**Comment by ppdeassis** [comment] 2019-01-17 18:48
I'd like to support this change too.

**Comment by Mactaivsh** [comment] 2019-02-01 09:20
Yes, I've notice this weird behavior too. If this behavior was made in purpose, it should be well document it.

**Comment by latel** [comment] 2019-02-04 15:36
> I'd like to support this change too.
> There's an old PR #1041 to solve it.

this pr seemed to be merged, but for some reason is now gone

**Comment by lili21** [comment] 2019-03-18 07:37
feature instead of bug ?

**Comment by KonovalovaKV** [comment] 2019-04-05 09:53
Hi, this problem is relevant. It is not possible to override and line up the order of the handlers. It is important!

**Comment by zgayjjf** [comment] 2019-04-08 09:18
Is there any progress? At least there should be a configuration.

**Comment by delirius325** [comment] 2019-04-08 14:39
Hi everyone,

So this has been a long standing "issue" which can easily be worked around by adding the following snippet to your code:
```javascript
// add this after your interceptor(s') declaration
axios.request.interceptors.handlers.reverse();
```
However, I did add a `reverseInterceptorsOrder` method in this PR https://github.com/axios/axios/pull/2085.

**Comment by KonovalovaKV** [comment] 2019-05-07 04:18
Any news?

**Comment by delirius325** [comment] 2019-05-07 15:30
@KonovalovaKV 

PR is still ready to be merged. As mentioned in my previous comment, you can DIY with the following code snippet:

```javascript
axios.request.interceptors.handlers.reverse();
```

Hope this helps!

**Comment by 7rulnik** [comment] 2019-06-21 16:59
It should be, isn't?
```js
wrappedAxios.interceptors.request.handlers.reverse();
```

**Comment by chinesedfan** [comment] 2020-02-16 05:37
@delirius325 Would you or someone else mind opening another PR to emphasize it in the document? The current behavior is not straight-forward, but it has been already there server years. And we don't want to introduce extra interface or option.

**Comment by delirius325** [comment] 2020-02-17 13:22
@chinesedfan not sure I understand what you mean by "emphasize it in the document"? What needs to be emphasized exactly? The method I had created? Or the current behaviour?

**Comment by chinesedfan** [comment] 2020-02-17 14:41
> The current behavior is not straight-forward, but it has been already there server years. And we don't want to introduce extra interface or option.

The current behavior. Thanks.

**Comment by alwayszb** [comment] 2020-03-12 09:07
Can anybody follows up this issue?

**Comment by hxiongg** [comment] 2020-04-09 06:01
I have no idea why is this issue getting ignored. Please, either document this unnatural execution order or please merge this PR https://github.com/axios/axios/pull/1041 previously created.

**Comment by b-strauss** [comment] 2020-05-07 12:22
Is this even considered a bug? What is the position of the team regarding this behaviour? I don't think this was communicated clearly.

If this is considered a bug I suggest to fix it with the provided PR.
If this is considered working as intended I suggest closing this issue with a note.

**Comment by ansonatloop** [comment] 2020-05-22 16:20
Adding my support for this as either a fix or as an option. And yes, it should be documented as well, since this seems very unnatural to me and it's not how the response interceptors work. My use case is similar to the others mentioned, in that I'm creating plugin wrappers that utilize interceptors to add modular functionality. It makes sense to me to have the interceptors run in the order that they are attached.

Also, I've seen no replies here that give any reason for why this behavior exists in the first place. It does seem explicitly written this way, so it'd be interesting to hear the implementation reasons.

**Comment by linqFR** [comment] 2020-11-19 21:14
> > The current behavior is not straight-forward, but it has been already there server years. And we don't want to introduce extra interface or option.
> 
> The current behavior. Thanks.


yep clearly not straight-forward ! and if not a bug, an algorithmic issue !

Adding my support for either a fix or an option !

**Comment by marceloloureiro** [comment] 2020-12-10 14:13
Well, I used a different aproach.
First a define an Object called InterceptionHandler.

`javascript
class InterceptionHandler {
  constructor({request, response}) {
    this.request = request;
    this.response = response;
  }
}`

So, the ideia is create multiple handlers, and use them in a single interceptor (or two if we are talking about both request and response).

`javascript
const handler1 = new InterceptionHandler(
  {
    request: (config) => {
      console.log('request 1');
      return config;
    },

    response: (response) => {
      console.log('response 1')
      return response;
    }
  }
);

const handler2 = new InterceptionHandler(
  {
    request: (config) => {
      console.log('request 2');
      return config;
    },

    response: (response) => {
      console.log('response 2')
      return response;
    }
  }
);
`
After that we can line up the handlers in a appropriate execution order.

`javascript
axios.interceptors.request.use(
  (config) => {
   handler1.request(config);
   handler2.request(config);
   return config;
  },
  (error) => Promise.reject(error)
);

axios.interceptors.response.use(
  (response) => {
    handler1.response(response);
    handler2.response(response);
    return response;
  },
  (error) => Promise.reject(error)
);
`
Wich produces the output

`request 1
request 2
response 1
response 2
`

**Comment by latel** [comment] 2021-11-11 10:32
may be we can resolve this issue in another way, provide a option to define wheter this interceptor should be executed ealier, just like `[enforce](https://webpack.js.org/configuration/module/#ruleenforce)` in webpack loaders injection do.

**Comment by Denfie** [comment] 2024-07-10 09:14
related to the [documentation](https://github.com/axios/axios?tab=readme-ov-file#multiple-interceptors)

`... then they are executed in the order they were added ... `

```typescript
// Standard File Core System not possible to overwrite
const axios = require('axios');

export default function factory(context) {
        return new axios(context)
}

axios.interceptors.request.use(function(config) {
        config.headers['not-cors-header'] = 'bla';
	console.log(1);
});

axios.interceptors.request.use(function(config) {
	console.log(2);
});


// our custom file later included after core system was loaded

const httpClient = CoreSystem.httpClient; 

axios.interceptors.request.use(function(config) {
        delete config.headers['not-cors-header'];
        config.headers.Authentication = 'Baerer Token';
	console.log(3);
}, undefined);

axios.get('http://www.baidu.com').then(function() {
	console.log('ok');
}).catch(function() {
	console.log('fail');
});
```

Resulting into the following results:

```
# current result
3
2
1
ok

# expected result
1
2
3
ok
```

The header still contains "not-cors-header" as this is the last interceptor used, but the first one to be implemented.

This is the code section where the unshift was implemented. [Axios -> Core -> Line 128](https://github.com/axios/axios/blob/0e4f9fa29077ebee4499facea6be1492b42e8a26/lib/core/Axios.js#L128)

```typescript
const requestInterceptorChain = [];
let synchronousRequestInterceptors = true;
this.interceptors.request.forEach(function unshiftRequestInterceptors(interceptor) {
      if (typeof interceptor.runWhen === 'function' && interceptor.runWhen(config) === false) {
            return;
      }

      synchronousRequestInterceptors = synchronousRequestInterceptors && interceptor.synchronous;

      requestInterceptorChain.unshift(interceptor.fulfilled, interceptor.rejected);
});
```

**Comment by cbeck88** [comment] 2024-07-31 01:47
I'm going to offer an unpopular opinion:

The current behavior is *better* than the proposed change. The ordering of the request interceptors should just be documented better.

---

Reasoning:

There are some helper libraries built on top of axios, like axios-retry, that will add both a request and a response interceptor for you.

The way the library currently works, I could call several third-party helpers like this, each adding a request and response interceptor, and they will logically form a stack. The last added helper will intercept the request first, and intercept the response last. [This is the same way that middleware's work in django on the server side](https://docs.djangoproject.com/en/5.0/topics/http/middleware/#middleware-order-and-layering).

It's often more useful if the middlewares form a stack, because you may want middleware that retries for 500's to be outermost, and higher-level middlewares, like retrying for some type of auth error, to be inwards of that, and anything that changes other details of the request to be inwards of that, in order to get the best behavior of the client overall.

If this were changed so that requests are handled in order registered and responses are handled in order registered, it would be harder for people to publish middlewares like `axios-retry` and for you to just add several of them and get the right behavior. You would have to re-order the interceptors manually, and that would be pretty annoying.

**Comment by jasonsaayman** [comment] 2024-09-26 17:34
closing due to being very stale, if this is still relevant please open a new issue

**Closed by jasonsaayman** 2024-09-26 17:34 UTC
