### ISSUE TITLE
1.2.0 transformResponse

### ISSUE THREAD

**Issue by heldr** [axios/axios#5296] opened 2022-11-22 22:31 UTC
### Describe the bug

When upgrading from `1.2.0-alpha.1` to just `1.2.0` the config `transformResponse` sends data as binary instead of string.

**Comment by andrewdibiasio6** [comment] 2022-11-22 22:40
Had this issue, I set version to 1.1.x.

**Comment by andrewdibiasio6** [comment] 2022-11-22 22:40
This is likely related to very recent release.

**Comment by DigitalBrainJS** [comment] 2022-11-22 23:20
Please, could you provide more information? At least the platform, ideally a reproducible example.

**Comment by Dav-v** [comment] 2022-11-23 00:06
@DigitalBrainJS Hi, I think I found the same bug after a fresh installation of axios (I launched npm install about 3 hours ago, I'm on axios version `1.2.0`  . I managed to reproduce the issue with a simple example:
```js
const axios = require('axios');

async function start() {
  const { data } = await axios.get('https://jsonplaceholder.typicode.com/todos');
  console.log(data);
}
start();
```

After launching this with node 16.14.0  "data" is not a json object but a string with a weird encoding
```
�^DT�z!��f�Y�����
                 �b�%Z��"���~��4�.m�ڲ
HZ�l
    L����F�}$/�!D��9ij�2�i�CF��^)Q@N���
                                       R�.U�߀���v�)���FD��'�}���o�K�&n�����w���º�c�d�o�3q#��� �w��l�t��!ݑ���̸�l���?��Ԓ+��d�;�U��䈽C
눭Y�������N�KF�s���8���IQ�������5�M/�}��=}꒭�p�ټt�.��죴�Vs_�r���
                                                                p��u�X*#<�6��;���咳#ǚ����K���2g]�z#�b"�
�͍ �T�80'�:�?X�L��Ō�u������q}O������{u�:^:�
                �L�	N�}�=�a�I��"ۃ��|n��¨h�}_(�������!�P�F���1:uu
"G�^I/�H��
          ���=�0�,�3�
(���v�FL�l蟫t=�
�A�e�*��I����re)��z�t�,xTSΎ܃�Y�Z�R�:�<����Ņ/J�'���DM����h�w�ߏ�����
                                             1��T���fM6U���EM���#�~g+�"+��bB���MQ�G��C
��=}�
     ��19��Z�Ǒ���$�`��&pܘ,-�b�p����

                                   ��7q�`{IE�d�e�AĈ7:}m:)

                                                         s��o�:Ê�0�h��W�z�k�q���o�3�_�q�Q��n�M���wؐ��h���=�{�#S6f<�l��bNE�K��Ď �X�]Q����C���xJ�T�3����)TEX�ه�]ڛGՍ�}ǡ�q6&1	�Y�a-wP��
                         %Z��d1�.�M?K�B�	DOh>����9n��}9S�m���R1�v�4�*-���`��V�6��\:<e��� K�	Fƴ�J|�`e[
                                                                                                                 ,��5�'���pc
�[��%����|�C���ں1:�:�0p���%�
                            ��	&��D뉳8V=�I`E
�13�e4#E��l���T����F��\\�]��֠:���pQ�6Z�G���G4��na+�9t����Y\��?�
                                                              Z�����,ыV�L7����H3���C/r���Φ9r��1C�K��P���5��@�m$�6��f���=Q3�&�h�W�m[t.��R�vr�RD�y�ʰ�I��iP��>�s%C����(Y�ẘ?)r��[�	�
q-�E2'f�P��O����^۶T�߁�j=�@=��P��,�f��Z;/����CϦ?��\ѐS��!oM�����p,E�_�0-�fe�O�֕$l���]�h_�x������Xޜ
             �(TVN�`�p6?���׌L�.E/q�>��V�d�
rw]�s�=�]vv �R#e����B�L�>�L��D��@�d.5�|L�
                                         ���9�"�;��k�hI�)Iu^T��0"��Hz�@��UU4}4[�eб��.�u �Ց�z��"S"����|&t7 K>~���Ld�����e"ͬ$
                                                                                                                          8�1�s]���"�EH�̹bʯ/�?n*���0�$�T�4��1
                                                                                                                                                            �G](�1�<
      ����Q���!6���B��x
                       ���f�i=�@�v��z�nE5�C�Zt�,�w� ����t�H��/��`Sń�M�(kS�o����&F���^�~��V>*8w��c���DzA';z�	,	����m3}��
\ Ɯ{Cq�>�!푾���l�H�K�H�q֬9��B�T�����c���D\A��L�W*X/N�85�{l��H�ȷ�X�x��_*8��b�#G�Kѩ���EX��C&�`a�3�όV@��0����/�v:]���3�jw�t-
�TTvO�|W"�NZ{�                                                                                                          !�
C���|4��[oBQ�MjT$��C�Fn�f�}uԂL����59*�
�D3.L���D=��-����v�#
                    e�].�u�4U
                             ��ݨ~�ӱ&f��LΫ�O�����t�\�@u�R��l���4T���G❬�${�K!WơO֑�(�pżD�Ĝ����ee�]�&�vș�b3��M�Ҩ�Cا���Ւ�On����(�N��QO	�qC_�cz���z�v��	���#Zr�Q.
�	�d>6/�f`��79xILb�44Θ�;�(+�ն#�|�ݑ�d���Be���c�1�|(�P[)S���ޗ���i2����Ŝ}h������V��v��'��V��G^eU]"|E�s��i���%}��jaG{�Nj��l���f|�t�ti&[�P�<��@�����"���b3����f�2���,�(A������U�
                ����a�Ehh�*�v+�ܞ�x'��.���7���c����똆:Y�$Lp��k����e�G���(�\�=/9K�݃
                                                                                ��rbݙ�F���<��G,���\�����HV=1�<����F�d�
                                                                                                                      ��I�I엞��4��|s�9�f�Md�o��ֻ�P�O�;\[�Q�2��+M�k_����\*4.�!�]����ZC��0�q��%/C�}���^"Exp4�w�M�V
                                                  ��2���n4��gr�O�.�ߟ@�ld�����W���ͬ�/?; ����a��8����v�\̬q3}��Ѻ C\����L&�.Y�� ��c.��I
                                                                                                                                 !�V¤���>g�Țk���.k
                                                                                                                                                  i��
                                                                                                                                                     ~��֑ds��]����hl�rv���%lE�'r�����'�D)��>��9�,N��
                                      7X��#]"�[���h�1�Ɂ�w��w�l�k?�	�d�O�{
       

```
I'm on Ubuntu 22.04.1 LTS, kernel 5.15.0-53-generic

**Comment by DigitalBrainJS** [comment] 2022-11-23 00:27
@Dav-v Thank you! This helped me find the problem! This issue occurs because of the updated response decompression logic - it is skipped when the server does not set the response content-length header, although this is a required header by the standard.
> For POST, if Content-Length is specified and it does not match the length of the message-line, the message is either truncated, or padded with nulls to the specified length.
> The Content-Length is always returned in the HTTP response even when there is no content, in which case the value is zero.

**Comment by agucova** [comment] 2022-11-23 03:44
Can confirm. This broke our production 😔

**Comment by fernandosmither** [comment] 2022-11-23 03:46
This also happened to me.

Quick fix, go to your dependencies file (for instance `package.json` and replace the axios version
```json
"axios": "1.1.x",
```

**Comment by vizv** [comment] 2022-11-23 06:43
This broke our deployments as well :scream_cat:

**Comment by KyeongminKang-GGQ** [comment] 2022-11-23 08:13
Same issue..  😔

**Comment by RezkyRizaldi** [comment] 2022-11-23 08:44
> This also happened to me.
> 
> Quick fix, go to your dependencies file (for instance `package.json` and replace the axios version
> 
> ```json
> "axios": "1.1.x",
> ```

I'm still getting weird encoding from axios response `data` even after downgrade it to `1.1.3`. I wondering why?

**Comment by KyeongminKang-GGQ** [comment] 2022-11-23 09:07
> > This also happened to me.
> > Quick fix, go to your dependencies file (for instance `package.json` and replace the axios version
> > ```json
> > "axios": "1.1.x",
> > ```
> 
> I'm still getting weird encoding from axios response `data` even after downgrade it to `1.1.3`. I wondering why?

In my case, I downgraded to version 1.1.2.

**Comment by phillipstemann** [comment] 2022-11-23 10:08
I'm experiencing this issue as well. I have downgraded for now.

**Comment by davidfilat** [comment] 2022-11-23 11:22
Same issue

**Comment by wodCZ** [comment] 2022-11-23 11:58
> although this is a required header by the standard.

I don't think it is: https://httpwg.org/specs/rfc9110.html#field.content-length:~:text=an%20origin%20server%20SHOULD%20send%20a%20Content%2DLength%20header

> ...an origin server SHOULD send a Content-Length header field when the content size is known prior to sending the complete header section...

But maybe I'm looking at a wrong specification?

**Comment by ddugovic** [comment] 2022-11-23 12:13
Can a maintainer confirm that axios is supposed to be able to decompress response data?

https://github.com/axios/axios/blob/a3d901777bc06e78adae3081f694cdbf76241303/test/unit/adapters/http.js#L469

**Comment by nickali2** [comment] 2022-11-24 09:22
same issue
using latest release (1.2.0) after using get method as below, I receive weird data:
```
axios.get('https://jsonplaceholder.typicode.com/posts/8')
  .then(function (response) {
    // handle success
    console.log(response.data);
  })
```
this is what I received: 
`� �:{y  z
���T�♠��∟�zR�����:9p�v�0►�a
�►i��|��r\��)�ͧ�V<�▬ ��§������"ձ��¶Th��n��*��ɝ�N3�0��&♣▼�◄D
}�ύ��#�ê(�S     cwXX�N'T�_5
%��▼!m�C��      §��
��↓�ϽY�p��:*;H|�-v↨�SJ8>����`

using latest alpha pre-release(1.2.0alpha-prerelease) for the same code  worked perfect and received  this:
`{
  userId: 1,
  id: 8,
  title: 'dolorem dolore est ipsam',
  body: 'dignissimos aperiam dolorem qui eum\n' +
    'facilis quibusdam animi sint suscipit qui sint possimus cum\n' +
    'quaerat magni maiores excepturi\n' +
    'ipsam ut commodi dolor voluptatum modi aut vitae'
}`

**Comment by gggggihggg** [comment] 2022-11-24 13:05
I had this problem too, and it was fixed when I downgraded it to 1.0

**Comment by Tallyb** [comment] 2022-11-24 14:24
Seems like it is only a problem for get request and not for post. is that possible?

**Comment by uxbert-fe** [comment] 2022-11-24 14:31
> Seems like it is only a problem for get request and not for post. is that possible?

I face this in post requests as well. Has to downgrade to 1.1.x

**Comment by Christophosaurus** [comment] 2022-11-24 14:47
> > Seems like it is only a problem for get request and not for post. is that possible?
> 
> I face this in post requests as well. Has to downgrade to 1.1.x

I also face the issue with post requests. adding header`'Accept-Encoding': 'identity',` resulted in expected responses without having to downgrade.

**Comment by uxbert-fe** [comment] 2022-11-24 14:54
> I also face the issue with post requests. adding header`'Accept-Encoding': 'identity',` resulted in expected responses without having to downgrade.

confirmed working. But getting this error `Refused to set unsafe header "Accept-Encoding"`

**Comment by Tallyb** [comment] 2022-11-24 15:07
Downgraded as well.

**Comment by DenverCoder1** [comment] 2022-11-24 15:53
This is not the fist time. Changing from 0.27.2 to 1.0.0 also broke the most basic GET request example and it wasn't repaired until 1.1.0.

I've migrated everything from axios to node-fetch since I don't think I can trust axios to not release broken versions anymore.

**Comment by rcoundon** [comment] 2022-11-24 17:08
> Seems like it is only a problem for get request and not for post. is that possible?

We've seen the issue with POSTs too

**Comment by mo4islona** [comment] 2022-11-25 10:41
Faced same issue. 1.2.0 broke our production as well

**Comment by RPainter8West** [comment] 2022-11-25 11:14
The troubling thing here is this is a major regression that's been known about for too long and not addressed.   This should have been caught in a beta phase, and the release blocked. I thought axios was a trustworthy library, but I'm having my doubts now.

**Comment by rcoundon** [comment] 2022-11-25 17:51
This is a pretty serious regression and I wasted a lot of time hunting it down but version updates to library dependencies really shouldn't break production systems (unless it was due to a 'sub dependency')
IMHO dependency versions should be fixed and a change to the version requires tests to be rerun (manual or automatic) before things make it into production environment.

Using ^ or ~ in package.json is a recipe for best case - breaking production environments when CI/CD systems can automatically perform upgrades, and worst case introduce malicious code ([remember](https://blog.openreplay.com/another-npm-package-is-highjacked-and-it-s-your-fault-that-this-happened)

In the case of yarn we should use --frozen-lockfile

If everyone fixed their dependencies, the supply chain would be so much more robust!

**Comment by Luxcium** [comment] 2022-11-27 11:14
I guess it is prohibited 🚫 to rant as it is not something constructive and it is not adding helpful information but I must admit that I am unable to understand what is the problem I have installed a previous version and I am all right now but I have been trying to convert a lot of my code into using Puppeteer when in fact it was not me or the website I was trying to visit that was at fault... I never thought it would have been because of Axios since it is developed by professionals who have a solid CI/CD deployment framework in place (Do you know what CI/CD means I will assume yes)... 

But I have been trying to find solutions on your website and it dose not mention that it would be required to update my code for it to work: 

![image](https://user-images.githubusercontent.com/42672814/204132223-b26a76e4-1937-4474-916f-b5446ebef71c.jpeg)

**Comment by amandujano** [comment] 2022-11-29 16:26
also downgrading version to fix this problem

**Comment by Tronikelis** [comment] 2022-11-29 18:34
Massive respect to the axios team for creating & maintaining this awesome http client, but I just can't seem to wrap my head around this issue, (probably) everyone that installs the latest version will have this broken behavior leading to a lot of dev time wasted debugging this issue, because I am assuming that most people trust axios enough to not release a version with a major bug like this one.

**Comment by RPainter8West** [comment] 2022-11-29 21:56
It's 7 days now that the latest version is broken. Would you please release a 1.2.1 version with a rollback of the problematic change if a proper fix is not available?

**Comment by jeffwilcox** [comment] 2022-11-29 22:13
I've just submitted a one-time $99 sponsorship here on top of my monthly support to show my support for seeing this prioritized. Happy to lend a hand validating or testing as well.

**Comment by TomFrankly** [comment] 2022-11-29 22:27
I'm getting ready to publish a coding tutorial that heavily utilizes axios. Going to ask Glitch, Replit, and Pipedream if they can auto-downgrade axios due to this issue; it's going to confuse a lot of newbies.

Even an extremely simple GET request to PokeAPI is currently impossible with this release.

**Closed** 2022-12-01 14:22 UTC

**Comment by dondre** [comment] 2022-12-05 05:13
Here's how I fixed in the issue without downgrading.

```
import _axios from "axios";

const axios = _axios.create({
    headers: {
        'Accept-Encoding': '*',
    }
})
```

**Comment by jasonsaayman** [comment] 2022-12-05 07:14
Going to release these changes tonight
