### ISSUE TITLE
Improve axios stack traces

### ISSUE THREAD

**Issue by rclmenezes** [axios/axios#2387] opened 2019-09-03 19:10 UTC
Currently, if you use axios with async / await, you get a stack trace like this:

```
Request failed with status code 500
    at createError (/Users/rmenezes/code/seedfi/web/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/rmenezes/code/seedfi/web/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/rmenezes/code/seedfi/web/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:208:15)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11
```

It doesn't show you much about *what* called Axios., which makes debugging quite difficult!

This is because `settle` calls `createError`:
https://github.com/axios/axios/blob/master/lib/core/settle.js#L12-L24

Which creates a new error with a brand new stack trace:
https://github.com/axios/axios/blob/master/lib/core/createError.js#L15-L18

Perhaps we can fix this by creating an error before the request goes out and stitching it to the new error's stack trace?

**Comment by applechips** [comment] 2019-10-04 17:55
i have similar error but with code `403` when i am using async await:
```
Request failed with status code 403
    at createError (node_modules/axios/lib/core/createError.js:16:15)
    at settle (node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:237:11)
```

**Comment by jmicco** [comment] 2019-10-19 04:27
This makes it super hard to debug bad responses from other servers when you are making lots of calls.

**Comment by abihf** [comment] 2019-10-24 05:00
Maybe axios can use https://stackoverflow.com/a/42755876

**Comment by WarisR** [comment] 2019-12-02 12:17
@jmicco I don't understand why this makes it super hard to debug.
Is it still super hard if I use this pattern? https://stackoverflow.com/a/42755876 (merge stacktrace)
Could you please give me more example? Thank you.

**Comment by jmicco** [comment] 2019-12-09 01:01
Hi Waris,

Stack traces for async functions in Node are difficult to deal with and
adding catch / rethrow into code to tease out the stack trace does not seem
practical.  When we get a trace from Axios our code is never listed on the
stack making it hard to understand where we got the problem.  We are
calling several different other micro-services and it is not clear which
call received an error.  It would be very convenient if code were added to
axios to improve the stack traces that get thrown for all consumers exactly
once - although I do understand that this is more of a NodeJS asynchronous
function problem and it is not really axios specific.

Thanks for listening!

Cheers,
John

**Comment by abihf** [comment] 2019-12-09 15:45
Hi @jmicco 

It seems the problem is axios discard original error and create new error instead of reusing original error (with original stack trace). Please correct me if i'm wrong.

**Comment by captealc** [comment] 2020-01-07 18:36
Bump up.Turning on async stacktraces on newest node does not help. 
This is a real issue, e.g when you make multiple HTTP calls and all you get is an info that some failed somewhere.

**Comment by cesco69** [comment] 2020-01-08 10:53
Another way is implement a new option for customize error message, eg.:

```js
axios({
  method: 'get',
  url: 'http://bit.ly/2mTM3nY',
  customErrorMessage: (response) =>  'Request at URL '+ response.config.url +' failed with status code ' + response.status
})
.then(response=> console.log(response))
.catch(error => console.log(error));
```

this just require a minimal implementation in https://github.com/axios/axios/blob/master/lib/core/settle.js

```javascript
'use strict';

var createError = require('./createError');

/**
 * Resolve or reject a Promise based on response status.
 *
 * @param {Function} resolve A function that resolves the promise.
 * @param {Function} reject A function that rejects the promise.
 * @param {object} response The response.
 */
module.exports = function settle(resolve, reject, response) {
  var validateStatus = response.config.validateStatus;
  if (!validateStatus || validateStatus(response.status)) {
    resolve(response);
  } else {
    var customErrorMessage = response.config.customErrorMessage;
    var message = customErrorMessage ? customErrorMessage(response) : 'Request failed with status code ' + response.status;
    reject(createError(
      message,
      response.config,
      null,
      response.request,
      response
    ));
  }
};
```

**Comment by rafaelalmeidatk** [comment] 2020-01-15 02:07
In case anyone needs a solution for this, I have managed to solve the stack trace problem storing the current stack trace in a variable and replacing it before throwing the error:

```js
const { stack } = new Error();

return instance.get(endpoint, { params, ...config }).catch(error => {
  error.stack = stackTrace;
  throw error;
});
```

I explained everything here: https://github.com/rafaelalmeidatk/TIL/issues/4

**Comment by sadokmtir** [comment] 2020-06-28 21:14
no updates regarding this issue ?

**Comment by jekh** [comment] 2020-07-01 07:25
I've managed to work around this issue by using interceptors. I create an Error in a request interceptor, store it on a config property, then use its stack trace in the response interceptor's error handler. This is obviously less than ideal and it would be better to not clobber the stack trace in the first place.

```ts
const client = axios.create();

client.interceptors.request.use(config => {
 config.errorContext = new Error("Thrown at:");
 return config;
});

client.interceptors.response.use(undefined, async error => {
  const originalStackTrace = error.config?.errorContext?.stack;
  if (originalStackTrace) {
    error.stack = `${error.stack}\n${originalStackTrace}`;
  }

  throw error;
});
```

This results in pretty reasonable stack traces:
```
Error: getaddrinfo ENOTFOUND junk.blackhole
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
Error: Thrown at:
    at /home/code/node/src/utils/axios.ts:35:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at IntegrationClient.getReport (/home/code/node/src/clients/IntegrationClient.ts:80:24)
```
```
Error: Request failed with status code 404
    at createError (/home/code/node/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/code/node/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/code/node/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:322:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Thrown at:
    at /home/code/node/src/utils/axios.ts:35:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at IntegrationClient.getReport (/home/code/node/src/clients/IntegrationClient.ts:80:24)
```

**Comment by philios33** [comment] 2020-11-04 17:10
As a personal rule of thumb, due to this issue I always use

`validateStatus: () => true`

and handle the `result.status` code myself, throwing proper errors if I need to.

**Comment by svsool** [comment] 2020-12-03 08:33
The interceptors' approach proposed by @jekh for some reason was not showing the exact method that initiated a request for me, but I managed to get a similar stack trace by patching `post, put, patch, delete, get, head, options, request` axios methods. It's implemented as part of [axios-better-stacktrace](https://github.com/svsool/axios-better-stacktrace) plugin. I hope it helps until the original problem is fixed.

**Comment by margalit** [comment] 2021-02-01 03:37
> The interceptors' approach proposed by @jekh for some reason was not showing the exact method that initiated a request for me, but I managed to get a similar stack trace by patching `post, put, patch, delete, get, head, options, request` axios methods. It's implemented as part of [axios-better-stacktrace](https://github.com/svsool/axios-better-stacktrace) plugin. I hope it helps until the original problem is fixed.

This worked perfectly for us. Thank you @svsool!

**Comment by jasonsaayman** [comment] 2021-05-14 14:04
Please use the interceptor approach mentioned above, we will address this in the future however currently an interceptor is the most appropriate solution.

**Comment by Merlin-Taylor** [comment] 2021-07-06 13:32
I have replaced native Promises with [Bluebird](http://bluebirdjs.com/) in my application. Bluebird supports [long stack traces](http://bluebirdjs.com/docs/features.html#long-stack-traces) and I now have decent stack traces across async boundaries, including calls to axios methods.

**Comment by Frondor** [comment] 2021-08-22 20:32
> Please use the interceptor approach mentioned above, we will address this in the future however currently an interceptor is the most appropriate solution.

Hi  @jasonsaayman, I see this issue brings lots of headaches and a bad developer experience to those who fall into these scenarios without any knowledge about the need of such interceptor.

I don't think that's the best solution and imho, it degrades Axios as a good library for production-ready applications.

A fix should be as easy as implementing something like

https://github.com/axios/axios/blob/5bc9ea24dda14e74def0b8ae9cdb3fa1a0c77773/lib/core/createError.js#L16-L17

to 
```js
var axiosError = enhanceError(new Error(message), config, code, request, response);
if (Error.captureStackTrace) Error.captureStackTrace(axiosError, createError);
return axiosError;
```

Yes, it may degrade performance for failing requests, but we all know this is better than having no input for proper debuging.

I can open a PR with this and discuss the approach if you want.

**Comment by PetrShchukin** [comment] 2021-11-19 13:30
Hi all, for me neither interceptors not axios-better-stacktrace package didn't help. Once it enters into an interceptor it looses all stack trace.
This is what I see when I do console.log(new Error()) before axios request
````
Error: Hello getMaterials
    at EthosProxyAPIService.getMaterials (C:\_CR\crossreg-core\src\internal-http\ethos-proxy-api\ethos-proxy-api.service.ts:69:17)
    at SubjectsService.test (C:\_CR\registration-api\src\apps\subjects\subjects.service.ts:11:38)
    at SubjectsController.getTest2 (C:\_CR\registration-api\src\apps\subjects\subjects.controller.ts:16:32)
    at C:\_CR\registration-api\node_modules\@nestjs\core\router\router-execution-context.js:38:29
    at InterceptorsConsumer.intercept (C:\_CR\registration-api\node_modules\@nestjs\core\interceptors\interceptors-consumer.js:11:20)
    at C:\_CR\registration-api\node_modules\@nestjs\core\router\router-execution-context.js:46:60
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at C:\_CR\registration-api\node_modules\@nestjs\core\router\router-proxy.js:9:17
````
And this is what I see in my first interceptor
````
Error: Hello
    at C:\_CR\crossreg-core\src\context\interceptor-correlation.service.ts:16:19
    at C:\_CR\crossreg-core\node_modules\lodash\lodash.js:5177:46
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
````

**Comment by bytenik** [comment] 2022-03-30 21:43
> I have replaced native Promises with [Bluebird](http://bluebirdjs.com/) in my application. Bluebird supports [long stack traces](http://bluebirdjs.com/docs/features.html#long-stack-traces) and I now have decent stack traces across async boundaries, including calls to axios methods.

How did you do this in a way that Axios then uses Bluebird promises?

**Comment by despreston** [comment] 2022-04-25 15:51
> > Please use the interceptor approach mentioned above, we will address this in the future however currently an interceptor is the most appropriate solution.
> 
> Hi @jasonsaayman, I see this issue brings lots of headaches and a bad developer experience to those who fall into these scenarios without any knowledge about the need of such interceptor.
> 
> I don't think that's the best solution and imho, it degrades Axios as a good library for production-ready applications.
> 
> A fix should be as easy as implementing something like
> 
> https://github.com/axios/axios/blob/5bc9ea24dda14e74def0b8ae9cdb3fa1a0c77773/lib/core/createError.js#L16-L17
> 
> to
> 
> ```js
> var axiosError = enhanceError(new Error(message), config, code, request, response);
> if (Error.captureStackTrace) Error.captureStackTrace(axiosError, createError);
> return axiosError;
> ```
> 
> Yes, it MAY degrade performance (imo its negligible) for failing requests, but we all know this is better than [having no input for proper debugging](https://dev.to/frondor/how-to-not-write-async-code-in-express-handlers-based-on-a-true-story-44j2).
> 
> I can open a PR with this and discuss the approach if you want.

@jasonsaayman I didnt see any PRs from the original commenter and I'm happy to complete this. Is this still relevant?

**Comment by jasonsaayman** [comment] 2022-04-25 16:37
You can for sure, please check master we made a whole load of changes to the way errors work for the next release

**Comment by doronhorwitz** [comment] 2023-05-30 11:41
> > > Please use the interceptor approach mentioned above, we will address this in the future however currently an interceptor is the most appropriate solution.
> > 
> > 
> > Hi @jasonsaayman, I see this issue brings lots of headaches and a bad developer experience to those who fall into these scenarios without any knowledge about the need of such interceptor.
> > I don't think that's the best solution and imho, it degrades Axios as a good library for production-ready applications.
> > A fix should be as easy as implementing something like
> > https://github.com/axios/axios/blob/5bc9ea24dda14e74def0b8ae9cdb3fa1a0c77773/lib/core/createError.js#L16-L17
> > 
> > to
> > ```js
> > var axiosError = enhanceError(new Error(message), config, code, request, response);
> > if (Error.captureStackTrace) Error.captureStackTrace(axiosError, createError);
> > return axiosError;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Yes, it MAY degrade performance (imo its negligible) for failing requests, but we all know this is better than [having no input for proper debugging](https://dev.to/frondor/how-to-not-write-async-code-in-express-handlers-based-on-a-true-story-44j2).
> > I can open a PR with this and discuss the approach if you want.
> 
> @jasonsaayman I didnt see any PRs from the original commenter and I'm happy to complete this. Is this still relevant?

Did @despreston's [pull request](https://github.com/axios/axios/pull/4624) (which was an implementation of @Frondor's suggestion) actually fix the problem? I'm running Node v18.16.0 and axios v1.4.0 and still getting stacktraces like what @rclmenezes was seeing at the beginning of this issue.

**Comment by emilio-notable** [comment] 2023-05-30 11:41
Hello &#x27;Doron,

Thank you for contacting us!  The Notable office is currently closed in observance of the Memorial Day Holiday.

We will resume normal business hours on Tuesday, May 30th from 9am to 9pm EST and look forward to assisting you at that time.
​

Best Regards,
The Notable Team

**Comment by AndyOooh** [comment] 2023-08-01 13:16
> > > > Please use the interceptor approach mentioned above, we will address this in the future however currently an interceptor is the most appropriate solution.
> > > 
> > > 
> > > Hi @jasonsaayman, I see this issue brings lots of headaches and a bad developer experience to those who fall into these scenarios without any knowledge about the need of such interceptor.
> > > I don't think that's the best solution and imho, it degrades Axios as a good library for production-ready applications.
> > > A fix should be as easy as implementing something like
> > > https://github.com/axios/axios/blob/5bc9ea24dda14e74def0b8ae9cdb3fa1a0c77773/lib/core/createError.js#L16-L17
> > > 
> > > to
> > > ```js
> > > var axiosError = enhanceError(new Error(message), config, code, request, response);
> > > if (Error.captureStackTrace) Error.captureStackTrace(axiosError, createError);
> > > return axiosError;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Yes, it MAY degrade performance (imo its negligible) for failing requests, but we all know this is better than [having no input for proper debugging](https://dev.to/frondor/how-to-not-write-async-code-in-express-handlers-based-on-a-true-story-44j2).
> > > I can open a PR with this and discuss the approach if you want.
> > 
> > 
> > @jasonsaayman I didnt see any PRs from the original commenter and I'm happy to complete this. Is this still relevant?
> 
> Did @despreston's [pull request](https://github.com/axios/axios/pull/4624) (which was an implementation of @Frondor's [suggestion](https://github.com/axios/axios/issues/2387#issuecomment-903326573)) actually fix the problem? I'm running Node v18.16.0 and axios v1.4.0 and still getting stacktraces like what @rclmenezes was seeing at the beginning of this issue.

Same for me running same versions of Node and axios. When making identical requests made with _fetch_  gives me the stack trace I need but with axios 1.4.0 I only get the library stack.
Is there some config that needs to be set?

**Comment by jasonsaayman** [comment] 2023-08-01 20:28
will have a look

**Comment by jedkass** [comment] 2023-09-25 15:17
@jasonsaayman Were you possibly able to confirm @despreston's change? Does `1.5.0` address this in full?

**Comment by miso-belica** [comment] 2023-09-25 15:27
@jedkass for me the stack traces are still quite useless. At least in Sentry with Axios v1.5.0. I am running Node.js v20.7.0.

<details>
<summary>Screenshot of stack trace from Sentry</summary>

![image](https://github.com/axios/axios/assets/1072330/f849101c-0c15-43e1-a8b3-ea8a674846c1)

</details>

**Comment by jedkass** [comment] 2023-09-25 17:22
Ah that's a shame. @jasonsaayman Shouldn't we reopen this issue in that case? Or is this being tracked elsewhere?

**Comment by ikonst** [comment] 2023-09-28 03:06
I don't see how #4624 would improve things. You'd need to capture the stack when you make the request, not from within `settle` when you're creating an error. (FWIW, Node already stamps it with a stack the moment you throw it.)

**Comment by jasonsaayman** [comment] 2023-09-29 08:15
reopening, that sucks

**Comment by andrew0** [comment] 2023-10-06 14:31
I also ran into this issue and was able to get more usable stack traces by applying this patch to axios@1.5.0:

```
diff --git a/dist/node/axios.cjs b/dist/node/axios.cjs
index adce59e4733b2520cff2c7354411fb3d32dfdd75..224ba7d01dc3a53b3e62ede6566275864f53a669 100644
--- a/dist/node/axios.cjs
+++ b/dist/node/axios.cjs
@@ -3779,7 +3779,19 @@ class Axios {
    *
    * @returns {Promise} The Promise to be fulfilled
    */
-  request(configOrUrl, config) {
+  async request(configOrUrl, config) {
+    try {
+      return await this._dispatchRequest(configOrUrl, config);
+    } catch (err) {
+      if (err instanceof Error) {
+        Error.captureStackTrace(err, Axios.prototype.request);
+      }
+
+      throw err;
+    }
+  }
+
+  _dispatchRequest(configOrUrl, config) {
     /*eslint no-param-reassign:0*/
     // Allow for axios('example/url'[, config]) a la fetch API
     if (typeof configOrUrl === 'string') {
```

The same patch could be applied to lib/core/Axios.js if you're using ESM.

After applying that patch and running this script:

```js
const axios = require('axios');

async function makeRequest() {
  await axios.get('https://httpstat.us/500');
}

async function main() {
  await makeRequest();
}

main().catch((err) => {
  console.error(err.stack);
});
```

I get this stacktrace:

```
AxiosError: Request failed with status code 500
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async makeRequest (test.js:4:3)
    at async main (test.js:8:3)
```

**Comment by ikonst** [comment] 2023-10-06 14:55
This is a pretty good place to add it, given how `request` can call all those interceptors. But we should probably attach the original exception as a cause.

**Comment by ikonst** [comment] 2023-10-06 15:06
Also, not sure how standard `Error.captureStackTrace` is. It's in V8 but not in Firefox.

**Comment by ikonst** [comment] 2023-10-06 15:42
@andrew0 made #5987 based on your suggestion

**Comment by rickgm** [comment] 2023-10-26 12:00
> @andrew0 made #5987 based on your suggestion

@jasonsaayman will you consider merging this?

**Comment by jedkass** [comment] 2024-01-24 18:27
@jasonsaayman @andrew0 It looks like @ikonst's PR has been idle for a little bit since its last review. Is there any chance we might be able to get another round of review on it? 🙏

**Closed** 2024-01-24 22:21 UTC

**Comment by jasonsaayman** [comment] 2024-10-28 14:31
might make sense to open a new issue @maxiedaniels
