### ISSUE TITLE
Post formdata with application/x-www-form-urlencoded is changed to multipart/form-data

### ISSUE THREAD

**Issue by fkranenburg** [axios/axios#3019] opened 2020-06-12 14:08 UTC
**Describe the bug**
I am trying to post some data with content type application/x-www-form-urlencoded but the content type is changed to multipart/form-data; when I do a post of formdata

**To Reproduce**
The situation is reproducable here: [https://codepen.io/ferrykranenburg/pen/abdZrGG](https://codepen.io/ferrykranenburg/pen/abdZrGG)

```js
var bodyFormData = new FormData();
bodyFormData.set("dbpath", "somedata");
bodyFormData.set("username", "somedata");
bodyFormData.set("password", "somedata");
bodyFormData.set("token", "somedata");

axios({
  method: "post",
  url: "https://dev07.changetocomm.net/ac/api/credentials/",
  data: bodyFormData,
  headers: { "content-type": "application/x-www-form-urlencoded" }
});
```

**Expected behavior**
The post should be done with 'application/x-www-form-urlencoded' like I'm adding to the headers.

**Environment:**
 - Axios Version [e.g. 0.19.2]
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: latest

**Additional context/Screenshots**
See screenshot, the post is done with multipart/form-data header.
![image](https://user-images.githubusercontent.com/5680394/84625491-a8249380-aee3-11ea-85fc-dc39d67b6f9b.png)

**Comment by chinesedfan** [comment] 2020-06-14 16:01
It shouldn't be. Can you follow the issue template to provide required informations?

**Comment by fkranenburg** [comment] 2020-06-15 06:39
@chinesedfan I updated my question using the template.

**Comment by chinesedfan** [comment] 2020-06-15 07:08
I see. Duplicate of #1603. Let's track there.

**Closed by chinesedfan** 2020-06-15 07:08 UTC
Labels: status:more info needed
