### ISSUE TITLE
Make Axios easier to use for Node.js and Request users

### ISSUE THREAD

**Issue by bajtos** [axios/axios#2741] opened 2020-02-14 15:37 UTC
**Is your feature request related to a problem? Please describe.**

I am a lead maintainer of [LoopBack](https://loopback.io), a REST API framework for Node.js. Recently, [request](https://www.npmjs.com/package/request) has been deprecated (see https://github.com/request/request/issues/3142) and we started to look for alternatives (see https://github.com/request/request/issues/3143). We picked Axios as the best option.

However, while migrating from `request` to `axios`, we found small API incompatibilities that are making migration more tedious than I would like to.

- `request` options have `uri` field, `axios` has `url`
- `request` accepts `proxy` specified as a URL string (e.g. `http://localhost:8080`), `axios` requires the URL to be parsed into components
- `request` (and Node.js) provides `statusCode` property on the response object, `axios` provides `status` only
- `request` (and other popular clients like [superagent](https://github.com/visionmedia/superagent)) store the buffered response body in `body` property, `axios` uses `data` instead. (Also on the server, Express middleware provide `req.body` property.)

**Describe the solution you'd like**

- Enhance Axios to accept request-like configuration options as aliases to Axios options.
- Enhance the response object returned by Axios to provide property getters to offer request-like API (e.g. `class AxiosResponse { get body() { return this.data }}`).

**Describe alternatives you've considered**

Create a wrapper function that will massage request options from `request` to `axios` format and then add additional fields to the response object returned by axios.

```js
async function makeRequest(options) {
  if (!options.url && options.uri) {
    options.url = options.uri;
    delete options.uri;
  }
  // etc.
  const response = axios(options);
  response.body = response.data;
  response.statusCode = response.status;
  return response;
}
```

**Additional context**

I am happy to contribute a pull request to implement those enhancements. However, I'd like to first check with you which of them are likely to be accepted. I also see 147 open pull request, it makes me wonder how likely would such pull request be reviewed and merged?

/cc @raymondfeng

**Comment by chinesedfan** [comment] 2020-02-15 06:30
Personally, I will suggest your wrapper solution. As axios is a tiny core, which requires users to implement their own customized functionalities. Maybe someday your wrapper can be added to https://github.com/axios/axios/blob/master/ECOSYSTEM.md.

**Comment by bajtos** [comment] 2020-02-18 13:51
Thank you @chinesedfan for a quick response, I appreciate it!

I understand your point and the reluctance to add my proposed API. I think my proposal would be a pretty small change, but I respect your opinion as a maintainer.

I'd like to discuss the proxy handling though. AFAICT, axios already contains code for parsing proxy configuration from a string (e.g. `HTTP_PROXY` environment variable).

https://github.com/axios/axios/blob/12e00b8018ddfb078800ebc548879723665b4bce/lib/adapters/http.js#L102-L104

Would you consider accepting an improvement to apply this parsing logic to `config.proxy` option too? I think the change could be very small, something along the following lines:

```js
if (typeof config.proxy === 'string') {
  config.proxy = url.parse(config.proxy);
}
```

IMO, this will make Axios much easier to use for everybody.

What do you think?

**Comment by chinesedfan** [comment] 2020-02-19 10:51
@bajtos Hard to say reject, because it is different with other naming things. If you or someone send a pull request with sufficient tests, I am glad to review. But please make psychological preparations that it requires time to be really merged and released. And also keep an eye on it once regressions are introduced.

**Comment by jasonsaayman** [comment] 2021-05-16 14:35
Hi,

Thank you for submitting the above issue. It seems the issue has gone stale. Should you feel that this issue still exists please submit a new issue.

Thanks

**Closed by jasonsaayman** 2021-05-16 14:35 UTC
Labels: type:enhancement
